<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Introduction | Estonian Human Development Report 2019/2020</title>
  <meta name="description" content="Spatial Choices for an Urbanised Society" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Introduction | Estonian Human Development Report 2019/2020" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="https://inimareng.ee/cover.png" />
  <meta property="og:description" content="Spatial Choices for an Urbanised Society" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction | Estonian Human Development Report 2019/2020" />
  
  <meta name="twitter:description" content="Spatial Choices for an Urbanised Society" />
  <meta name="twitter:image" content="https://inimareng.ee/cover.png" />




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="foreword.html"/>
<link rel="next" href="diversity-in-the-estonian-living-environment.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.3/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.3/leaflet-providers-plugin.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-168674881-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-168674881-1');
</script>
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#a94b23">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="../eia.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="estonian-human-development-report-20192020.html"><a href="estonian-human-development-report-20192020.html"><i class="fa fa-check"></i>Estonian Human Development Report 2019/2020</a><ul>
<li class="chapter" data-level="" data-path="foreword.html"><a href="foreword.html"><i class="fa fa-check"></i>Foreword</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#põhisõnumid"><i class="fa fa-check"></i>Põhisõnumid</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#estonia-has-advanced-to-30th-position-in-the-world-in-terms-of-human-development-but-has-since-stalled"><i class="fa fa-check"></i>Estonia has advanced to 30th position in the world in terms of human development, but has since stalled</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#estonias-metropolisation-is-reflected-in-the-continued-growth-of-the-greater-tallinn-urban-area-where-people-economic-activity-and-services-are-concentrating-while-the-rest-of-estonia-is-shrinking-and-degenerating"><i class="fa fa-check"></i>Estonia’s metropolisation is reflected in the continued growth of the Greater Tallinn urban area, where people, economic activity and services are concentrating, while the rest of Estonia is shrinking and degenerating</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#the-multilocality-enjoyed-by-people-living-in-estonian-connects-tallinn-with-the-counties-and-the-cities-with-the-villages"><i class="fa fa-check"></i>The multilocality enjoyed by people living in Estonian connects Tallinn with the counties, and the cities with the villages</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#public-debate-results-in-a-better-living-environment-and-greater-consensus"><i class="fa fa-check"></i>Public debate results in a better living environment and greater consensus</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#built-heritage-and-natural-areas-as-part-of-our-culture-strengthen-peoples-relationship-with-the-environment-and-their-sense-of-belonging"><i class="fa fa-check"></i>Built heritage and natural areas as part of our culture strengthen people’s relationship with the environment and their sense of belonging</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#future-perspectivese"><i class="fa fa-check"></i>Future perspectivese</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="diversity-in-the-estonian-living-environment.html"><a href="diversity-in-the-estonian-living-environment.html"><i class="fa fa-check"></i><b>1</b> Diversity in the Estonian living environment</a><ul>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#points-of-departure"><i class="fa fa-check"></i>Points of departure</a></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#articles-in-this-chapter"><i class="fa fa-check"></i>Articles in this chapter</a></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#estonia-in-the-international-context"><i class="fa fa-check"></i>Estonia in the international context</a></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#how-do-we-move-forward"><i class="fa fa-check"></i>How do we move forward?</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="1.1" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><i class="fa fa-check"></i><b>1.1</b> Changes in land use: distortion of the meaning of urban and rural</a><ul>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#population-decline-and-migration-to-urban-regions-affect-landscapes"><i class="fa fa-check"></i>Population decline and migration to urban regions affect landscapes</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#built-up-areas-are-increasing-mostly-around-cities"><i class="fa fa-check"></i>Built-up areas are increasing mostly around cities</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#urban-sprawl-reduces-the-diversity-of-the-use-of-space-in-urban-areas-and-their-surroundings"><i class="fa fa-check"></i>Urban sprawl reduces the diversity of the use of space in urban areas and their surroundings</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#agricultural-landscape-is-shrinking-and-becoming-less-populated"><i class="fa fa-check"></i>Agricultural landscape is shrinking and becoming less populated</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#forest-land-is-growing-but-we-have-less-coniferous-forests-and-the-forests-are-becoming-younger"><i class="fa fa-check"></i>Forest land is growing but we have less coniferous forests and the forests are becoming younger</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#the-preservation-of-valuable-agricultural-lands-restrains-landscape-changes"><i class="fa fa-check"></i>The preservation of valuable agricultural lands restrains landscape changes</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#protecting-valuable-landscapes-and-conservation-areas-helps-preserve-the-overall-appearance-of-landscapes"><i class="fa fa-check"></i>Protecting valuable landscapes and conservation areas helps preserve the overall appearance of landscapes</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="increasing-regional-polarisation-in-estonia.html"><a href="increasing-regional-polarisation-in-estonia.html"><i class="fa fa-check"></i><b>1.2</b> Increasing regional polarisation in Estonia</a><ul>
<li class="chapter" data-level="" data-path="increasing-regional-polarisation-in-estonia.html"><a href="increasing-regional-polarisation-in-estonia.html#peripheralisation-is-self-reproducing"><i class="fa fa-check"></i>Peripheralisation is self-reproducing</a></li>
<li class="chapter" data-level="" data-path="increasing-regional-polarisation-in-estonia.html"><a href="increasing-regional-polarisation-in-estonia.html#the-stigmatisation-of-rural-areas-and-small-towns-exacerbates-peripheralisation"><i class="fa fa-check"></i>The stigmatisation of rural areas and small towns exacerbates peripheralisation</a></li>
<li class="chapter" data-level="" data-path="increasing-regional-polarisation-in-estonia.html"><a href="increasing-regional-polarisation-in-estonia.html#competitiveness-based-regional-policy-has-not-reduced-peripheralisation"><i class="fa fa-check"></i>Competitiveness-based regional policy has not reduced peripheralisation</a></li>
<li class="chapter" data-level="" data-path="increasing-regional-polarisation-in-estonia.html"><a href="increasing-regional-polarisation-in-estonia.html#the-peripheral-status-and-image-of-a-place-sets-limits-to-its-competitiveness"><i class="fa fa-check"></i>The peripheral status and image of a place sets limits to its competitiveness</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li><a href="increasing-regional-polarisation-in-estonia.html#acknowledgements"><em>Acknowledgements</em></a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html"><i class="fa fa-check"></i><b>1.3</b> The triumph of planning freedom in suburban Estonia</a><ul>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#how-to-define-a-suburb"><i class="fa fa-check"></i>How to define a suburb?</a></li>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#one-tenth-of-estonians-live-in-the-suburbs"><i class="fa fa-check"></i>One-tenth of Estonians live in the suburbs</a></li>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#suburban-neighbourhoods-are-characterised-by-a-fragmented-settlement-structure"><i class="fa fa-check"></i>Suburban neighbourhoods are characterised by a fragmented settlement structure</a></li>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#the-pattern-of-a-new-suburb-emerges-as-the-sum-of-detailed-spatial-plans"><i class="fa fa-check"></i>The pattern of a new suburb emerges as the sum of detailed spatial plans</a></li>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#place-making-as-an-expression-of-market-forces-and-planning-policy"><i class="fa fa-check"></i>Place-making as an expression of market forces and planning policy</a></li>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#easily-accessible-public-services-and-spaces-are-limited-in-the-suburbs"><i class="fa fa-check"></i>Easily accessible public services and spaces are limited in the suburbs</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html"><i class="fa fa-check"></i><b>1.4</b> Modern living conditions – whose privilege?</a><ul>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#a-typical-person-in-estonia-lives-in-a-soviet-era-mass-housing-apartment-the-housing-stock-is-renewed-faster-in-the-capital-region"><i class="fa fa-check"></i>A typical person in Estonia lives in a Soviet-era mass housing apartment; the housing stock is renewed faster in the capital region</a></li>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#the-condition-of-the-housing-stock-is-improving-but-rural-housing-is-in-worse-condition"><i class="fa fa-check"></i>The condition of the housing stock is improving, but rural housing is in worse condition</a></li>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#financial-security-key-to-improved-living-conditions"><i class="fa fa-check"></i>Financial security: key to improved living conditions</a></li>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#the-housing-sector-was-fully-geared-towards-market-based-housing-after-independence-was-restored"><i class="fa fa-check"></i>The housing sector was fully geared towards market-based housing after independence was restored</a></li>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#new-public-sector-measures-have-been-introduced-over-time"><i class="fa fa-check"></i>New public-sector measures have been introduced over time</a></li>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#reconstruction-grants-help-to-improve-living-conditions-but-unevenly-across-regions"><i class="fa fa-check"></i>Reconstruction grants help to improve living conditions, but unevenly across regions</a></li>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#the-key-question-in-the-housing-sector-is-what-are-the-options-for-intervention"><i class="fa fa-check"></i>The key question in the housing sector is – what are the options for intervention?</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html"><i class="fa fa-check"></i><b>1.5</b> Accessibility changes in motorised Estonia</a><ul>
<li class="chapter" data-level="" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html#the-rapid-motorisation-of-the-1990s-is-stabilising"><i class="fa fa-check"></i>The rapid motorisation of the 1990s is stabilising</a></li>
<li class="chapter" data-level="" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html#motorisation-affects-the-environment-peoples-health-mobility-and-access-to-services"><i class="fa fa-check"></i>Motorisation affects the environment, people’s health, mobility and access to services</a></li>
<li class="chapter" data-level="" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html#life-in-low-density-areas-is-car-centred"><i class="fa fa-check"></i>Life in low-density areas is car-centred</a></li>
<li class="chapter" data-level="" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html#suburbs-are-more-car-centred-than-urban-centres"><i class="fa fa-check"></i>Suburbs are more car-centred than urban centres</a></li>
<li class="chapter" data-level="" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html#the-development-of-mobility-in-urban-centres-is-based-on-cars"><i class="fa fa-check"></i>The development of mobility in urban centres is based on cars</a></li>
<li class="chapter" data-level="" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html#future-trends-enabling-various-modes-of-mobility-in-suitable-volumes-will-reduce-the-use-of-cars"><i class="fa fa-check"></i>Future trends: enabling various modes of mobility in suitable volumes will reduce the use of cars</a></li>
<li><a href="increasing-regional-polarisation-in-estonia.html#acknowledgements"><em>Acknowledgements</em></a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="public-urban-space.html"><a href="public-urban-space.html"><i class="fa fa-check"></i><b>2</b> Public urban space</a><ul>
<li class="chapter" data-level="" data-path="introduction-2.html"><a href="introduction-2.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#points-of-departure"><i class="fa fa-check"></i>Points of departure</a></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#articles-in-this-chapter"><i class="fa fa-check"></i>Articles in this chapter</a></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#estonia-in-the-international-context"><i class="fa fa-check"></i>Estonia in the international context</a></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#how-do-we-move-forward"><i class="fa fa-check"></i>How do we move forward?</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="2.1" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html"><i class="fa fa-check"></i><b>2.1</b> Public space as an interconnecting network within the living environment</a><ul>
<li class="chapter" data-level="" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#public-space-is-a-network-connecting-peoples-homes-workplaces-and-other-activity-spaces"><i class="fa fa-check"></i>Public space is a network connecting people’s homes, workplaces and other activity spaces</a></li>
<li class="chapter" data-level="" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#the-quality-of-public-space-is-mainly-determined-by-its-continuity-for-all-users"><i class="fa fa-check"></i>The quality of public space is mainly determined by its continuity for all users</a></li>
<li class="chapter" data-level="" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#the-concept-of-public-space-has-not-been-defined-in-estonian-legislation"><i class="fa fa-check"></i>The concept of public space has not been defined in Estonian legislation</a></li>
<li class="chapter" data-level="" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#the-public-sector-has-not-established-itself-as-an-advocate-and-commissioning-party-for-public-space"><i class="fa fa-check"></i>The public sector has not established itself as an advocate and commissioning party for public space</a></li>
<li class="chapter" data-level="" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#the-public-space-can-only-function-as-a-network-if-the-state-and-local-governments-emphasise-it-in-spatial-decisions-at-every-level"><i class="fa fa-check"></i>The public space can only function as a network if the state and local governments emphasise it in spatial decisions at every level</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="built-heritage-and-spatial-quality.html"><a href="built-heritage-and-spatial-quality.html"><i class="fa fa-check"></i><b>2.2</b> Built heritage and spatial quality</a><ul>
<li class="chapter" data-level="" data-path="built-heritage-and-spatial-quality.html"><a href="built-heritage-and-spatial-quality.html#built-heritage-helps-to-create-diverse-space"><i class="fa fa-check"></i>Built heritage helps to create diverse space</a></li>
<li class="chapter" data-level="" data-path="built-heritage-and-spatial-quality.html"><a href="built-heritage-and-spatial-quality.html#the-conservation-of-existing-buildings-is-the-basis-for-sustainable-spatial-development"><i class="fa fa-check"></i>The conservation of existing buildings is the basis for sustainable spatial development</a></li>
<li class="chapter" data-level="" data-path="built-heritage-and-spatial-quality.html"><a href="built-heritage-and-spatial-quality.html#individual-spatial-decisions-have-a-major-impact-on-cultural-heritage-and-regional-development"><i class="fa fa-check"></i>Individual spatial decisions have a major impact on cultural heritage and regional development</a></li>
<li class="chapter" data-level="" data-path="built-heritage-and-spatial-quality.html"><a href="built-heritage-and-spatial-quality.html#monuments-are-a-common-good-and-a-shared-responsibility"><i class="fa fa-check"></i>Monuments are a common good and a shared responsibility</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html"><i class="fa fa-check"></i><b>2.3</b> Urban activism in the co-creation of public space</a><ul>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#urban-activism-as-a-political-activity-changes-in-time-and-its-form-varies-according-to-the-aims-pursued"><i class="fa fa-check"></i>Urban activism as a political activity changes in time and its form varies according to the aims pursued</a></li>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#urban-activism-implements-existing-models-and-invents-new-models-of-participatory-democracy"><i class="fa fa-check"></i>Urban activism implements existing models and invents new models of participatory democracy</a></li>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#urban-activism-spurs-the-development-of-civil-society"><i class="fa fa-check"></i>Urban activism spurs the development of civil society</a></li>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#the-impact-of-movements-and-individuals-involved-in-spatial-design-is-expressed-in-new-forms-of-participatory-culture"><i class="fa fa-check"></i>The impact of movements and individuals involved in spatial design is expressed in new forms of participatory culture</a></li>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#challenges-to-activism-in-urban-design"><i class="fa fa-check"></i>Challenges to activism in urban design</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#viidatud-allikad"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html"><i class="fa fa-check"></i><b>2.4</b> Data-driven spatial planning</a><ul>
<li class="chapter" data-level="" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html#open-access-spatial-data-can-only-benefit-society"><i class="fa fa-check"></i>Open-access spatial data can only benefit society</a></li>
<li class="chapter" data-level="" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html#first-steps-in-data-driven-spatial-planning-in-estonia"><i class="fa fa-check"></i>First steps in data-driven spatial planning in Estonia</a></li>
<li class="chapter" data-level="" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html#clear-connections-between-spatial-analyses-and-subsequent-decisions-are-rare"><i class="fa fa-check"></i>Clear connections between spatial analyses and subsequent decisions are rare</a></li>
<li class="chapter" data-level="" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html#high-time-to-introduce-data-driven-spatial-planning"><i class="fa fa-check"></i>High time to introduce data-driven spatial planning</a></li>
<li class="chapter" data-level="" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html#from-follower-to-leader"><i class="fa fa-check"></i>From follower to leader</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="natural-environment-as-a-public-good.html"><a href="natural-environment-as-a-public-good.html"><i class="fa fa-check"></i><b>3</b> Natural environment as a public good</a><ul>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#from-the-condition-of-the-natural-environment-to-environmental-justice-and-environmental-democracy"><i class="fa fa-check"></i>From the condition of the natural environment to environmental justice and environmental democracy</a></li>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#the-social-role-of-the-natural-environment-requires-better-monitoring"><i class="fa fa-check"></i>The social role of the natural environment requires better monitoring</a></li>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#the-overall-condition-of-estonian-nature-has-deteriorated"><i class="fa fa-check"></i>The overall condition of Estonian nature has deteriorated</a></li>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#the-options-for-spending-time-in-nature-are-narrowing"><i class="fa fa-check"></i>The options for spending time in nature are narrowing</a></li>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#neighbourhood-natural-areas-and-urban-green-spaces-require-more-attention-from-planners"><i class="fa fa-check"></i>Neighbourhood natural areas and urban green spaces require more attention from planners</a></li>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#future-perspectives"><i class="fa fa-check"></i>Future perspectives</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="3.1" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html"><i class="fa fa-check"></i><b>3.1</b> How do people use the natural environment in Estonia?</a><ul>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#the-public-use-of-the-estonian-natural-environment-is-based-on-everymans-right"><i class="fa fa-check"></i>The public use of the Estonian natural environment is based on everyman’s right</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#estonian-educational-and-hiking-trails-offer-good-recreational-opportunities"><i class="fa fa-check"></i>Estonian educational and hiking trails offer good recreational opportunities</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#the-number-of-visitors-to-conservation-areas-is-increasing-and-the-visitor-profiles-are-diversifying"><i class="fa fa-check"></i>The number of visitors to conservation areas is increasing and the visitor profiles are diversifying</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#towns-and-cities-have-many-green-spaces-but-their-quality-requires-attention"><i class="fa fa-check"></i>Towns and cities have many green spaces, but their quality requires attention</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#information-on-the-use-of-natural-areas-is-fragmentary"><i class="fa fa-check"></i>Information on the use of natural areas is fragmentary</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#half-of-the-population-go-berry-or-mushroom-picking"><i class="fa fa-check"></i>Half of the population go berry or mushroom picking</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#nature-education-mobility-and-landscape-planning-contribute-to-foraging-for-wild-produce"><i class="fa fa-check"></i>Nature education, mobility and landscape planning contribute to foraging for wild produce</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#hunting-combines-outdoorsmanship-with-meeting-societal-expectations"><i class="fa fa-check"></i>Hunting combines outdoorsmanship with meeting societal expectations</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#the-number-of-recreational-fishermen-in-estonia-is-stable"><i class="fa fa-check"></i>The number of recreational fishermen in Estonia is stable</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="the-impact-of-natural-areas-on-peoples-well-being.html"><a href="the-impact-of-natural-areas-on-peoples-well-being.html"><i class="fa fa-check"></i><b>3.2</b> The impact of natural areas on people’s well-being</a><ul>
<li class="chapter" data-level="" data-path="the-impact-of-natural-areas-on-peoples-well-being.html"><a href="the-impact-of-natural-areas-on-peoples-well-being.html#the-relationship-between-the-size-of-natural-areas-and-the-self-reported-health-of-estonian-adults"><i class="fa fa-check"></i>The relationship between the size of natural areas and the self-reported health of Estonian adults</a></li>
<li class="chapter" data-level="" data-path="the-impact-of-natural-areas-on-peoples-well-being.html"><a href="the-impact-of-natural-areas-on-peoples-well-being.html#the-health-benefits-of-natural-areas-are-not-sufficiently-taken-into-account-during-planning"><i class="fa fa-check"></i>The health benefits of natural areas are not sufficiently taken into account during planning</a></li>
<li class="chapter" data-level="" data-path="the-impact-of-natural-areas-on-peoples-well-being.html"><a href="the-impact-of-natural-areas-on-peoples-well-being.html#the-buffering-capacity-of-natural-areas-is-weakening"><i class="fa fa-check"></i>The buffering capacity of natural areas is weakening</a></li>
<li class="chapter" data-level="" data-path="the-impact-of-natural-areas-on-peoples-well-being.html"><a href="the-impact-of-natural-areas-on-peoples-well-being.html#education-is-key-to-unlocking-the-potential-of-natural-areas"><i class="fa fa-check"></i>Education is key to unlocking the potential of natural areas</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="shaping-natural-areas-for-public-use.html"><a href="shaping-natural-areas-for-public-use.html"><i class="fa fa-check"></i><b>3.3</b> Shaping natural areas for public use</a><ul>
<li class="chapter" data-level="" data-path="shaping-natural-areas-for-public-use.html"><a href="shaping-natural-areas-for-public-use.html#the-planning-of-natural-areas-is-based-on-the-principle-of-subsidiarity"><i class="fa fa-check"></i>The planning of natural areas is based on the principle of subsidiarity</a></li>
<li class="chapter" data-level="" data-path="shaping-natural-areas-for-public-use.html"><a href="shaping-natural-areas-for-public-use.html#international-development-objectives-and-national-policies-influence-the-status-of-natural-areas"><i class="fa fa-check"></i>International development objectives and national policies influence the status of natural areas</a></li>
<li class="chapter" data-level="" data-path="shaping-natural-areas-for-public-use.html"><a href="shaping-natural-areas-for-public-use.html#natural-areas-have-different-access-options-and-restrictions-on-use"><i class="fa fa-check"></i>Natural areas have different access options and restrictions on use</a></li>
<li class="chapter" data-level="" data-path="shaping-natural-areas-for-public-use.html"><a href="shaping-natural-areas-for-public-use.html#the-green-network-connects-natural-areas-but-its-function-as-a-whole-is-not-guaranteed"><i class="fa fa-check"></i>The green network connects natural areas, but its function as a whole is not guaranteed</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html"><i class="fa fa-check"></i><b>3.4</b> Public participation in decisions on the use of natural areas</a><ul>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#aastate-sündmused-tingisid-nõukogude-eestis-avaliku-keskkonnaarutelu"><i class="fa fa-check"></i>1980. aastate sündmused tingisid Nõukogude Eestis avaliku keskkonnaarutelu</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#the-current-legal-framework-on-public-participation-and-environmental-information-in-estonia-is-sound"><i class="fa fa-check"></i>The current legal framework on public participation and environmental information in Estonia is sound</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#the-public-can-mostly-participate-in-the-management-of-public-space"><i class="fa fa-check"></i>The public can mostly participate in the management of public space</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#despite-the-right-to-participate-estonians-are-passive-and-pessimistic"><i class="fa fa-check"></i>Despite the right to participate, Estonians are passive and pessimistic</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#stakeholders-expect-more-effective-methods-of-participation"><i class="fa fa-check"></i>Stakeholders expect more effective methods of participation</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#access-to-environmental-information-is-a-requirement-for-substantive-public-participation"><i class="fa fa-check"></i>Access to environmental information is a requirement for substantive public participation</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#citizens-that-follow-the-natural-environment-promote-civil-society"><i class="fa fa-check"></i>Citizens that follow the natural environment promote civil society</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estonian-deliberative-space.html"><a href="estonian-deliberative-space.html"><i class="fa fa-check"></i><b>4</b> Estonian deliberative space</a><ul>
<li class="chapter" data-level="" data-path="introduction-4.html"><a href="introduction-4.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#points-of-departure"><i class="fa fa-check"></i>Points of departure</a></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#articles-in-this-chapter"><i class="fa fa-check"></i>Articles in this chapter</a></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#how-do-we-move-forward"><i class="fa fa-check"></i>How do we move forward?</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="4.1" data-path="socio-political-discussion-in-the-digital-public-space.html"><a href="socio-political-discussion-in-the-digital-public-space.html"><i class="fa fa-check"></i><b>4.1</b> Socio-political discussion in the digital public space</a><ul>
<li class="chapter" data-level="" data-path="socio-political-discussion-in-the-digital-public-space.html"><a href="socio-political-discussion-in-the-digital-public-space.html#the-affordances-of-social-media-encourage-emotion-based-communication"><i class="fa fa-check"></i>The affordances of social media encourage emotion-based communication</a></li>
<li class="chapter" data-level="" data-path="socio-political-discussion-in-the-digital-public-space.html"><a href="socio-political-discussion-in-the-digital-public-space.html#internet-use-in-estonia"><i class="fa fa-check"></i>Internet use in Estonia</a></li>
<li class="chapter" data-level="" data-path="socio-political-discussion-in-the-digital-public-space.html"><a href="socio-political-discussion-in-the-digital-public-space.html#closed-meaning-creation-evokes-polarisation"><i class="fa fa-check"></i>Closed meaning creation evokes polarisation</a></li>
<li class="chapter" data-level="" data-path="socio-political-discussion-in-the-digital-public-space.html"><a href="socio-political-discussion-in-the-digital-public-space.html#open-meaning-creation-involves-various-parties"><i class="fa fa-check"></i>Open meaning creation involves various parties</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html"><i class="fa fa-check"></i><b>4.2</b> Estonian youth in the virtual opinion space</a><ul>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#estonian-children-use-the-internet-daily"><i class="fa fa-check"></i>Estonian children use the internet daily</a></li>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#childrens-digital-literacy-is-improving"><i class="fa fa-check"></i>Children’s digital literacy is improving</a></li>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#digital-participation-does-not-appeal-to-estonian-youth"><i class="fa fa-check"></i>Digital participation does not appeal to Estonian youth</a></li>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#types-of-civic-participation-among-estonian-youth"><i class="fa fa-check"></i>Types of civic participation among Estonian youth</a></li>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#factors-hindering-the-digital-participation-of-young-people"><i class="fa fa-check"></i>Factors hindering the digital participation of young people</a></li>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#young-people-perceive-the-weaknesses-of-the-virtual-opinion-space"><i class="fa fa-check"></i>Young people perceive the weaknesses of the virtual opinion space</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li><a href="increasing-regional-polarisation-in-estonia.html#acknowledgements"><em>Acknowledgements</em></a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="the-deliberative-space-shaped-by-the-press.html"><a href="the-deliberative-space-shaped-by-the-press.html"><i class="fa fa-check"></i><b>4.3</b> The deliberative space shaped by the press</a><ul>
<li class="chapter" data-level="" data-path="the-deliberative-space-shaped-by-the-press.html"><a href="the-deliberative-space-shaped-by-the-press.html#media-control-of-the-opinion-space-in-traditional-media-channels"><i class="fa fa-check"></i>Media control of the opinion space in traditional media channels</a></li>
<li class="chapter" data-level="" data-path="the-deliberative-space-shaped-by-the-press.html"><a href="the-deliberative-space-shaped-by-the-press.html#inclusive-architecture-and-the-functioning-of-online-journalism"><i class="fa fa-check"></i>Inclusive architecture and the functioning of online journalism</a></li>
<li class="chapter" data-level="" data-path="the-deliberative-space-shaped-by-the-press.html"><a href="the-deliberative-space-shaped-by-the-press.html#the-contradictory-potential-of-social-media"><i class="fa fa-check"></i>The contradictory potential of social media</a></li>
<li class="chapter" data-level="" data-path="the-deliberative-space-shaped-by-the-press.html"><a href="the-deliberative-space-shaped-by-the-press.html#kokkuvõte"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#viidatud-allikad"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="the-role-and-status-of-experts-in-societal-media-discussions.html"><a href="the-role-and-status-of-experts-in-societal-media-discussions.html"><i class="fa fa-check"></i><b>4.4</b> The role and status of experts in societal media discussions</a><ul>
<li class="chapter" data-level="" data-path="the-role-and-status-of-experts-in-societal-media-discussions.html"><a href="the-role-and-status-of-experts-in-societal-media-discussions.html#the-role-of-scientists-in-societal-debates"><i class="fa fa-check"></i>The role of scientists in societal debates</a></li>
<li class="chapter" data-level="" data-path="the-role-and-status-of-experts-in-societal-media-discussions.html"><a href="the-role-and-status-of-experts-in-societal-media-discussions.html#a-plan-for-a-wood-processing-plant-encouraged-academics-to-lead-the-public-debate"><i class="fa fa-check"></i>A plan for a wood processing plant encouraged academics to lead the public debate</a></li>
<li class="chapter" data-level="" data-path="the-role-and-status-of-experts-in-societal-media-discussions.html"><a href="the-role-and-status-of-experts-in-societal-media-discussions.html#public-debate-on-forestry-did-not-bring-experts-any-closer-together"><i class="fa fa-check"></i>Public debate on forestry did not bring experts any closer together</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#summary"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="estonian-living-environment-in-2050.html"><a href="estonian-living-environment-in-2050.html"><i class="fa fa-check"></i><b>5</b> Estonian living environment in 2050</a><ul>
<li class="chapter" data-level="" data-path="introduction-5.html"><a href="introduction-5.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction-5.html"><a href="introduction-5.html#what-is-scenario-planning"><i class="fa fa-check"></i>What is scenario planning?</a></li>
<li class="chapter" data-level="" data-path="introduction-5.html"><a href="introduction-5.html#main-trends"><i class="fa fa-check"></i>Main trends</a></li>
<li><a href="introduction-5.html#acknowledgements50"><em>Acknowledgements</em></a></li>
<li class="chapter" data-level="" data-path="introduction-5.html"><a href="introduction-5.html#forecasts-and-scenarios-used"><i class="fa fa-check"></i>Forecasts and scenarios used</a></li>
<li class="chapter" data-level="" data-path="introduction-0.html"><a href="introduction-0.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="estonia-2050-scenarios.html"><a href="estonia-2050-scenarios.html"><i class="fa fa-check"></i>Estonia 2050 scenarios</a></li>
<li class="chapter" data-level="" data-path="estonia-voluntarily-forced-into-cities.html"><a href="estonia-voluntarily-forced-into-cities.html"><i class="fa fa-check"></i>Estonia voluntarily forced into cities</a></li>
<li class="chapter" data-level="" data-path="one-hour-estonia.html"><a href="one-hour-estonia.html"><i class="fa fa-check"></i>One-hour Estonia</a></li>
<li class="chapter" data-level="" data-path="estonia-of-rogues-and-rascals.html"><a href="estonia-of-rogues-and-rascals.html"><i class="fa fa-check"></i>Estonia of rogues and rascals</a></li>
<li class="chapter" data-level="" data-path="self-sufficient-estonia.html"><a href="self-sufficient-estonia.html"><i class="fa fa-check"></i>Self-sufficient Estonia</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contributors-and-editors.html"><a href="contributors-and-editors.html"><i class="fa fa-check"></i><b>6</b> Contributors and Editors</a><ul>
<li class="chapter" data-level="" data-path="contributors-and-editors.html"><a href="contributors-and-editors.html#editor-in-chief"><i class="fa fa-check"></i>Editor-in-chief</a></li>
<li class="chapter" data-level="" data-path="contributors-and-editors.html"><a href="contributors-and-editors.html#editors"><i class="fa fa-check"></i>Editors</a></li>
<li class="chapter" data-level="" data-path="contributors-and-editors.html"><a href="contributors-and-editors.html#contributors"><i class="fa fa-check"></i>Contributors</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="info.html"><a href="info.html"><i class="fa fa-check"></i><b>7</b> Info</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estonian Human Development Report 2019/2020</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-0" class="section level2 unnumbered chapter_section chapter0_section intro_section">
<h2>Introduction</h2>
<h1>
SPATIAL DEVELOPMENT IN ESTONIA
</h1>
<div class="authors">
<div class="author-links">
<p><strong><a href="contributors-and-editors.html#helen-sooväli-sepping">Helen Sooväli-Sepping</a> ja <a href="contributors-and-editors.html#antti-roose">Antti Roose</a></strong></p>
</div>
<div>
<p><a class="print-btn" href="../print/EIA-2019-0-Sissejuhatus.pdf"><i class="fa fa-file" aria-hidden="true"></i>Trükiversioon</a></p>
</div>
</div>
<div id="põhisõnumid" class="section level3 unnumbered chapter0_section">
<h3>Põhisõnumid</h3>
<div class="points">
<ul>
<li>
Estonia has advanced to 30th position in the world in terms of human development, but has since stalled.
</li>
</ul>
<p>
The well-being of the Estonian population has improved remarkably compared to other countries in the world. Domestically, social inequality between regions is deepening.
</p>
<ul>
<li>
Estonia’s metropolisation is reflected in the continued growth of the Greater Tallinn urban area, where people, economic activity and services are concentrating, while the rest of Estonia is shrinking.
</li>
</ul>
<p>
For Estonia as a whole, metropolisation creates an imbalance in terms of statehood, governance, the economy, and the quality of life, space and the environment. It is time to require urban policy-making, time to create a national framework and targeted measures based on actual urban areas, rather than administrative city boundaries.
</p>
<ul>
<li>
The multilocality of Estonians connects Tallinn with the counties, and the cities with rural areas.
</li>
</ul>
<p>
People’s expanding daily activity spaces and the recent administrative reform have led to a dilution of spatial identity. A lifestyle and infrastructure based on car use allows people to operate simultaneously in the city and the countryside. Multilocality, or living in more than one place, due to labour migration, country homes, networks of families and friends, study and leisure requires more flexible spatial planning and administrative arrangements.
</p>
<ul>
<li>
Public debate results in a better living environment and greater consensus.
</li>
</ul>
<p>
The development of deliberative skills is in the national interest. More effective, transparent and feedback-based modes of public participation are needed to promote participatory democracy. Digital platforms, a media space based on analytical argumentation, a competent civil service and reliable experts all contribute to this, ensuring the exchange of knowledge and building mutual trust between the state and its citizens.
</p>
<ul>
<li>
Built heritage and natural areas as part of Estonian culture strengthen people’s relationship with the environment and their sense of belonging.
</li>
</ul>
<p>
A diverse living environment requires the protection of built heritage based on the principles of sustainable development, combined with an investment plan that ensures the preservation, utilisation and management of buildings of national importance. Estonians’ environmental awareness is undergoing rapid and sharp changes, which explains the social confrontations over the use of natural areas in recent years. More targeted planning of natural areas and better management of visits to nature helps to improve the health of urban populations and maintain their contact with nature.
</p>
</div>
<p>In his speech on the 78th anniversary of the Republic of Estonia on 24 February 1996, President Lennart Meri declared:</p>
<p><em>‘Where do Estonia’s strengths lie? Estonia’s strength is [that it] is exactly where it is; that it is precisely the size it is.’</em></p>
<p>The total land area of Estonia is exactly 43,465 sq. km (Land Board 2020). The Estonian territory – the land, geographical places, their use and usefulness, the cities, towns and villages as well as its natural environment – is a national asset. It is here, in this ‘space’, to use academic parlance, that Estonia exists and develops. The Estonian Human Development Report 2019/2020 focuses on the spatial development of Estonia in terms of social processes and processes affecting the well-being of the Estonian people. The fundamental question of this report is how to recreate and enhance spatial diversity, quality and balance in Estonia in a way that is democratic and serves the interests of society as a whole.</p>
<p>In the five chapters that follow, we approach the concept of space as broadly as possible – on different scales and in the different senses of the term. We extend the concept geographically to cover the whole of Estonia, looking at the settlement structure, natural areas, urban space, including urban design, and the deliberative space that connects us. We also describe the health of Estonian democracy as it undergoes spatial change, from the perspective of sustainable development and social cohesion, emphasising the importance of the co-creation of habitable space that is human-friendly and on a human scale. Therefore, space as the umbrella term for this report refers to the common space that serves the public interest and provides public goods.</p>
<p>Several articles in the report raise the issue of democratic spatial relations in the public sphere, where the public interest clashes with individual and private interests. How public is public space? This question has arisen sharply in Estonian society in recent years, in connection with the planning of urban space as well as industrial facilities, apartment buildings, roads and other structures, and also in connection with deforestation and the opportunities for spending time in nature. Indeed, we can understand public space by contrasting it with private (or privatised) space. Although 40% of Estonia’s land is state-owned and 1% is owned by local governments, public access to this space is limited, for example, in the case of national defence lands. The public interest may also concern the 59% of the Estonian territory that is private property.</p>
<div class="blockquote-right">
<p>
Space itself affects people’s lives and behaviour, and shapes the way we think at both the collective and individual level.
</p>
</div>
<p>Space plays an important role in shaping social processes. The use and design of public space, including privately owned public space, reflects how society is organised. The more open and democratic the society, the better the opportunities for participation in shaping space and the more transparent the spatial decisions. Space itself affects people’s lives and behaviour, and shapes the way we think at both the collective and individual level. Moreover, the nature of public space has changed substantially in recent decades. As well as historical and textual narratives, the cultural space is made up of physical space as a medium for national self-description. Therefore, the digital deliberative space can serve as an extension of the town square or village green. Public digital and physical space are closely intertwined, creating the effect of time-space compression – digitally, we can be in several spaces at the same time.</p>
</div>
<div id="estonia-has-advanced-to-30th-position-in-the-world-in-terms-of-human-development-but-has-since-stalled" class="section level3 unnumbered chapter0_section">
<h3>Estonia has advanced to 30th position in the world in terms of human development, but has since stalled</h3>
<p>According to the Human Development Index introduced by the United Nations Development Programme in 1990, Estonia qualifies among countries with very high human development. Estonia ranks 30th with an index of 0.882 and has remained in that position for the past six years (<a href="introduction-0.html#table01">Table 0.1</a>). The index takes into account life expectancy, mean years of schooling and GNI per capita at constant prices. Estonian residents have an average life expectancy of 78.6 years, which is 3 years less than the European Union average. Life expectancy depends on several factors: the environment, access to healthcare, people’s standard of living and health awareness. In Estonia, life expectancy is higher in urban areas, among ethnic Estonians and the more highly educated population (<a href="#StatisticsEstonia2018">Statistics Estonia 2018</a>). Education continues to be highly valued and respected. Globally, students receive more years of schooling only in Switzerland, the United States and Canada.</p>
<p>The improvement in well-being has been significant and inspired the slogan ‘Estonia has never done as well as it is doing today’. More important than measurement and indexing systems, however, are data quality and the depth with which the data is studied.
A chain is only as strong as its weakest link; in other words, the population is as prosperous as the most financially vulnerable social groups. According to Statistics Estonia, 284,300 (21.7%) Estonians lived at risk of poverty and 31,400 (2.4%) in absolute poverty in 2019. About half of the elderly population experience risk of poverty. While the share of the population at risk of poverty has decreased slowly but steadily in recent years, the difference between the richest and poorest fifth of the population has not changed since 2017. Not all social groups, let alone all regions, have benefited from the increase in well-being. Differences in average life expectancy, educational levels and income are regional and also related to the state of the environment (<a href="#NationalHealthPlan2030">see e.g. National Health Plan 2020–2030</a>).</p>
<p>In the first decades of this century, the world has seen a rapid rise in the standards of living due to the successful fight against disease, hunger and poverty. But today the world faces a new wave of inequality, and inequality as the biggest obstacle to human well-being is also at the heart of the global Human Development Report published in late 2019. The report is framed by a forward-looking message that two new global trends have emerged over the past decade which are affecting people’s well-being around the world: access to technology and climate change. The success stories in technology, such as artificial intelligence and machine learning, are widening the gap with populations and countries that do not have the capacity to keep up with technological development. The climate crisis is already hitting the world’s poorest regions and vulnerable groups harder. Climate change is expected to cause 250,000 additional deaths a year from malnutrition, malaria, diarrhoea and heat stress between 2030 and 2050 (<a href="introduction-0.html#UnitedNations2019">United Nations 2019</a>).</p>
<p class="caption" id="table01">
<span class="figure-number">Table 0.1</span> Human Development Index and its components in selected countries (2018)
</p>
<div style="overflow-x:auto;">
<table class="table table-bordered table-hover table-condensed" id="table_01">
<thead>
<tr>
<th title="Field #1"" align="left !important">HDI rank</th>
<th title="Field #2" class="table_01_country">
Country
</th>
<th title="Field #3">
Human Development Index value
</th>
<th title="Field #4">
Life expectancy at birth (y)
</th>
<th title="Field #5">
Expected years of schooling
</th>
<th title="Field #6">
Mean years of schooling
</th>
<th title="Field #7">
Gross national income per capita (2011 PPP $)
</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left" class="table_01_nr">
1
</td>
<td class="table_01_country">
Norway
</td>
<td>
0,954
</td>
<td>
82,3
</td>
<td>
18,1
</td>
<td>
12,6
</td>
<td>
68 059
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
2
</td>
<td class="table_01_country">
Switzerland
</td>
<td>
0,946
</td>
<td>
83,6
</td>
<td>
16,2
</td>
<td>
13,4
</td>
<td>
59 375
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
3
</td>
<td class="table_01_country">
Ireland
</td>
<td>
0,942
</td>
<td>
82,1
</td>
<td>
18,8
</td>
<td>
12,5
</td>
<td>
55 660
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
4
</td>
<td class="table_01_country">
Germany
</td>
<td>
0,939
</td>
<td>
81,2
</td>
<td>
17,1
</td>
<td>
14,1
</td>
<td>
46 946
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
4
</td>
<td class="table_01_country">
Hong Kong, China (SAR)
</td>
<td>
0,939
</td>
<td>
84,7
</td>
<td>
16,5
</td>
<td>
12
</td>
<td>
60 221
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
6
</td>
<td class="table_01_country">
Australia
</td>
<td>
0,938
</td>
<td>
83,3
</td>
<td>
22,1
</td>
<td>
12,7
</td>
<td>
44 097
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
6
</td>
<td class="table_01_country">
Iceland
</td>
<td>
0,938
</td>
<td>
82,9
</td>
<td>
19,2
</td>
<td>
12,5
</td>
<td>
47 566
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
8
</td>
<td class="table_01_country">
Sweden
</td>
<td>
0,937
</td>
<td>
82,7
</td>
<td>
18,8
</td>
<td>
12,4
</td>
<td>
47 955
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
9
</td>
<td class="table_01_country">
Singapore
</td>
<td>
0,935
</td>
<td>
83,5
</td>
<td>
16,3
</td>
<td>
11,5
</td>
<td>
83 793
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
10
</td>
<td class="table_01_country">
Netherlands
</td>
<td>
0,933
</td>
<td>
82,1
</td>
<td>
18
</td>
<td>
12,2
</td>
<td>
50 013
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
11
</td>
<td class="table_01_country">
Denmark
</td>
<td>
0,93
</td>
<td>
80,8
</td>
<td>
19,1
</td>
<td>
12,6
</td>
<td>
48 836
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
12
</td>
<td class="table_01_country">
Finland
</td>
<td>
0,925
</td>
<td>
81,7
</td>
<td>
19,3
</td>
<td>
12,4
</td>
<td>
41 779
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
13
</td>
<td class="table_01_country">
Canada
</td>
<td>
0,922
</td>
<td>
82,3
</td>
<td>
16,1
</td>
<td>
13,3
</td>
<td>
43 602
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
14
</td>
<td class="table_01_country">
New Zealand
</td>
<td>
0,921
</td>
<td>
82,1
</td>
<td>
18,8
</td>
<td>
12,7
</td>
<td>
35 108
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
15
</td>
<td class="table_01_country">
United Kingdom
</td>
<td>
0,92
</td>
<td>
81,2
</td>
<td>
17,4
</td>
<td>
13
</td>
<td>
39 507
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
15
</td>
<td class="table_01_country">
United States
</td>
<td>
0,92
</td>
<td>
78,9
</td>
<td>
16,3
</td>
<td>
13,4
</td>
<td>
56 140
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
17
</td>
<td class="table_01_country">
Belgium
</td>
<td>
0,919
</td>
<td>
81,5
</td>
<td>
19,7
</td>
<td>
11,8
</td>
<td>
43 821
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
18
</td>
<td class="table_01_country">
Lichtenstein
</td>
<td>
0,917
</td>
<td>
80,5
</td>
<td>
14,7
</td>
<td>
12,5
</td>
<td>
99 732
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
19
</td>
<td class="table_01_country">
Japan
</td>
<td>
0,915
</td>
<td>
84,5
</td>
<td>
15,2
</td>
<td>
12,8
</td>
<td>
40 799
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
20
</td>
<td class="table_01_country">
Austria
</td>
<td>
0,914
</td>
<td>
81,4
</td>
<td>
16,3
</td>
<td>
12,6
</td>
<td>
46 231
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
21
</td>
<td class="table_01_country">
Luxembourg
</td>
<td>
0,909
</td>
<td>
82,1
</td>
<td>
14,2
</td>
<td>
12,2
</td>
<td>
65 543
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
22
</td>
<td class="table_01_country">
Isreal
</td>
<td>
0,906
</td>
<td>
82,8
</td>
<td>
16
</td>
<td>
13
</td>
<td>
33 650
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
22
</td>
<td class="table_01_country">
Korea (Republic of)
</td>
<td>
0,906
</td>
<td>
82,8
</td>
<td>
16,4
</td>
<td>
12,2
</td>
<td>
36 757
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
24
</td>
<td class="table_01_country">
Slovenia
</td>
<td>
0,902
</td>
<td>
81,2
</td>
<td>
17,4
</td>
<td>
12,3
</td>
<td>
32 143
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
25
</td>
<td class="table_01_country">
Spain
</td>
<td>
0,893
</td>
<td>
83,4
</td>
<td>
17,9
</td>
<td>
9,8
</td>
<td>
35 041
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
26
</td>
<td class="table_01_country">
Czechia
</td>
<td>
0,891
</td>
<td>
79,2
</td>
<td>
16,8
</td>
<td>
12,7
</td>
<td>
31 597
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
26
</td>
<td class="table_01_country">
France
</td>
<td>
0,891
</td>
<td>
82,5
</td>
<td>
15,5
</td>
<td>
11,4
</td>
<td>
40 511
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
28
</td>
<td class="table_01_country">
Malta
</td>
<td>
0,885
</td>
<td>
82,4
</td>
<td>
15,9
</td>
<td>
11,3
</td>
<td>
34 795
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
29
</td>
<td class="table_01_country">
Italy
</td>
<td>
0,883
</td>
<td>
83,4
</td>
<td>
16,2
</td>
<td>
10,2
</td>
<td>
36 141
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
30
</td>
<td class="table_01_est table_01_country">
Estonia
</td>
<td class="table_01_est">
0,882
</td>
<td class="table_01_est">
78,6
</td>
<td class="table_01_est">
16,1
</td>
<td class="table_01_est">
13
</td>
<td class="table_01_est">
30 379
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
34
</td>
<td class="table_01_country">
Lithuania
</td>
<td>
0,869
</td>
<td>
75,7
</td>
<td>
16,5
</td>
<td>
13
</td>
<td>
29 775
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
39
</td>
<td class="table_01_country">
Latvia
</td>
<td>
0,854
</td>
<td>
75,2
</td>
<td>
16
</td>
<td>
12,8
</td>
<td>
26 301
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
49
</td>
<td class="table_01_country">
Russiaan Federation
</td>
<td>
0,824
</td>
<td>
72,4
</td>
<td>
15,5
</td>
<td>
12
</td>
<td>
25 036
</td>
</tr>
</tbody>
</table>
</div>
<div class="imgsource">
<p>
<span class="imgsource-source">Source:</span> United Nations 2019.
</p>
</div>
</div>
<div id="estonias-metropolisation-is-reflected-in-the-continued-growth-of-the-greater-tallinn-urban-area-where-people-economic-activity-and-services-are-concentrating-while-the-rest-of-estonia-is-shrinking-and-degenerating" class="section level3 unnumbered chapter0_section">
<h3>Estonia’s metropolisation is reflected in the continued growth of the Greater Tallinn urban area, where people, economic activity and services are concentrating, while the rest of Estonia is shrinking and degenerating</h3>
<p>The map of Estonia is simple. Tallinn is the big city, Tartu is the university town and Pärnu is the summer capital; there is the late-industrial northeastern Estonia, southern Estonia, which is increasingly a region for recreation, agriculture and forestry, and the marine islands. To simplify even further, we can divide the country into two – there is Tallinn and the rest of Estonia: the nine-to-five county towns and the periphery that increasingly resembles a national park. Rather than mere labels, this is the actual spatial structure and administrative division of Estonia (<a href="introduction-0.html#figure01">Figure 0.1</a>). In terms of spatial development, the ‘two Estonias’ referred to by social scientists in 2000 have now become a reality (see <a href="introduction-0.html#Lauristin2001">Lauristin 2001</a>; <a href="introduction-0.html#Vetik2002">Vetik 2002</a>).</p>
<p>The scientific community is increasingly discussing planetary urbanisation, explaining and specifying the growing impact of urbanisation processes on globalisation, the blurring of centres and urban areas, and the destructive pressures on nature (<a href="introduction-0.html#Schmidt2018">Schmidt 2018</a>). The urbanisation process intertwines market economy activities that connect to a global network and intensifies land use. Rural areas are transformed into agro-industrial complexes; nature is commodified for tourism and other purposes; industrial parks are built along with logistics and transport infrastructure.</p>
<p class="caption" id="figure01">
<span class="figure-number">Figure 0.1</span> Estonian urban system (2,000 or more residents as of 2019)
</p>
<pre><code>## Warning: package &#39;sf&#39; was built under R version 4.0.2</code></pre>
<pre><code>## Warning: package &#39;raster&#39; was built under R version 4.0.2</code></pre>
<pre><code>## Warning: package &#39;sp&#39; was built under R version 4.0.2</code></pre>
<pre><code>## Warning: package &#39;tmap&#39; was built under R version 4.0.2</code></pre>
<pre><code>## Warning: package &#39;svglite&#39; was built under R version 4.0.2</code></pre>
<pre><code>## Reading layer `maakond_20200101&#39; from data source `/Users/taavet/Documents/GitHub/EIA_2019/data/0_fig1_data/maakond_20200101.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 15 features and 2 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 369032.1 ymin: 6377141 xmax: 739152.8 ymax: 6634019
## projected CRS:  Estonian Coordinate System of 1997</code></pre>
<pre><code>##                MNIMI MKOOD                       geometry
## 1   Viljandi maakond  0084 MULTIPOLYGON (((621049.2 64...
## 2       Hiiu maakond  0039 MULTIPOLYGON (((418045.8 65...
## 3      Harju maakond  0037 MULTIPOLYGON (((505059.9 65...
## 4      Lääne maakond  0056 MULTIPOLYGON (((460628.3 65...
## 5      Rapla maakond  0071 MULTIPOLYGON (((504136.5 65...
## 6 Lääne-Viru maakond  0060 MULTIPOLYGON (((657694.1 65...</code></pre>
<pre><code>## Reading layer `asustusyksus_20200301&#39; from data source `/Users/taavet/Documents/GitHub/EIA_2019/data/0_fig1_data/asustusyksus_20200301.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 4713 features and 7 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 369032.1 ymin: 6377141 xmax: 739152.8 ymax: 6634019
## projected CRS:  Estonian Coordinate System of 1997</code></pre>
<pre><code>##                            ANIMI AKOOD TYYP          ONIMI OKOOD         MNIMI
## 1 Väikeheinamaa küla / Lillängin  9619    8    Viimsi vald  0890 Harju maakond
## 2                 Saviranna küla  7498    8 Jõelähtme vald  0245 Harju maakond
## 3             Kristiine linnaosa  0339    6        Tallinn  0784 Harju maakond
## 4              Mustamäe linnaosa  0482    6        Tallinn  0784 Harju maakond
## 5                      Salu küla  7392    8       Rae vald  0653 Harju maakond
## 6                    Patika küla  6036    8       Rae vald  0653 Harju maakond
##   MKOOD                       geometry
## 1  0037 MULTIPOLYGON (((527958.2 66...
## 2  0037 MULTIPOLYGON (((558032.7 65...
## 3  0037 MULTIPOLYGON (((538249.5 65...
## 4  0037 MULTIPOLYGON (((536316.3 65...
## 5  0037 MULTIPOLYGON (((559679.9 65...
## 6  0037 MULTIPOLYGON (((552250.8 65...</code></pre>
<pre><code>## Reading layer `omavalitsus_20200301&#39; from data source `/Users/taavet/Documents/GitHub/EIA_2019/data/0_fig1_data/omavalitsus_20200301.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 79 features and 5 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 369032.1 ymin: 6377141 xmax: 739152.8 ymax: 6634019
## projected CRS:  Estonian Coordinate System of 1997</code></pre>
<pre><code>##           ONIMI OKOOD         MNIMI MKOOD TYYP                       geometry
## 1    Ruhnu vald  0689 Saare maakond  0074    1 MULTIPOLYGON (((456706.5 64...
## 2     Muhu vald  0478 Saare maakond  0074    1 MULTIPOLYGON (((463418.4 64...
## 3   Viimsi vald  0890 Harju maakond  0037    1 MULTIPOLYGON (((545381.9 65...
## 4 Saaremaa vald  0714 Saare maakond  0074    1 MULTIPOLYGON (((383834.7 64...
## 5  Hiiumaa vald  0205  Hiiu maakond  0039    1 MULTIPOLYGON (((418045.8 65...
## 6    Kihnu vald  0303 Pärnu maakond  0068    1 MULTIPOLYGON (((499610.8 64...</code></pre>
<pre><code>## $tm_layout
## $tm_layout$frame
## [1] FALSE
## 
## $tm_layout$asp
## [1] 1.777778
## 
## $tm_layout$outer.margins
## [1] 0
## 
## $tm_layout$inner.margins
## [1] 0.02 0.10 0.02 0.02
## 
## $tm_layout$legend.outside
## [1] FALSE
## 
## $tm_layout$legend.width
## [1] 0.25
## 
## $tm_layout$legend.height
## [1] 0.7
## 
## $tm_layout$legend.title.size
## [1] 1
## 
## $tm_layout$legend.text.size
## [1] 1
## 
## $tm_layout$legend.format
## $tm_layout$legend.format$text.separator
## [1] &quot;kuni&quot;
## 
## 
## $tm_layout$style
## [1] NA
## 
## 
## attr(,&quot;class&quot;)
## [1] &quot;tm&quot;</code></pre>
<p><img src="../figures/0-intro/fig01_eng.jpg" width="100%" style="display: block; margin: auto;" /></p>
<div class="imgsource">
<div>
<p><span class="imgsource-source">Source:</span> Statistics Estonia.</p>
</div>
<div>
<p><a class="data-btn" href="data/0_fig1_data.zip"><i class="fa fa-download" aria-hidden="true"></i>Laadi andmed</a></p>
</div>
</div>
<div class="blockquote-right">
<p>
Linnastumisprotsess põimib kokku turumajanduslikud globaalvõrgustikku ühendatud tegevused ning intensiivistab maakasutust.
</p>
</div>
<p>LThe significance and impact of a city can no longer be measured in terms of its urban form, density and other spatial features alone. Today’s cities are defined by a socio-spatial force that transcends administrative boundaries (<a href="introduction-0.html#Brenner2019">Brenner 2019</a>). The Estonian city no longer follows the traditional idea of a high-density industrial settlement with a clearly defined urban centre. The current 47 cities with administrative boundaries in Estonia only notionally form an urban system, as most of them lack sufficient size and the functions of a 21st-century town. In Estonia, urbanisation occurs as the expansion of urban areas and the growth of the urban population in and around Tallinn. Urban-regional economic theory explains the current metropolisation process in terms of a deepening imbalance and concentration of growth (<a href="introduction-0.html#Nijkamp2013">Nijkamp and Kourtit 2013</a>). Estonia is a textbook example of these theoretical economic models. Urbanisation, and metropolisation in particular, has significant negative externalities, primarily in terms of the use of urban space and the environment, but also social impacts, such as wealth disparities in society. In the 2000s, urbanisation in Estonia was characterised by the rapid Europeanisation of the legal, administrative and socio-economic spheres (<a href="introduction-0.html#Raagmaa2014">Raagmaa et al. 2014</a>) (<a href="introduction-0.html#table02">Table 0.2</a>). In a new wave of economic growth in the 2010s, European metropolises merged into megaregions (London and Manchester; Paris, Brussels, Amsterdam and the German conurbations; Rome, Milan and Turin). In this context, Tallinn is by no means a large city, ranking only 59th in the European Union in terms of population size.</p>
<p class="caption" id="table02">
<span class="figure-number">Table 0.2</span> Key developments in European and Estonian urban policy
</p>
<div style="overflow-x:auto;">
<table class="table table-bordered table-hover table-condensed" id="table_02">
<thead>
<tr>
<th title="Field #1">
Decade
</th>
<th title="Field #2">
European development
</th>
<th title="Field #3">
Key processes in Europe
</th>
<th title="Field #4">
Key urban policy areas in ‘old’ Europe
</th>
<th title="Field #5">
Key urban policy areas in Estonia
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="table_02_red">
1990
</td>
<td>
Integration of the single market and trans-European infrastructures, including the transport network
</td>
<td>
Demokratiseerimine ja riigireformid Kesk- ja Ida-Euroopas.
</td>
<td>
Kultuur ja turism. Konkurentsipoliitika.
</td>
<td>
Üleminekureformid, sh maa- ja omandireform ning linnahaldus. Erastamine ja kinnisvaraturu teke.
</td>
</tr>
<tr>
<td class="table_02_red">
2000
</td>
<td>
Euroopa Liidu itta laienemine. Terrorism.
</td>
<td>
Majandusbuum ja finantskriis.
</td>
<td>
Suurlinnastud. Elukvaliteet.
</td>
<td>
Linnaplaneerimine. Kinnisvarabuum, sh eeslinnastumislaine, uued keskused ja linnataristud ning ärilinnak.
</td>
</tr>
<tr>
<td class="table_02_red">
2010
</td>
<td>
Hiigelregioonid suurlinnastute võrgustikuna.
</td>
<td>
Majanduse taastumine. Kokkuhoiupoliitika.
</td>
<td>
Nutikas spetsialiseerumine. Tehnoloogiline areng ja innovatsioon.
</td>
<td>
Suurarendused ja suurtaristud. Keskklassistumine. Avaliku ruumi teema esilekerkimine. Kaasav linn ja kodanikuaktivismi teke.
</td>
</tr>
<td class="table_02_red">
2020 ja tulevik
</td>
<td>
Deglobaliseerumine. Euroopa geopoliitilise positsiooni hoidmine maailmas. Kliimaneutraalsus.
</td>
<td>
Majanduskriis. Brexit. Roheline lepe. Digitaalsus. Populism. Euroopa kultuuri kaitse.
</td>
<td>
Säästlik, tark hooliv linn. „Uus” demokraatia.
</td>
<td>
Rail Baltica. Talsinki. Kestlik kahanemine. Sotsiaalsüsteemid.
</td>
</tr>
</tbody>
</table>
</div>
<div class="imgsource">
<p>
<span class="imgsource-source">Source:</span> Clark et al. 2018; Mäntysalo et al. 2019; Raagmaa et al. 2014.
</p>
</div>
<p>Estonian urban development as a whole is based on the expansion of urban land, that is, on land take. Between 2000 and 2017, settlement area increased by 138 sq. km (<a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural">Oja, Ch. 1</a>). New urban land equal to nine times the area of the town of Viljandi has been generated in Estonia during those years through changing land use, although no new cities have been added on the map. This urban growth is characterised by fragmentation and diffusion. Architecture historian and member of the Estonian Academy of Sciences Mart Kalm (<a href="introduction-0.html#Kalm2018">2018</a>) has characterised the Estonian built space as follows::</p>
<p><em>‘Compared to the rest of Europe, it is embarrassing how little attention we pay to sustainability today. […] Poverty and changing circumstances have rarely allowed integrated environments to emerge, which is why fragmented environments are more characteristic of modern Estonia.’</em></p>
<div class="blockquote-left">
<p>
The metropolisation during the first two decades of this century has already shaped Estonian history.
</p>
</div>
<p>At present, 920,000 people or 69% of the Estonian population live in an urban environment; about 550,000 of them, or 40% of the population, live in the Greater Tallinn area (<a href="#the-triumph-of-planning-freedom-in-suburban-Estonia">Roose, Ch. 1</a>). The metropolisation during the first two decades of this century has already shaped Estonian history. Nevertheless, the impact is not yet comparable with that of the mass housing construction and immigration of the 1970s and 1980s. The growth of Greater Tallinn in the 2010s has meant extensive new property and traffic infrastructure development, residential segregation (<a href="introduction-0.html#Tammaru2020">Tammaru et al. 2020</a>), fragmented expansion of new settlements (<a href="#the-triumph-of-planning-freedom-in-suburban-Estonia">Roose, Ch. 1</a>)and declining public urban space (<a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#public-space-as-an-interconnecting-network-within-the-living-environment">Paaver and Kiivet, Ch. 2</a>) on an unprecedented scale. With rapid motorisation, more and more urban territory is occupied by roads and parking spaces (<a href="estonian-living-environment-in-2050.html#estonian-living-environment-in-2050">Grišakov, Ch. 5</a>). Infrastructure investments are also funnelled into road construction, with less invested in pedestrian and bicycle paths, town squares and parks. The lack of physical activity associated with increased car use (<a href="#accessibility-changes-in-motorised-Estonia">Tuvikene et al., Ch. 1</a>) may in turn affect people’s physical and mental health, which have been deteriorating in Estonia in recent decades due to obesity and mental disorders (<a href="#Statistikaamet2018">Sustainable Development Indicators 2018</a>). Paved surfaces and built-up areas are expanding, sacrificing urban greenery, which has become increasingly important in the deepening climate crisis as a source of biodiversity and as a carbon sink to help clean and buffer the environmental impacts of the urban environment and human activity (<a href="#Shaping-natural-areas-for-public-use">Poom and Sepp, Ch. 3</a>; <a href="introduction-0.html#Hansis2015">Hansis et al. 2015</a>; <a href="introduction-0.html#EEA2019">EEA 2019a</a>). In the context of rapid urban growth, public and private interests often collide (e.g. in the property development in Viimsi municipality outside Tallinn and the densification of the Kalamaja district in Tallinn; see <a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#public-space-as-an-interconnecting-network-within-the-living-environment">Paaver and Kiivet, Ch. 2</a>; <a href="urban-activism-in-the-co-creation-of-public-space.html#urban-activism-in-the-co-creation-of-public-space">Kljavin et al., Ch. 2</a>; <a href="socio-political-discussion-in-the-digital-public-space.html#socio-political-discussion-in-the-digital-public-space">Ventsel and Madisson, Ch. 4</a>).</p>
<p>Tallinn’s potential for development lies in it becoming a twin city with Helsinki. Talsinki could combine Helsinki’s global image for the knowledge economy and quality of life with Tallinn’s innovation and growth momentum to emerge as a city of the future which fosters the knowledge economy and innovation. This would mean the creation of a global city with over a million residents (<a href="estonian-living-environment-in-2050.html#estonian-living-environment-in-2050">Grišakov, Ch. 5</a>).</p>
</div>
<div id="the-multilocality-enjoyed-by-people-living-in-estonian-connects-tallinn-with-the-counties-and-the-cities-with-the-villages" class="section level3 unnumbered chapter0_section">
<h3>The multilocality enjoyed by people living in Estonian connects Tallinn with the counties, and the cities with the villages</h3>
<p>All counties except Harjumaa are shrinking. Between 2000 and 2018, the population of Harjumaa county increased by 10%, while Tartumaa county lost 4% of its population and the other counties 10–25%. Shrinkage is the reverse of metropolisation. As an example, consider the population pyramids of a new suburban neighbourhood on the outskirts of Tallinn and a rural small town (<a href="introduction-0.html#figure02">Figure 0.2</a>). Young families with children live in the Tallinn suburb, while the population of the rural town is predominantly aged 50+. A region is shrinking when it experiences a significant population decline within a single generation. The gap between Tallinn and the counties is growing spatially, economically, socially, culturally and in terms of living conditions (<a href="modern-living-conditions-whose-privilege.html#modern-living-conditions-whose-privilege">Kährik and Väiko, Ch. 1</a>; <a href="increasing-regional-polarisation-in-estonia.html#increasing-regional-polarisation-in-estonia">Plüschke-Altof et al., Ch. 1</a>). At the heart of this development is a bundle of questions that have been waiting to be answered throughout the past decade: Do shrinking county towns have the strength to get the counties up and running? Is the business environment vibrant and diverse enough? Is the available workforce and catchment area sufficient for economic development?</p>
<p class="caption" id="figure02">
<span class="figure-number">Figure 0.2.</span> The population pyramids of a Tallinn suburban neighbourhood and a small town
</p>
<div class="desktop-plot">
<pre><code>## Warning: package &#39;scales&#39; was built under R version 4.0.2</code></pre>
<pre><code>## Warning: package &#39;showtext&#39; was built under R version 4.0.2</code></pre>
<pre><code>## Warning: package &#39;sysfonts&#39; was built under R version 4.0.2</code></pre>
<pre><code>## Warning: package &#39;showtextdb&#39; was built under R version 4.0.2</code></pre>
<pre><code>## Warning: package &#39;plotly&#39; was built under R version 4.0.2</code></pre>
<pre><code>## Warning: `group_by_()` is deprecated as of dplyr 0.7.0.
## Please use `group_by()` instead.
## See vignette(&#39;programming&#39;) for more help
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_warnings()` to see where this warning was generated.</code></pre>
<pre><code>## Warning in config(., displayModeBar = F, collaborate = F): The collaborate
## button is no longer supported</code></pre>
<pre><code>## Warning: &#39;config&#39; objects don&#39;t have these attributes: &#39;collaborate&#39;
## Valid attributes include:
## &#39;staticPlot&#39;, &#39;plotlyServerURL&#39;, &#39;editable&#39;, &#39;edits&#39;, &#39;autosizable&#39;, &#39;responsive&#39;, &#39;fillFrame&#39;, &#39;frameMargins&#39;, &#39;scrollZoom&#39;, &#39;doubleClick&#39;, &#39;doubleClickDelay&#39;, &#39;showAxisDragHandles&#39;, &#39;showAxisRangeEntryBoxes&#39;, &#39;showTips&#39;, &#39;showLink&#39;, &#39;linkText&#39;, &#39;sendData&#39;, &#39;showSources&#39;, &#39;displayModeBar&#39;, &#39;showSendToCloud&#39;, &#39;showEditInChartStudio&#39;, &#39;modeBarButtonsToRemove&#39;, &#39;modeBarButtonsToAdd&#39;, &#39;modeBarButtons&#39;, &#39;toImageButtonOptions&#39;, &#39;displaylogo&#39;, &#39;watermark&#39;, &#39;plotGlPixelRatio&#39;, &#39;setBackground&#39;, &#39;topojsonURL&#39;, &#39;mapboxAccessToken&#39;, &#39;logging&#39;, &#39;notifyOnLogging&#39;, &#39;queueLength&#39;, &#39;globalTransforms&#39;, &#39;locale&#39;, &#39;locales&#39;</code></pre>
<div id="htmlwidget-c46557e38c2b815d5bef" style="width:100%;height:504px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-c46557e38c2b815d5bef">{"x":{"data":[{"orientation":"h","width":[0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.9,0.9,0.9,0.9,0.9,0.9,0.9],"base":[-1,-1,-1,-4,-4,-4,-4,-4,-5,-5,-10,-12,-9,-6,-5,-6,-7,-10,-9],"x":[1,1,1,4,4,4,4,4,5,5,10,12,9,6,5,6,7,10,9],"y":[19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1],"text":[" Men <br> 1 %"," Men <br> 1 %"," Men <br> 1 %"," Men <br> 4 %"," Men <br> 4 %"," Men <br> 4 %"," Men <br> 4 %"," Men <br> 4 %"," Men <br> 5 %"," Men <br> 5 %"," Men <br> 10 %"," Men <br> 12 %"," Men <br> 9 %"," Men <br> 6 %"," Men <br> 5 %"," Men <br> 6 %"," Men <br> 7 %"," Men <br> 10 %"," Men <br> 9 %"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(54,155,158,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Men","legendgroup":"Men","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"h","width":[0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.9,0.9,0.9,0.9,0.9,0.9,0.9],"base":[-2,-4,-2,-1,-2,-5,-10,-11,-8,-5,-4,-8,-11,-8,-5,-4,-4,-4,-5],"x":[2,4,2,1,2,5,10,11,8,5,4,8,11,8,5,4,4,4,5],"y":[19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1],"text":[" Men <br> 2 %"," Men <br> 4 %"," Men <br> 2 %"," Men <br> 1 %"," Men <br> 2 %"," Men <br> 5 %"," Men <br> 10 %"," Men <br> 11 %"," Men <br> 8 %"," Men <br> 5 %"," Men <br> 4 %"," Men <br> 8 %"," Men <br> 11 %"," Men <br> 8 %"," Men <br> 5 %"," Men <br> 4 %"," Men <br> 4 %"," Men <br> 4 %"," Men <br> 5 %"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(54,155,158,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Men","legendgroup":"Men","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"h","width":[0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.9,0.9,0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[1,2,3,4,4,5,5,5,5,5,9,12,10,7,3,5,6,10,9],"y":[19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1],"text":[" Women <br> 1 %"," Women <br> 2 %"," Women <br> 3 %"," Women <br> 4 %"," Women <br> 4 %"," Women <br> 5 %"," Women <br> 5 %"," Women <br> 5 %"," Women <br> 5 %"," Women <br> 5 %"," Women <br> 9 %"," Women <br> 12 %"," Women <br> 10 %"," Women <br> 7 %"," Women <br> 3 %"," Women <br> 5 %"," Women <br> 6 %"," Women <br> 10 %"," Women <br> 9 %"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(197,68,9,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Women","legendgroup":"Women","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"h","width":[0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.9,0.9,0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[6,5,6,3,5,6,7,7,11,3,3,4,5,8,6,5,1,5,4],"y":[19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1],"text":[" Women <br> 6 %"," Women <br> 5 %"," Women <br> 6 %"," Women <br> 3 %"," Women <br> 5 %"," Women <br> 6 %"," Women <br> 7 %"," Women <br> 7 %"," Women <br> 11 %"," Women <br> 3 %"," Women <br> 3 %"," Women <br> 4 %"," Women <br> 5 %"," Women <br> 8 %"," Women <br> 6 %"," Women <br> 5 %"," Women <br> 1 %"," Women <br> 5 %"," Women <br> 4 %"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(197,68,9,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Women","legendgroup":"Women","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":48.1811579281108,"r":0,"b":27.563304275633,"l":43.5035284350353},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(41,43,44,1)","family":"Montserrat","size":13.2835201328352},"xaxis":{"domain":[0,0.489128071319852],"automargin":true,"type":"linear","autorange":false,"range":[-15.84,15.84],"tickmode":"array","ticktext":[15,10,5,0,5,10,15],"tickvals":[-15,-10,-5,0,5,10,15],"categoryorder":"array","categoryarray":[15,10,5,0,5,10,15],"nticks":null,"ticks":"outside","tickcolor":"rgba(234,234,234,1)","ticklen":3.65296803652968,"tickwidth":0.265670402656704,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"Montserrat","size":10.6268161062682},"tickangle":-0,"showline":true,"linecolor":"rgba(234,234,234,1)","linewidth":0.265670402656704,"showgrid":true,"gridcolor":"rgba(234,234,234,1)","gridwidth":0.265670402656704,"zeroline":false,"anchor":"y","title":"","hoverformat":".2f","fixedrange":true},"annotations":[{"text":"%","x":0.5,"y":-0.04151100041511,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(41,43,44,1)","family":"Montserrat","size":13.2835201328352},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"top","annotationType":"axis"},{"text":"Age","x":-0.0548538219771097,"y":0.5,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(41,43,44,1)","family":"Montserrat","size":13.2835201328352},"xref":"paper","yref":"paper","textangle":-90,"xanchor":"right","yanchor":"center","annotationType":"axis"},{"text":"Tallinn suburb","x":0.244564035659926,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(41,43,44,1)","family":"Montserrat","size":13.2835201328352},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Rural small town","x":0.755435964340074,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(41,43,44,1)","family":"Montserrat","size":13.2835201328352},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"}],"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.4,19.6],"tickmode":"array","ticktext":["0-4","5-9","10-14","15-19","20-24","25-29","30-34","35-39","40-44","45-49","50-54","55-59","60-64","65-69","70-74","75-79","80-84","85-89","90+"],"tickvals":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],"categoryorder":"array","categoryarray":["0-4","5-9","10-14","15-19","20-24","25-29","30-34","35-39","40-44","45-49","50-54","55-59","60-64","65-69","70-74","75-79","80-84","85-89","90+"],"nticks":null,"ticks":"outside","tickcolor":"rgba(234,234,234,1)","ticklen":3.65296803652968,"tickwidth":0.265670402656704,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"Montserrat","size":10.6268161062682},"tickangle":-0,"showline":true,"linecolor":"rgba(234,234,234,1)","linewidth":0.265670402656704,"showgrid":true,"gridcolor":"rgba(234,234,234,1)","gridwidth":0.265670402656704,"zeroline":false,"anchor":"x","title":"","hoverformat":".2f","fixedrange":true},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":0.489128071319852,"y0":0,"y1":1},{"type":"rect","fillcolor":"rgba(255,255,255,1)","line":{"color":"rgba(255,255,255,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":0.489128071319852,"y0":0,"y1":24.9730178497302,"yanchor":1,"ysizemode":"pixel"},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.510871928680148,"x1":1,"y0":0,"y1":1},{"type":"rect","fillcolor":"rgba(255,255,255,1)","line":{"color":"rgba(255,255,255,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0.510871928680148,"x1":1,"y0":0,"y1":24.9730178497302,"yanchor":1,"ysizemode":"pixel"}],"xaxis2":{"type":"linear","autorange":false,"range":[-15.84,15.84],"tickmode":"array","ticktext":[15,10,5,0,5,10,15],"tickvals":[-15,-10,-5,0,5,10,15],"categoryorder":"array","categoryarray":[15,10,5,0,5,10,15],"nticks":null,"ticks":"outside","tickcolor":"rgba(234,234,234,1)","ticklen":3.65296803652968,"tickwidth":0.265670402656704,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"Montserrat","size":10.6268161062682},"tickangle":-0,"showline":true,"linecolor":"rgba(234,234,234,1)","linewidth":0.265670402656704,"showgrid":true,"domain":[0.510871928680148,1],"gridcolor":"rgba(234,234,234,1)","gridwidth":0.265670402656704,"zeroline":false,"anchor":"y","title":"","hoverformat":".2f"},"showlegend":true,"legend":{"bgcolor":"transparent","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(41,43,44,1)","family":"Montserrat","size":10.6268161062682},"y":1.15,"orientation":"h"},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","showSendToCloud":false,"displayModeBar":false,"collaborate":false},"source":"A","attrs":{"b18d134c9d40":{"x":{},"y":{},"fill":{},"text":{},"type":"bar"}},"cur_data":"b18d134c9d40","visdat":{"b18d134c9d40":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
<div class="mobile-plot">
<p><img src="EIA_2019_digi_eng_files/figure-html/unnamed-chunk-13-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div class="imgsource">
<div>
<p><span class="imgsource-source">Source:</span> Population Register.</p>
</div>
<div>
<p><a class="data-btn" href="data/0_fig2_data.csv"><i class="fa fa-download" aria-hidden="true"></i></i>Laadi andmed</a></p>
</div>
</div>
<p>The shrinkage does not involve only labour migration and the search for higher income. Excess housing stock, which is deteriorating in terms of their liveability as well as structurally and technologically, has tied down many Estonian families, as the market price of their homes has sunk. At the same time, the counties do not offer young families the opportunity to start a home in new housing. Inequality in terms of living conditions and property prices, and sporadic public transport pushes minors and retirement-age population into mobility poverty, and thereby further deepens the overall regional inequality in Estonia (<a href="modern-living-conditions-whose-privilege.html#modern-living-conditions-whose-privilege">Kährik and Väiko, Ch. 1</a>; <a href="#accessibility-changes-in-motorised-Estonia">Tuvikene et al., Ch. 1</a>).</p>
<div class="blockquote-right">
<p>
Estonia needs a place-based plan for smart shrinking in three key areas: jobs, homes and public services.
</p>
</div>
<p>The weakening of the counties and county towns has accelerated the trend towards a two-centre Estonia, consisting of Tallinn and Tartu, and their respective hinterlands within an hour’s drive of each city (<a href="introduction-0.html#figure03">Figure 0.3</a>). First, the jobs move to Tallinn or Tartu, then the homes and services follow. After university studies, many young people stay in Tallinn or Tartu, rather than returning home. This process is mitigated by the multilocality. Many people own two homes, one in the city and the other in the countryside, where they travel on weekends and for summer holidays. In addition, there are also transnational families, who live abroad and come on holiday to Estonia. Transnationalism has brought Tallinn closer to Helsinki and Stockholm than, for example, Rakvere or Paide, both in terms of time geography – as places to live and work – and in terms of living conditions. Therefore, the counties, and also the university city of Tartu, remain remote and are sidelined in the processes of globalisation (<a href="introduction-1.html#introduction-1">Leetmaa, Ch. 1</a>). The concept of proximity to home has also changed as a result of time-space compression and acceleration (<a href="introduction-0.html#Lauristin2017">Lauristin et al. 2017</a>) as well as due to the urban life model; it has expanded to cover towns and rural areas. This, in turn, has undermined spatial identity, blurring the meaning of the hometown or village.</p>
<p class="caption" id="figure03">
<span class="figure-number">Figure 0.3.</span> The Estonian urban system outlined by geographer Edgar Kant nearly a century ago essentially still applies today, including the concept of two urban centres with catchment areas within a radius of an hour’s drive around Tallinn and Tartu – ‘one-hour Estonia’
</p>
<p><img src="../figures/0-intro/fig03.png" width="100%" style="display: block; margin: auto;" /></p>
<div class="imgsource">
<p>
<span class="imgsource-source">Source:</span> Kant (1935).
</p>
</div>
<p>So far, spatial restructuring in public administration and the recent administrative reform have failed to provide a key to sustainable shrinkage. On the one hand, the central government required rural municipalities to merge in order to address population decline and join forces in organising life in the country. On the other hand, services and other social networks (shopping and leisure centres, education and medical services, etc.) keep on moving to the cities. European Union programmes and projects that promote entrepreneurship and revitalise rural areas have had a modest impact, as they have largely reached only urban areas (<a href="#monitoringreport2019">Estonian Regional Development Strategy 2014–2020 monitoring report 2019</a>; <a href="introduction-0.html#Raagmaa2014">Raagmaa et al. 2014</a>). So far, regional policy has been focused on the competitiveness of regions. This sort of regional policy has supported market economy processes but has not helped to decrease peripheralisation (<a href="increasing-regional-polarisation-in-estonia.html#increasing-regional-polarisation-in-estonia">Plüschke-Altof et al., Ch. 1</a>).</p>
<p>Estonia needs a place-based plan for smart shrinking in three key areas: jobs, homes and public services. This requires regional development to be planned and the challenges resolved from two fundamentally different perspectives: from the point of view of growth and competition based on the principles of the market economy, and from the point of view of shrinking based on solidarity. Estonia needs two public governance models – one for metropolisation, the other for shrinkage.</p>
</div>
<div id="public-debate-results-in-a-better-living-environment-and-greater-consensus" class="section level3 unnumbered chapter0_section">
<h3>Public debate results in a better living environment and greater consensus</h3>
<p>As the nature of the physical public space has changed substantially in recent decades, our communication environments have undergone an equally fundamental change. Communicating and socialising on digital platforms offers extensive opportunities for discussions and meetings with strangers as well as people we know. Virtual space is taking over the functions of physical space (<a href="introduction-4.html#introduction-4">Ibrus, Ch. 4</a>). Like the living environment and physical space, the deliberative environment should also be diverse and balanced (<a href="the-deliberative-space-shaped-by-the-press.html#the-deliberative-space-shaped-by-the-press">Kõuts-Klemm, ptk 4</a>). Today, traditional printed journalism is retreating in the face of new media, thus deepening the digital divide. This has led to the narrowing of the local information space in many parts of Estonia (<a href="estonian-youth-in-the-virtual-opinion-space.html#estonian-youth-in-the-virtual-opinion-space">Kalmus and Siibak, Ch. 4</a>), which points to the problem that older people lack access to the media due to their insufficient digital skills (<a href="introduction-0.html#Tambaum2019">Tambaum 2019</a>).</p>
<p>The discussion of public issues in online media has shifted from argumentation towards oversimplification. Communication is dominated by easily grasped messages with a strong emotional charge (<a href="socio-political-discussion-in-the-digital-public-space.html#socio-political-discussion-in-the-digital-public-space">Ventsel and Madisson, Ch. 4</a>). On the other hand, the impact of new media and the resulting echo chamber effect on the deliberative space have been overestimated. The emotional form of communication originating in social media has spread throughout the media space, where expert and evidence-based argumentation can be hijacked to set up a conflict between different positions and refute arguments instead of finding common ground in the debate (<a href="the-role-and-status-of-experts-in-societal-media-discussions.html#the-role-and-status-of-experts-in-societal-media-discussions">Olesk, Ch. 4</a>). SThis is also the reason why Estonian youth do not want to participate in public debates (<a href="estonian-youth-in-the-virtual-opinion-space.html#estonian-youth-in-the-virtual-opinion-space">Kalmus and Siibak, Ch. 4</a>). A culture of communication includes the ability to follow good practice in public communication.</p>
<div class="blockquote-left">
<p>
A culture of communication includes the ability to follow good practice in public communication.
</p>
</div>
<p>Estonian civil society advocates have been promoting a culture of deliberation and participation. Despite these efforts, the level of civic activism remains low in Estonia – we are several decades behind countries like Finland and Sweden (<a href="introduction-0.html#Ainsaar2019">Ainsaar and Strenze 2019</a>). ISpatial planning practices have become increasingly open and democratic in Estonia since the country regained its independence. This is beginning to instil in people the understanding that public participation is part of creating and shaping a good living environment. Yet, most of the Estonian population has a passive or pessimistic attitude towards public participation (<a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#public-participation-in-decisions-on-the-use-of-natural-areas">Vahtrus et al., Ch. 3</a>). This is caused by insufficient feedback and a merely formal approach to engaging the public, and with that reducing the meaningfulness and credibility of public participation and giving rise to participation fatigue. Interest groups that advocate for public space are actively seeking dialogue partners in the public or private sector and are driving the development of civil society and a more democratic culture of participation (<a href="urban-activism-in-the-co-creation-of-public-space.html#urban-activism-in-the-co-creation-of-public-space">Kljavin et al., Ch. 2</a>). Even so, public administration has become overly bureaucratic and impenetrably technocratic. Finding a consensus is obstructed by the barrier of the highly specialised language that exists between the planners and designers on the one hand and citizens on the other. The detailed technical drawings and descriptions submitted for public discussion in the depths of the internet do not allow ordinary people the opportunity to have a say in local development. This, in turn, has led to an opposition to development and spatial change – the attitude of ‘not in my backyard’, or NIMBYism.</p>
<p>Viimaste aastate konfliktid ruumi planeerimisel ning arutelud loodusalade kasutamisest annavad tunnistust keskkonna väärtuste mitmetimõistmisest.</p>
<div class="blockquote-right">
<p>
Viimaste aastate konfliktid ruumi planeerimisel ning arutelud loodusalade kasutamisest annavad tunnistust keskkonna väärtuste mitmetimõistmisest.
</p>
</div>
<p>The poor quality of debate is one of the biggest problems of the information age. There are various solutions for creating better space and clarifying the views of the different parties. A balanced, consensus-oriented deliberative space is a prerequisite for cooperation and cohesion between different social groups. The development of deliberative skills is in the public interest. We need to improve citizen competence and debating skills in order to empower our citizens and promote broad-based democracy. Opportunities for this are provided by digital platforms, which are already being developed, a competent civil service and professional experts.</p>
</div>
<div id="built-heritage-and-natural-areas-as-part-of-our-culture-strengthen-peoples-relationship-with-the-environment-and-their-sense-of-belonging" class="section level3 unnumbered chapter0_section">
<h3>Built heritage and natural areas as part of our culture strengthen people’s relationship with the environment and their sense of belonging</h3>
<p>Physical space as an integral part of cultural space is another medium for national self-description alongside historical and textual narratives. Layers of different historical eras are embedded in our living environment with its contemporary and historical buildings, urban and rural fabric, settlement structures, and land use. This makes our landscape, its design and representations one of the most important means for creating a collective memory and identity, much the same way as our core literary texts, films, theatre performances, or song and dance festivals. According to the Statistics Estonia collection Sustainable Development Indicators (2018), the state of our cultural heritage continues to show the sustainability of Estonian culture and society’s awareness of the values of cultural heritage.</p>
<p>New buildings have been erected for the country’s most important cultural and memory institutions – the Art Museum of Estonia (Kumu) and the Estonian National Museum (ERM). We also need to value the existing architectural and landscape heritage more. Alongside the construction of new buildings, the re-use of built heritage should be preferred more systematically. This will bring socio-economic benefits to the entire region, rather than just a specific area of life (<a href="introduction-0.html#HistoricEngland2019">Historic England 2019</a>).The utilisation of cultural heritage will make small towns and settlements as a whole more attractive both for the population and for visitors to the area (<a href="built-heritage-and-spatial-quality.html#built-heritage-and-spatial-quality">Talk and Raie, Ch. 2</a>).Establishing this kind of thinking requires thorough socio-economic impact analysis and a comprehensive view of both the built heritage and the region as whole, as well as taking into account the interests and available resources of as many stakeholders as possible (<a href="introduction-2.html#introduction-2">Lankots, Ch. 2</a>). It is also appropriate to ask for each site what the purpose of preserving the heritage would be and look at the ability of the state or the private owner to invest in the protected site. For a more diverse living environment, Estonia’s built heritage needs protection combined with a socio-cultural and economic impact assessment, as well as a national investment plan and measures to ensure the preservation, reuse and management of historical buildings that are a priority for the state.</p>
<p>The urbanisation process in recent decades has had an impact on cultural practices. In Estonia, many cultural practices orally passed down from generation to generation, such as mushroom and berry picking and the cultivation and preservation of fruit and vegetables, have survived. We protect nature and care about the environment. The annual Let’s Do It! campaign days, which bring together thousands of Estonians, are a case in point. The State Forest Management Centre’s recreational areas are extremely popular among city dwellers and in many places operate at the limit of their visitor capacity. Despite all this, the Estonian population is losing contact with nature; the last couple of generations are lacking knowledge of nature more broadly, and there is also an irrational fear of nature (<a href="how-do-people-use-the-natural-environment-in-estonia.html#how-do-people-use-the-natural-environment-in-estonia">Sepp and Lõhmus, Ch. 3</a>). The loss of biodiversity and natural sites in Estonia (<a href="introduction-0.html#EEA2019b">EEA 2019b</a>; <a href="introduction-3.html#introduction-3">Lõhmus, Ch. 3</a>), as well as across Europe, and the expansion of the built environment signal ruptures in the value system of Estonian society, which explain the conflicts over spatial planning and the use of natural areas in recent years (<a href="the-role-and-status-of-experts-in-societal-media-discussions.html#the-role-and-status-of-experts-in-societal-media-discussions">Olesk, Ch. 4</a>; <a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#public-participation-in-decisions-on-the-use-of-natural-areas">Vahtrus et al., Ch. 3</a>). Such a rupture in cultural continuity is directly related to environmental awareness and behaviour towards the environment. Gandy (<a href="introduction-0.html#Gandy2018">2018</a>)points out that we cannot increase people’s ecological awareness if their exposure to nature is limited to TV shows, images in magazines and visits to natural museums. Society will take climate change and threats to biodiversity more seriously only if people perceive and experience nature directly. Integrated planning in Estonian urban areas will stop building over urban and peri-urban green spaces, which are crucial for human health and well-being.</p>
</div>
<div id="future-perspectivese" class="section level3 unnumbered chapter0_section">
<h3>Future perspectivese</h3>
<p>While they have a powerful socio-economic impact, cities are also vulnerable systems. The authors of this human development report consistently point out that the growth of Estonia’s largest cities, especially the Tallinn urban area, in terms of building stock and infrastructure often comes at the expense of public space and greenery, which are important for people’s mental and physical well-being. They also draw attention to the link between climate change and rapid automobilisation. Reducing carbon emissions requires preferring more climate-friendly modes of mobility (<a href="#accessibility-changes-in-motorised-Estonia">Tuvikene et al., Ch. 1</a>).</p>
<p>Examples of numerous cities, both in the Baltic Sea region and Europe more broadly, highlight the growing role of cities as drivers of sustainable development and innovation. Urban growth will be guided by the European Union’s climate policy both in the near future and in the longer term. What does the climate policy entail for governance? The main criterion for planning decisions will be the efficiency of land use in relation to climate change. In the next decade, the focus of European climate policy will extend from energy use to land use, designated as LULUCF (land use, land-use change and forestry) in current carbon accounting to emphasise the role of land-use change and forestry in the carbon cycle. The circular economy is becoming increasingly important. In the urban environment, this is reflected in the renewal of urban areas, brownfield development and renovating existing buildings instead of erecting new ones.</p>
<p>An urban environment that follows the principles of sustainable development and provides a good quality of life feels good for 8 and 80-year-olds alike. On its way to becoming the European Capital of Culture, the city of Tartu is promoting a new era of urbanism in Estonia, looking at urban culture in terms of urban space and the living environment. In the coming years, Tartu will make infrastructure investments preferring pedestrians and cyclists; it will enhance the city centre by building parks suitable for children and the elderly, creating new well-adapted architecture, and promoting street culture. Pärnu has also set the goal of improving the health of its residents by boosting the quality of the urban environment. Cooperation between cities, universities and health institutions to create a health-promoting environment can lay the foundations for improving public health, thereby reducing direct health costs (<a href="estonian-living-environment-in-2050.html#estonian-living-environment-in-2050">Grišakov, Ch. 5</a>).</p>
<div class="blockquote-right">
<p>
Estonia is no exception in terms of peripheralisation, but due to our geopolitical location, it may threaten Estonia’s statehood.
</p>
</div>
<p>Neither the Nordic countries nor the rest of Europe have so far been able to propose effective policies to curb shrinkage in rural areas. However, there are promising examples from the Nordics (<a href="introduction-0.html#Nordregio2017">Nordregio 2017</a>) that may also be suitable for Estonia. Estonia is no exception in terms of peripheralisation, but due to our geopolitical location, it may threaten Estonia’s statehood. The decline of permanent settlement in the border areas creates a territorial vacuum where only Estonian military and law enforcement agencies operate. This is often the only way to ensure a state presence in these areas. Addressing the issue of border regions requires closer co-operation with the other Baltic States. Following the recent local governance reform, people in rural areas need reassurance that high-quality services will be available to all age groups. Based on the experience of other countries (ibid.), the key to retaining existing local communities and attracting young people to the regions may lie in the active participation of local citizens in the development processes of the region and in guiding these processes. Local government that is open, empowering and encourages cooperation ensures an atmosphere of trust, inducing people to care about the planning and implementation of local development, and providing them the opportunity to guide regional development. This involves long-term strategic agreements that are based on trust and transcend daily politics.</p>
<p>There is untapped potential in integrating Estonian civil society into national and local-level decision-making processes. More effective, transparent and feedback-based modes of public participation are needed to promote deliberative democracy, ensuring the exchange of knowledge and building trust between the state and its citizens. Another trust-building mechanism in society is the accessibility and accuracy of data. Society’s innovation is driven by the smart city, which relies on the interpretation of real-time public data and integrated knowledge transfer between private enterprises, universities and citizens’ initiatives. Citizen science based on publicly accessible data can offer additional social innovation solutions to urban and rural communities, and also act as a partner for the state and local governments in solving specific problems. In this way, civil society is a partner that fosters social cohesion and influences governance processes through participation.</p>
<p>By the time this report is complete, we are in the grip of a global health crisis. Large cities, where disease control is difficult, are particularly vulnerable in this situation. Major outbreaks of disease known throughout history have significantly changed the nature and behavioural patterns of cities and societies. It is to be hoped that the two current major global challenges – the health and climate crises – will be tackled in tandem.</p>
</div>
<div id="references" class="section level3 unnumbered subreferences">
<h3>References</h3>
<p id="Ainsaar2019">
Ainsaar, M., Strenze, T. (ed.) 2019. Väärtused kui inimvara ja nende seos ühiskonna arenguga. Tallinn, Tartu: Arenguseire Keskus, Tartu Ülikool.
</p>
<p id="Brenner2019">
Brenner, N. 2019. New Urban Spaces: Urban Theory and the Scale Question. Oxford: Oxford University Press.
</p>
<p id="Clark2019">
Clark, G., Moonen, T., Nunley, J. 2019. The Story of Your City: Europe and its Urban Development 1970 to 2020. European Investment Bank.
</p>
<p id="EEA2019">
EEA – European Environmental Agency 2019a. Land and soil in Europe. EEA Signals 2019. Luxembourg: Publications Office of the European Union.
</p>
<p id="EEA2019b">
EEA – European Environmental Agency 2019b. The European environment – state and outlook 2020. Luxembourg: Publications Office of the European Union.
</p>
<p id="Eestiinimvararaport2019">
Eesti inimvara raport 2019. Tallinn: Arenguseire Keskus.
</p>
<p id="#monitoringreport2019">
Estonian Regional Development Strategy 2014–2020 monitoring report 2019. Tallinn: Rahandusministeerium.
</p>
<p id="Gandy2018">
Gandy, M. 2018. Cities in deep time. – Cities, 22 (1), 96–195.
</p>
<p id="Hansis2015">
Hansis, E., Davis, S. J., Pongratz, J. 2015. Relevance of methodological choices for accounting of land use change carbon fluxes. – Global Biogeochemical Cycles, 29 (8), 1230–1246.
</p>
<p id="HistoricEngland2019">
Historic England 2019. – Annual Report &amp; Accounts 2018/2019.
</p>
<p id="Kalm2018">
Kalm, M. 2018. Eesti arhitektuuri 100 aastat. Talust tarbimismaastikuni. Tallinn: Postimehe Kirjastus.
</p>
<p id="Kant1935">
Kant, E. 1935. Bevölkerung und Lebensraum Estlands: ein anthropoökologischer Beitrag zur Kunde Baltoskandias. Tartu: Akadeemiline Kooperatiiv.
</p>
<p id="Lauristin2001">
Lauristin, M. 2001. Kas siirdeaeg on Eestis lõppenud? – Eesti Päevaleht, 25.04.2001.
</p>
<p id="Lauristin2017">
Lauristin, M., Kalmus, V., Keller, M., Kiisel, M., Massu, A., Opermann, S., Vihalemm, P., Vihalemm, T. 2017. Kokkuvõte. Eesti ühiskonda kujundavad protsessid ja tulevikuarengud. – Vihalemm, P., Lauristin, M., Kalmus, V., Vihalemm, T. (ed.) Eesti ühiskond kiirenevas ajas. Uuringu „Mina. Maailm. Meedia“ 2002–2014 tulemused. Tartu: Tartu Ülikooli Kirjastus, 669–723.
</p>
<p id="Mäntysalo2019">
Mäntysalo, R., Kanninen, V., Purkarthofer, E., Koste, O.-W. (ed.) 2019. Kaupunkiseudut: Ristiinvalotuksia ja rajanylityksiä. BEMINE-hankkeen loppuraportti. Aalto-yliopiston julkaisusarja CROSSOVER 3/2019.
</p>
<p id="Nijkamp2013">
Nijkamp, P., Kourtit, K. 2013. The “New Urban Europe”: Global Challenges and Local Responses in the Urban Century. – European Planning Studies, 21 (3), 291–315.
</p>
<p id="Nordregio2017">
Nordregio 2017. White paper on Nordic sustainable cities. Stockholm: Nordregio.
</p>
<p id="Raagmaa2014">
Raagmaa, G., Kalvet, T., Kasesalu, R. 2014. Europeanization and De-Europeanization of Estonian Regional Policy. – European Planning Studies, 22 (4), 775–795.
</p>
<p id="#NationalHealthPlan2030)">
National Health Plan 2020–2030. Tööversioon. Tallinn: Sotsiaalministeerium, 2020.
</p>
<p id="Schmidt2018">
Schmidt, C. 2018. Journeys through planetary urbanization: Decentering perspectives on the urban. – Environment and Planning D: Society and Space, 36 (3), 591–610.
</p>
<p id="#StatisticsEstonia2018">
Sustainable Development Indicators 2018. Tallinn: Statistics Estonia.
Tambaum, T. 2016. 55+ rahvastiku internetikasutus ja sotsiaalne aktiivsus. – Sakkeus, L., Leppik, L. (ed.). Pilk hallile alale. SHARE Eesti uuringu esimene ülevaade ja soovitused eakate poliitika kujundamiseks. Tallinn: Tallinna Ülikool, 182−205.
</p>
<p id="Tambaum2019">
Tambaum, T. 2019. Vanemas tööeas inimeste interneti kasutus ja sotsiaalne aktiivsus SHARE nelja laine andmetes. – Sakkeus, L., Tambaum, T. (ed.). Vananemine elukaare vaates. SHARE Eesti Uuringu teine ülevaade. Tallinn: Tallinna Ülikool, 71–84.
</p>
<p id="Tammaru2020">
Tammaru, T., Marcinczak, S., Aunap, R., van Ham, M., Janssen, H. 2020. Relationship between income inequality and residential segregation of socioeconomic groups. – Regional Studies, 54 (4), 450–461.
</p>
<p id="Vetik2002">
Vetik, R. (ed.) 2002. Kaks Eestit. Artiklite, ettekannete ja analüüside kogumik. Tallinn: Tallinna Pedagoogikaülikool.
</p>
<p id="UnitedNations2019">
United Nations – UNDP 2019. Human Development Report 2019. Beyond income, beyond averages, beyond today: Inequalities in human development in the 21st century. New York. <a href="http://hdr.undp.org/en/content/human-development-report-2019" class="uri">http://hdr.undp.org/en/content/human-development-report-2019</a>.
</p>

</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="foreword.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="diversity-in-the-estonian-living-environment.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": true,
"weibo": false,
"instapaper": false,
"vk": false,
"all": false,
"google": false
},
"fontsettings": false,
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"scroll_highlight": true,
"toolbar": null,
"position": "fixed",
"edit": null,
"download": null,
"search": true
}
});
});
</script>

</body>

</html>
