<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Introduction | Estonian Human Development Report 2019/2020</title>
  <meta name="description" content="Spatial Choices for an Urbanised Society" />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Introduction | Estonian Human Development Report 2019/2020" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="https://inimareng.ee/cover.png" />
  <meta property="og:description" content="Spatial Choices for an Urbanised Society" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction | Estonian Human Development Report 2019/2020" />
  
  <meta name="twitter:description" content="Spatial Choices for an Urbanised Society" />
  <meta name="twitter:image" content="https://inimareng.ee/cover.png" />




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="foreword.html"/>
<link rel="next" href="diversity-in-the-estonian-living-environment.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.2/leaflet.js"></script>
<script src="libs/leaflet-providers-1.1.17/leaflet-providers.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.2/leaflet-providers-plugin.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-168674881-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-168674881-1');
</script>
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#a94b23">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="../eia.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="estonian-human-development-report-20192020.html"><a href="estonian-human-development-report-20192020.html"><i class="fa fa-check"></i>Estonian Human Development Report 2019/2020</a><ul>
<li class="chapter" data-level="" data-path="foreword.html"><a href="foreword.html"><i class="fa fa-check"></i>Foreword</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#põhisõnumid"><i class="fa fa-check"></i>Põhisõnumid</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#eesti-on-inimarengus-edenenud-maailma-riikide-hulgas-30.-positsioonile-kuid-jäänud-sinna-püsima"><i class="fa fa-check"></i>Eesti on inimarengus edenenud maailma riikide hulgas 30. positsioonile, kuid jäänud sinna püsima</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#eesti-suurlinnastumist-väljendab-suur-tallinna-jätkuv-kasv-inimesed-majandus-ja-teenused-koonduvad-tallinna-linnapiirkonda-ning-ülejäänud-eesti-kahaneb-ja-taandareneb"><i class="fa fa-check"></i>Eesti suurlinnastumist väljendab Suur-Tallinna jätkuv kasv: inimesed, majandus ja teenused koonduvad Tallinna linnapiirkonda ning ülejäänud Eesti kahaneb ja taandareneb</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#eesti-inimeste-mitmepaiksus-seob-tallinna-maakondadega-ja-linnad-küladega"><i class="fa fa-check"></i>Eesti inimeste mitmepaiksus seob Tallinna maakondadega ja linnad küladega</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#avalik-arutelu-loob-parema-elukeskkonna-ja-püüdleb-ühismeelele"><i class="fa fa-check"></i>Avalik arutelu loob parema elukeskkonna ja püüdleb ühismeelele</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#ehituspärand-ja-loodusalad-kultuuri-osana-tugevdavad-eesti-inimeste-keskkonnasuhet-ja-kodutunnet"><i class="fa fa-check"></i>Ehituspärand ja loodusalad kultuuri osana tugevdavad Eesti inimeste keskkonnasuhet ja kodutunnet</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#tulevikuvaade"><i class="fa fa-check"></i>Tulevikuvaade</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#viidatud-allikad"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="diversity-in-the-estonian-living-environment.html"><a href="diversity-in-the-estonian-living-environment.html"><i class="fa fa-check"></i><b>1</b> Diversity in the Estonian living environment</a><ul>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#põhisõnumid-1"><i class="fa fa-check"></i>Põhisõnumid</a></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#lähtekohad"><i class="fa fa-check"></i>Lähtekohad</a></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#artiklite-teemad"><i class="fa fa-check"></i>Artiklite teemad</a></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#eesti-maailmas"><i class="fa fa-check"></i>Eesti maailmas</a></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#kuidas-edasi"><i class="fa fa-check"></i>Kuidas edasi?</a></li>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#viidatud-allikad-1"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="1.1" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><i class="fa fa-check"></i><b>1.1</b> Changes in land use: distortion of the meaning of urban and rural</a><ul>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#rahvastiku-vähenemine-ja-ränne-linnaregioonidesse-mõjutab-maastikke"><i class="fa fa-check"></i>Rahvastiku vähenemine ja ränne linnaregioonidesse mõjutab maastikke</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#ehitatud-alade-pindala-suureneb-peamiselt-linnade-ümbruses"><i class="fa fa-check"></i>Ehitatud alade pindala suureneb peamiselt linnade ümbruses</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#linnade-laialivalgumisega-ühtlustub-linna-ja-tagamaa-ruumikasutus"><i class="fa fa-check"></i>Linnade laialivalgumisega ühtlustub linna ja tagamaa ruumikasutus</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#põllumajandusmaastik-väheneb-ja-tühjeneb-inimestest"><i class="fa fa-check"></i>Põllumajandusmaastik väheneb ja tühjeneb inimestest</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#metsamaa-pindala-kasvab-kuid-okasmetsi-on-vähem-ja-metsad-noorenevad"><i class="fa fa-check"></i>Metsamaa pindala kasvab, kuid okasmetsi on vähem ja metsad noorenevad</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#suund-väärtuslike-põllumaade-säilitamisele-pidurdab-maastikumuutusi"><i class="fa fa-check"></i>Suund väärtuslike põllumaade säilitamisele pidurdab maastikumuutusi</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#väärtuslikud-maastikud-ja-kaitsealad-toetavad-maastike-üldilme-säilimist"><i class="fa fa-check"></i>Väärtuslikud maastikud ja kaitsealad toetavad maastike üldilme säilimist</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#kokkuvõte"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html"><a href="changes-in-land-use-distortion-of-the-meaning-of-urban-and-rural.html#viidatud-allikad-2"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="increasing-regional-polarisation-in-estonia.html"><a href="increasing-regional-polarisation-in-estonia.html"><i class="fa fa-check"></i><b>1.2</b> Increasing regional polarisation in Estonia</a><ul>
<li class="chapter" data-level="" data-path="increasing-regional-polarisation-in-estonia.html"><a href="increasing-regional-polarisation-in-estonia.html#ääremaastumine-on-iseennast-taastootev-nõiaring"><i class="fa fa-check"></i>Ääremaastumine on iseennast taastootev nõiaring</a></li>
<li class="chapter" data-level="" data-path="increasing-regional-polarisation-in-estonia.html"><a href="increasing-regional-polarisation-in-estonia.html#maapiirkondade-ja-väikelinnade-häbimärgistamine-süvendab-ääremaastumist"><i class="fa fa-check"></i>Maapiirkondade ja väikelinnade häbimärgistamine süvendab ääremaastumist</a></li>
<li class="chapter" data-level="" data-path="increasing-regional-polarisation-in-estonia.html"><a href="increasing-regional-polarisation-in-estonia.html#konkurentsivõimele-keskenduv-regionaalpoliitika-ei-ole-ääremaastumist-vähendanud"><i class="fa fa-check"></i>Konkurentsivõimele keskenduv regionaalpoliitika ei ole ääremaastumist vähendanud</a></li>
<li class="chapter" data-level="" data-path="increasing-regional-polarisation-in-estonia.html"><a href="increasing-regional-polarisation-in-estonia.html#ääremaastaatus-ja--kuvand-piiravad-koha-konkurentsivõime-kasvu"><i class="fa fa-check"></i>Ääremaastaatus ja -kuvand piiravad koha konkurentsivõime kasvu</a></li>
<li class="chapter" data-level="" data-path="increasing-regional-polarisation-in-estonia.html"><a href="increasing-regional-polarisation-in-estonia.html#kokkuvõte-1"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li><a href="increasing-regional-polarisation-in-estonia.html#tänusõnad"><em>Tänusõnad</em></a></li>
<li class="chapter" data-level="" data-path="increasing-regional-polarisation-in-estonia.html"><a href="increasing-regional-polarisation-in-estonia.html#viidatud-allikad-3"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html"><i class="fa fa-check"></i><b>1.3</b> The triumph of planning freedom in suburban Estonia</a><ul>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#kuidas-määratleda-eeslinna"><i class="fa fa-check"></i>Kuidas määratleda eeslinna?</a></li>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#eeslinnas-elab-kümnendik-eesti-rahvast"><i class="fa fa-check"></i>Eeslinnas elab kümnendik Eesti rahvast</a></li>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#eeslinnaasumeid-iseloomustab-katkendlik-asustusstruktuur"><i class="fa fa-check"></i>Eeslinnaasumeid iseloomustab katkendlik asustusstruktuur</a></li>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#eeslinnamuster-sünnib-detailplaneeringute-summas"><i class="fa fa-check"></i>Eeslinnamuster sünnib detailplaneeringute summas</a></li>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#turujõud-ja-planeerimispoliitika-väljenduvad-kohaloomes"><i class="fa fa-check"></i>Turujõud ja planeerimispoliitika väljenduvad kohaloomes</a></li>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#kodulähedasi-avalikke-teenuseid-ja-avalikku-ruumi-eeslinnas-napib"><i class="fa fa-check"></i>Kodulähedasi avalikke teenuseid ja avalikku ruumi eeslinnas napib</a></li>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#kokkuvõte-2"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="the-triumph-of-planning-freedom-in-suburban-estonia.html"><a href="the-triumph-of-planning-freedom-in-suburban-estonia.html#viidatud-allikad-4"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html"><i class="fa fa-check"></i><b>1.4</b> Modern living conditions – whose privilege?</a><ul>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#tüüpiline-eestimaalane-elab-tüüpkorteris-eluasemefond-uueneb-kiiremini-pealinnaregioonis"><i class="fa fa-check"></i>Tüüpiline eestimaalane elab tüüpkorteris, eluasemefond uueneb kiiremini pealinnaregioonis</a></li>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#eluasemefondi-seisukord-on-paranemas-kuid-viletsamas-seisus-on-maapiirkondade-eluruumid"><i class="fa fa-check"></i>Eluasemefondi seisukord on paranemas, kuid viletsamas seisus on maapiirkondade eluruumid</a></li>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#majanduslik-kindlustatus---võti-elamistingimuste-parandamiseks"><i class="fa fa-check"></i>Majanduslik kindlustatus - võti elamistingimuste parandamiseks</a></li>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#taasiseseisvumise-järel-oli-eluasemekorraldus-täielikult-suunatud-turupõhisele-eluasemefondile"><i class="fa fa-check"></i>Taasiseseisvumise järel oli eluasemekorraldus täielikult suunatud turupõhisele eluasemefondile</a></li>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#avaliku-sektori-meetmeid-on-ajaga-lisandunud"><i class="fa fa-check"></i>Avaliku sektori meetmeid on ajaga lisandunud</a></li>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#rekonstrueerimistoetused-aitavad-elamistingimusi-parandada-kuid-regiooniti-ebaühtlaselt"><i class="fa fa-check"></i>Rekonstrueerimistoetused aitavad elamistingimusi parandada, kuid regiooniti ebaühtlaselt</a></li>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#võtmeküsimus-eluasemevaldkonnas-millised-on-sekkumise-võimalused"><i class="fa fa-check"></i>Võtmeküsimus eluasemevaldkonnas – millised on sekkumise võimalused?</a></li>
<li class="chapter" data-level="" data-path="modern-living-conditions-whose-privilege.html"><a href="modern-living-conditions-whose-privilege.html#viidatud-allikad-5"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html"><i class="fa fa-check"></i><b>1.5</b> Accessibility changes in motorised Estonia</a><ul>
<li class="chapter" data-level="" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html#aastate-kiire-autostumine-on-stabiliseerumas"><i class="fa fa-check"></i>1990. aastate kiire autostumine on stabiliseerumas</a></li>
<li class="chapter" data-level="" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html#autostumisel-on-mõju-keskkonnale-inimeste-tervisele-ja-võimalusele-liikuda-ning-teenuseid-kasutada"><i class="fa fa-check"></i>Autostumisel on mõju keskkonnale, inimeste tervisele ja võimalusele liikuda ning teenuseid kasutada</a></li>
<li class="chapter" data-level="" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html#hajaasustuse-elu-on-autokeskne"><i class="fa fa-check"></i>Hajaasustuse elu on autokeskne</a></li>
<li class="chapter" data-level="" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html#elu-eeslinnas-on-linnaelust-autokesksem"><i class="fa fa-check"></i>Elu eeslinnas on linnaelust autokesksem</a></li>
<li class="chapter" data-level="" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html#linnakeskuste-liikuvuse-arendamine-lähtub-autodest"><i class="fa fa-check"></i>Linnakeskuste liikuvuse arendamine lähtub autodest</a></li>
<li class="chapter" data-level="" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html#tulevikutrendid-erinevate-liikumisviiside-õigetes-mahtudes-võimaldamine-tagab-vähema-autokasutuse"><i class="fa fa-check"></i>Tulevikutrendid: erinevate liikumisviiside õigetes mahtudes võimaldamine tagab vähema autokasutuse</a></li>
<li class="chapter" data-level="" data-path="accessibility-changes-in-motorised-estonia.html"><a href="accessibility-changes-in-motorised-estonia.html#viidatud-allikad-6"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="public-urban-space.html"><a href="public-urban-space.html"><i class="fa fa-check"></i><b>2</b> Public urban space</a><ul>
<li class="chapter" data-level="" data-path="introduction-2.html"><a href="introduction-2.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction-2.html"><a href="introduction-2.html#põhisõnumid-2"><i class="fa fa-check"></i>Põhisõnumid</a></li>
<li class="chapter" data-level="" data-path="introduction-2.html"><a href="introduction-2.html#lähtekohad-1"><i class="fa fa-check"></i>Lähtekohad</a></li>
<li class="chapter" data-level="" data-path="introduction-2.html"><a href="introduction-2.html#artiklite-teemad-1"><i class="fa fa-check"></i>Artiklite teemad</a></li>
<li class="chapter" data-level="" data-path="introduction-2.html"><a href="introduction-2.html#eesti-maailmas-1"><i class="fa fa-check"></i>Eesti maailmas</a></li>
<li class="chapter" data-level="" data-path="introduction-2.html"><a href="introduction-2.html#kuidas-edasi-1"><i class="fa fa-check"></i>Kuidas edasi?</a></li>
<li class="chapter" data-level="" data-path="introduction-2.html"><a href="introduction-2.html#viidatud-allikad-7"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="2.1" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html"><i class="fa fa-check"></i><b>2.1</b> Public space as an interconnecting network within the living environment</a><ul>
<li class="chapter" data-level="" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#avalik-ruum-on-võrgustik-mis-seob-inimeste-elu--töö--ja-tegevuskohad"><i class="fa fa-check"></i>Avalik ruum on võrgustik, mis seob inimeste elu-, töö- ja tegevuskohad</a></li>
<li class="chapter" data-level="" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#avaliku-ruumi-kvaliteedi-määrab-eelkõige-selle-sidusus-kõigile-kasutajatele"><i class="fa fa-check"></i>Avaliku ruumi kvaliteedi määrab eelkõige selle sidusus kõigile kasutajatele</a></li>
<li class="chapter" data-level="" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#avaliku-ruumi-mõiste-on-eesti-õigussüsteemis-sisustamata"><i class="fa fa-check"></i>Avaliku ruumi mõiste on Eesti õigussüsteemis sisustamata</a></li>
<li class="chapter" data-level="" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#avalik-sektor-ei-ole-end-üldjuhul-teadvustanud-avaliku-ruumi-esindaja-ja-tellijana"><i class="fa fa-check"></i>Avalik sektor ei ole end üldjuhul teadvustanud avaliku ruumi esindaja ja tellijana</a></li>
<li class="chapter" data-level="" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#avalik-ruum-kui-võrgustik-on-tagatud-siis-kui-riik-ja-omavalitsused-tähtsustavad-seda-igas-ruumiotsuses-ja-igas-mõõtkavas"><i class="fa fa-check"></i>Avalik ruum kui võrgustik on tagatud siis, kui riik ja omavalitsused tähtsustavad seda igas ruumiotsuses ja igas mõõtkavas</a></li>
<li class="chapter" data-level="" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#kokkuvõte-3"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="public-space-as-an-interconnecting-network-within-the-living-environment.html"><a href="public-space-as-an-interconnecting-network-within-the-living-environment.html#viidatud-allikad-8"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="built-heritage-and-spatial-quality.html"><a href="built-heritage-and-spatial-quality.html"><i class="fa fa-check"></i><b>2.2</b> Built heritage and spatial quality</a><ul>
<li class="chapter" data-level="" data-path="built-heritage-and-spatial-quality.html"><a href="built-heritage-and-spatial-quality.html#ehituspärand-aitab-luua-mitmekesist-ruumi"><i class="fa fa-check"></i>Ehituspärand aitab luua mitmekesist ruumi</a></li>
<li class="chapter" data-level="" data-path="built-heritage-and-spatial-quality.html"><a href="built-heritage-and-spatial-quality.html#olemasolevate-ehitiste-säilitamine-on-kestliku-ruumilise-arengu-alus"><i class="fa fa-check"></i>Olemasolevate ehitiste säilitamine on kestliku ruumilise arengu alus</a></li>
<li class="chapter" data-level="" data-path="built-heritage-and-spatial-quality.html"><a href="built-heritage-and-spatial-quality.html#üksikutel-ruumiotsustel-on-suur-mõju-nii-kultuuripärandile-kui-ka-regionaalarengule"><i class="fa fa-check"></i>Üksikutel ruumiotsustel on suur mõju nii kultuuripärandile kui ka regionaalarengule</a></li>
<li class="chapter" data-level="" data-path="built-heritage-and-spatial-quality.html"><a href="built-heritage-and-spatial-quality.html#mälestised-on-ühine-hüve-ja-jagatud-vastutus"><i class="fa fa-check"></i>Mälestised on ühine hüve ja jagatud vastutus</a></li>
<li class="chapter" data-level="" data-path="built-heritage-and-spatial-quality.html"><a href="built-heritage-and-spatial-quality.html#kokkuvõte-4"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="built-heritage-and-spatial-quality.html"><a href="built-heritage-and-spatial-quality.html#viidatud-allikad-9"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html"><i class="fa fa-check"></i><b>2.3</b> Urban activism in the co-creation of public space</a><ul>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#ruumiaktivism-on-ajas-muutuv-ja-eesmärkidest-sõltuv-ruumipoliitiline-tegevus"><i class="fa fa-check"></i>Ruumiaktivism on ajas muutuv ja eesmärkidest sõltuv ruumipoliitiline tegevus</a></li>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#ruumiaktivism-rakendab-olemasolevaid-ja-leiutab-uusi-osalusdemokraatia-mudeleid"><i class="fa fa-check"></i>Ruumiaktivism rakendab olemasolevaid ja leiutab uusi osalusdemokraatia mudeleid</a></li>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#ruumiaktivism-kannustab-kodanikuühiskonna-arengut"><i class="fa fa-check"></i>Ruumiaktivism kannustab kodanikuühiskonna arengut</a></li>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#ruumiloomes-osalevate-liikumiste-ja-üksikisikute-mõju-väljendub-uutes-osaluskultuuri-vormides"><i class="fa fa-check"></i>Ruumiloomes osalevate liikumiste ja üksikisikute mõju väljendub uutes osaluskultuuri vormides</a></li>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#aktivismi-väljakutsed-ruumiloomes"><i class="fa fa-check"></i>Aktivismi väljakutsed ruumiloomes</a></li>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#kokkuvõte-5"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="urban-activism-in-the-co-creation-of-public-space.html"><a href="urban-activism-in-the-co-creation-of-public-space.html#viidatud-allikad-10"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html"><i class="fa fa-check"></i><b>2.4</b> Data-driven spatial planning</a><ul>
<li class="chapter" data-level="" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html#avalikest-ruumiandmetest-on-ühiskonnal-ainult-võita"><i class="fa fa-check"></i>Avalikest ruumiandmetest on ühiskonnal ainult võita</a></li>
<li class="chapter" data-level="" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html#andmepõhine-ruumiloome-eestis-on-lapsekingades"><i class="fa fa-check"></i>Andmepõhine ruumiloome Eestis on lapsekingades</a></li>
<li class="chapter" data-level="" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html#koostatud-ruumianalüüside-ja-tehtud-otsuste-vahelised-seosed-on-harva-tuvastatavad"><i class="fa fa-check"></i>Koostatud ruumianalüüside ja tehtud otsuste vahelised seosed on harva tuvastatavad</a></li>
<li class="chapter" data-level="" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html#aeg-andmepõhise-ruumiloome-juurutamiseks-on-küps"><i class="fa fa-check"></i>Aeg andmepõhise ruumiloome juurutamiseks on küps</a></li>
<li class="chapter" data-level="" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html#sabassörkijast-on-võimalik-tõusta-eestvedajaks"><i class="fa fa-check"></i>Sabassörkijast on võimalik tõusta eestvedajaks</a></li>
<li class="chapter" data-level="" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html#kokkuvõte-6"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="data-driven-spatial-planning.html"><a href="data-driven-spatial-planning.html#viidatud-allikad-11"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="natural-environment-as-a-public-good.html"><a href="natural-environment-as-a-public-good.html"><i class="fa fa-check"></i><b>3</b> Natural environment as a public good</a><ul>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#põhisõnumid-3"><i class="fa fa-check"></i>Põhisõnumid</a></li>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#looduskeskkonna-seisundist-keskkonnaõigluse-ja-keskkonnademokraatiani"><i class="fa fa-check"></i>Looduskeskkonna seisundist keskkonnaõigluse ja keskkonnademokraatiani</a></li>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#looduskeskkonna-ühiskondlik-roll-vajab-senisest-terviklikumat-jälgimist"><i class="fa fa-check"></i>Looduskeskkonna ühiskondlik roll vajab senisest terviklikumat jälgimist</a></li>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#eesti-looduse-seisundi-koondnäitajad-on-halvenenud"><i class="fa fa-check"></i>Eesti looduse seisundi koondnäitajad on halvenenud</a></li>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#looduses-viibimiseks-on-palju-valikuid-kuid-need-ahenevad"><i class="fa fa-check"></i>Looduses viibimiseks on palju valikuid, kuid need ahenevad</a></li>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#koduümbruse-loodus-ja-asulate-rohealad-vajavad-senisest-enam-tähelepanu"><i class="fa fa-check"></i>Koduümbruse loodus ja asulate rohealad vajavad senisest enam tähelepanu</a></li>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#tulevikuvaade-1"><i class="fa fa-check"></i>Tulevikuvaade</a></li>
<li class="chapter" data-level="" data-path="introduction-3.html"><a href="introduction-3.html#viidatud-allikad-12"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="3.1" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html"><i class="fa fa-check"></i><b>3.1</b> How do people use the natural environment in Estonia?</a><ul>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#eesti-looduskeskkonna-avaliku-kasutamise-alus-on-igaüheõigus"><i class="fa fa-check"></i>Eesti looduskeskkonna avaliku kasutamise alus on igaüheõigus</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#eesti-loodus--ja-matkarajad-pakuvad-häid-puhkevõimalusi"><i class="fa fa-check"></i>Eesti loodus- ja matkarajad pakuvad häid puhkevõimalusi</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#kaitsealade-külastajaskond-suureneb-ja-mitmekesistub"><i class="fa fa-check"></i>Kaitsealade külastajaskond suureneb ja mitmekesistub</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#linnades-on-palju-rohealasid-kuid-nende-kvaliteet-vajab-tähelepanu"><i class="fa fa-check"></i>Linnades on palju rohealasid, kuid nende kvaliteet vajab tähelepanu</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#teave-inimeste-looduskasutuse-kohta-on-lünklik"><i class="fa fa-check"></i>Teave inimeste looduskasutuse kohta on lünklik</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#pool-elanikkonnast-käib-marjul-või-seenel"><i class="fa fa-check"></i>Pool elanikkonnast käib marjul või seenel</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#loodusandide-korjamist-toetavad-loodusharidus-liikuvus-ja-maastiku-planeerimine"><i class="fa fa-check"></i>Loodusandide korjamist toetavad loodusharidus, liikuvus ja maastiku planeerimine</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#jahipidamine-ühendab-loodusharrastuse-ja-ühiskondliku-ootuse"><i class="fa fa-check"></i>Jahipidamine ühendab loodusharrastuse ja ühiskondliku ootuse</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#harrastuskalastajate-arv-on-eestis-püsiv"><i class="fa fa-check"></i>Harrastuskalastajate arv on Eestis püsiv</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#kokkuvõte-7"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="how-do-people-use-the-natural-environment-in-estonia.html"><a href="how-do-people-use-the-natural-environment-in-estonia.html#viidatud-allikad-13"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="the-impact-of-natural-areas-on-peoples-well-being.html"><a href="the-impact-of-natural-areas-on-peoples-well-being.html"><i class="fa fa-check"></i><b>3.2</b> The impact of natural areas on people’s well-being</a><ul>
<li class="chapter" data-level="" data-path="the-impact-of-natural-areas-on-peoples-well-being.html"><a href="the-impact-of-natural-areas-on-peoples-well-being.html#loodusalade-pindala-seos-eesti-täiskasvanute-tervisehinnangutega"><i class="fa fa-check"></i>Loodusalade pindala seos Eesti täiskasvanute tervisehinnangutega</a></li>
<li class="chapter" data-level="" data-path="the-impact-of-natural-areas-on-peoples-well-being.html"><a href="the-impact-of-natural-areas-on-peoples-well-being.html#loodusaladest-saadavat-tervisekasu-ei-arvestata-planeerimisel-piisavalt"><i class="fa fa-check"></i>Loodusaladest saadavat tervisekasu ei arvestata planeerimisel piisavalt</a></li>
<li class="chapter" data-level="" data-path="the-impact-of-natural-areas-on-peoples-well-being.html"><a href="the-impact-of-natural-areas-on-peoples-well-being.html#inimesed-seisavad-silmitsi-loodusalade-nõrgenenud-puhverdusvõimega"><i class="fa fa-check"></i>Inimesed seisavad silmitsi loodusalade nõrgenenud puhverdusvõimega</a></li>
<li class="chapter" data-level="" data-path="the-impact-of-natural-areas-on-peoples-well-being.html"><a href="the-impact-of-natural-areas-on-peoples-well-being.html#loodusalade-potentsiaal-avaneb-hariduse-kaudu"><i class="fa fa-check"></i>Loodusalade potentsiaal avaneb hariduse kaudu</a></li>
<li class="chapter" data-level="" data-path="the-impact-of-natural-areas-on-peoples-well-being.html"><a href="the-impact-of-natural-areas-on-peoples-well-being.html#kokkuvõte-8"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="the-impact-of-natural-areas-on-peoples-well-being.html"><a href="the-impact-of-natural-areas-on-peoples-well-being.html#viidatud-allikad-14"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="shaping-natural-areas-for-public-use.html"><a href="shaping-natural-areas-for-public-use.html"><i class="fa fa-check"></i><b>3.3</b> Shaping natural areas for public use</a><ul>
<li class="chapter" data-level="" data-path="shaping-natural-areas-for-public-use.html"><a href="shaping-natural-areas-for-public-use.html#loodusalade-planeerimisel-lähtutakse-lähimuspõhimõttest"><i class="fa fa-check"></i>Loodusalade planeerimisel lähtutakse lähimuspõhimõttest</a></li>
<li class="chapter" data-level="" data-path="shaping-natural-areas-for-public-use.html"><a href="shaping-natural-areas-for-public-use.html#loodusalade-seisundit-mõjutavad-nii-rahvusvahelised-arengueesmärgid-kui-ka-riiklik-valdkonnapoliitika"><i class="fa fa-check"></i>Loodusalade seisundit mõjutavad nii rahvusvahelised arengueesmärgid kui ka riiklik valdkonnapoliitika</a></li>
<li class="chapter" data-level="" data-path="shaping-natural-areas-for-public-use.html"><a href="shaping-natural-areas-for-public-use.html#loodusaladel-on-erinevad-juurdepääsuvõimalused-ja-kasutuskitsendused"><i class="fa fa-check"></i>Loodusaladel on erinevad juurdepääsuvõimalused ja kasutuskitsendused</a></li>
<li class="chapter" data-level="" data-path="shaping-natural-areas-for-public-use.html"><a href="shaping-natural-areas-for-public-use.html#rohevõrgustik-seob-loodusalad-tervikuks-kuid-selle-toimimine-pole-tervikuna-tagatud"><i class="fa fa-check"></i>Rohevõrgustik seob loodusalad tervikuks, kuid selle toimimine pole tervikuna tagatud</a></li>
<li class="chapter" data-level="" data-path="shaping-natural-areas-for-public-use.html"><a href="shaping-natural-areas-for-public-use.html#kokkuvõte-9"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="shaping-natural-areas-for-public-use.html"><a href="shaping-natural-areas-for-public-use.html#viidatud-allikad-15"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html"><i class="fa fa-check"></i><b>3.4</b> Public participation in decisions on the use of natural areas</a><ul>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#aastate-sündmused-tingisid-nõukogude-eestis-avaliku-keskkonnaarutelu"><i class="fa fa-check"></i>1980. aastate sündmused tingisid Nõukogude Eestis avaliku keskkonnaarutelu</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#eesti-praegune-osalemis--ja-keskkonnainfo-avalikustamise-normistik-on-hea"><i class="fa fa-check"></i>Eesti praegune osalemis- ja keskkonnainfo avalikustamise normistik on hea</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#avaliku-ruumi-kujundamisel-on-avalikkusel-üldjuhul-õigus-kaasa-rääkida"><i class="fa fa-check"></i>Avaliku ruumi kujundamisel on avalikkusel üldjuhul õigus kaasa rääkida</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#hoolimata-õigusest-osaleda-on-eesti-elanikud-passiivsed-ja-pessimistlikud"><i class="fa fa-check"></i>Hoolimata õigusest osaleda on Eesti elanikud passiivsed ja pessimistlikud</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#sihtrühmad-ootavad-tõhusamate-kaasamismeetodite-kasutuselevõttu"><i class="fa fa-check"></i>Sihtrühmad ootavad tõhusamate kaasamismeetodite kasutuselevõttu</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#sisuka-kaasarääkimise-eelduseks-on-keskkonnainfo-olemasolu-ja-kättesaadavus"><i class="fa fa-check"></i>Sisuka kaasarääkimise eelduseks on keskkonnainfo olemasolu ja kättesaadavus</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#loodust-jälgiv-elanikkond-edendab-kodanikuühiskonda"><i class="fa fa-check"></i>Loodust jälgiv elanikkond edendab kodanikuühiskonda</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#kokkuvõte-10"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="public-participation-in-decisions-on-the-use-of-natural-areas.html"><a href="public-participation-in-decisions-on-the-use-of-natural-areas.html#viidatud-allikad-16"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estonian-deliberative-space.html"><a href="estonian-deliberative-space.html"><i class="fa fa-check"></i><b>4</b> Estonian deliberative space</a><ul>
<li class="chapter" data-level="" data-path="introduction-4.html"><a href="introduction-4.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction-4.html"><a href="introduction-4.html#põhisõnumid-4"><i class="fa fa-check"></i>Põhisõnumid</a></li>
<li class="chapter" data-level="" data-path="introduction-4.html"><a href="introduction-4.html#lähtekohad-2"><i class="fa fa-check"></i>Lähtekohad</a></li>
<li class="chapter" data-level="" data-path="introduction-4.html"><a href="introduction-4.html#artiklite-kokkuvõte"><i class="fa fa-check"></i>Artiklite kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="introduction-4.html"><a href="introduction-4.html#kuidas-edasi-2"><i class="fa fa-check"></i>Kuidas edasi?</a></li>
<li class="chapter" data-level="" data-path="introduction-4.html"><a href="introduction-4.html#viidatud-allikad-17"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="4.1" data-path="socio-political-discussion-in-the-digital-public-space.html"><a href="socio-political-discussion-in-the-digital-public-space.html"><i class="fa fa-check"></i><b>4.1</b> Socio-political discussion in the digital public space</a><ul>
<li class="chapter" data-level="" data-path="socio-political-discussion-in-the-digital-public-space.html"><a href="socio-political-discussion-in-the-digital-public-space.html#sotsiaalmeedia-lubavused-soodustavad-emotsioonipõhist-suhtlust"><i class="fa fa-check"></i>Sotsiaalmeedia lubavused soodustavad emotsioonipõhist suhtlust</a></li>
<li class="chapter" data-level="" data-path="socio-political-discussion-in-the-digital-public-space.html"><a href="socio-political-discussion-in-the-digital-public-space.html#interneti-kasutamine-eestis"><i class="fa fa-check"></i>Interneti kasutamine Eestis</a></li>
<li class="chapter" data-level="" data-path="socio-political-discussion-in-the-digital-public-space.html"><a href="socio-political-discussion-in-the-digital-public-space.html#suletud-tähendusloome-tekitab-polariseerumist"><i class="fa fa-check"></i>Suletud tähendusloome tekitab polariseerumist</a></li>
<li class="chapter" data-level="" data-path="socio-political-discussion-in-the-digital-public-space.html"><a href="socio-political-discussion-in-the-digital-public-space.html#avatud-tähendusloome-kaasab-eri-osapooli"><i class="fa fa-check"></i>Avatud tähendusloome kaasab eri osapooli</a></li>
<li class="chapter" data-level="" data-path="socio-political-discussion-in-the-digital-public-space.html"><a href="socio-political-discussion-in-the-digital-public-space.html#kokkuvõte-11"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="socio-political-discussion-in-the-digital-public-space.html"><a href="socio-political-discussion-in-the-digital-public-space.html#viidatud-allikad-18"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html"><i class="fa fa-check"></i><b>4.2</b> Estonian youth in the virtual opinion space</a><ul>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#eesti-lapsed-kasutavad-internetti-iga-päev"><i class="fa fa-check"></i>Eesti lapsed kasutavad internetti iga päev</a></li>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#laste-digitaalne-kirjaoskus-paraneb"><i class="fa fa-check"></i>Laste digitaalne kirjaoskus paraneb</a></li>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#digiosalus-ei-paelu-eesti-noori"><i class="fa fa-check"></i>Digiosalus ei paelu Eesti noori</a></li>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#eesti-noorte-osalustüübid"><i class="fa fa-check"></i>Eesti noorte osalustüübid</a></li>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#noorte-digiosalust-takistavad-tegurid"><i class="fa fa-check"></i>Noorte digiosalust takistavad tegurid</a></li>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#noored-tajuvad-virtuaalse-arvamusruumi-kitsaskohti"><i class="fa fa-check"></i>Noored tajuvad virtuaalse arvamusruumi kitsaskohti</a></li>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#kokkuvõte-12"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li><a href="estonian-youth-in-the-virtual-opinion-space.html#tänusõnad-1"><em>Tänusõnad</em></a></li>
<li class="chapter" data-level="" data-path="estonian-youth-in-the-virtual-opinion-space.html"><a href="estonian-youth-in-the-virtual-opinion-space.html#viidatud-allikad-19"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="the-deliberative-space-shaped-by-the-press.html"><a href="the-deliberative-space-shaped-by-the-press.html"><i class="fa fa-check"></i><b>4.3</b> The deliberative space shaped by the press</a><ul>
<li class="chapter" data-level="" data-path="the-deliberative-space-shaped-by-the-press.html"><a href="the-deliberative-space-shaped-by-the-press.html#metsandusdebatis-ei-toonud-avalik-arutelu-eksperte-üksteisele-lähemale"><i class="fa fa-check"></i>Metsandusdebatis ei toonud avalik arutelu eksperte üksteisele lähemale</a></li>
<li class="chapter" data-level="" data-path="the-deliberative-space-shaped-by-the-press.html"><a href="the-deliberative-space-shaped-by-the-press.html#kokkuvõte-14"><i class="fa fa-check"></i>Kokkuvõte</a></li>
<li class="chapter" data-level="" data-path="the-deliberative-space-shaped-by-the-press.html"><a href="the-deliberative-space-shaped-by-the-press.html#viidatud-allikad-21"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="estonian-living-environment-in-2050.html"><a href="estonian-living-environment-in-2050.html"><i class="fa fa-check"></i><b>5</b> Estonian living environment in 2050</a><ul>
<li class="chapter" data-level="" data-path="introduction-5.html"><a href="introduction-5.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction-5.html"><a href="introduction-5.html#põhisõnumid-5"><i class="fa fa-check"></i>Põhisõnumid</a></li>
<li class="chapter" data-level="" data-path="introduction-5.html"><a href="introduction-5.html#mis-on-stsenaariumiplaneerimine"><i class="fa fa-check"></i>Mis on stsenaariumiplaneerimine?</a></li>
<li class="chapter" data-level="" data-path="introduction-5.html"><a href="introduction-5.html#peamised-suundumused"><i class="fa fa-check"></i>Peamised suundumused</a></li>
<li><a href="introduction-5.html#tänusõnad-2"><em>Tänusõnad</em></a></li>
<li class="chapter" data-level="" data-path="introduction-5.html"><a href="introduction-5.html#kasutatud-prognoosid-ja-stsenaariumid"><i class="fa fa-check"></i>Kasutatud prognoosid ja stsenaariumid</a></li>
<li class="chapter" data-level="" data-path="introduction-5.html"><a href="introduction-5.html#viidatud-allikad-22"><i class="fa fa-check"></i>Viidatud allikad</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="estonia-2050-scenarios.html"><a href="estonia-2050-scenarios.html"><i class="fa fa-check"></i>Estonia 2050 scenarios</a><ul>
<li class="chapter" data-level="" data-path="estonia-2050-scenarios.html"><a href="estonia-2050-scenarios.html#tulevikustsenaarumide-põhiteljed-on-asustusstruktuur-ja-avalik-ruum"><i class="fa fa-check"></i>Tulevikustsenaarumide põhiteljed on asustusstruktuur ja avalik ruum</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="estonia-voluntarily-forced-into-cities.html"><a href="estonia-voluntarily-forced-into-cities.html"><i class="fa fa-check"></i>Estonia voluntarily forced into cities</a></li>
<li class="chapter" data-level="" data-path="one-hour-estonia.html"><a href="one-hour-estonia.html"><i class="fa fa-check"></i>One-hour Estonia</a></li>
<li class="chapter" data-level="" data-path="estonia-of-rogues-and-rascals.html"><a href="estonia-of-rogues-and-rascals.html"><i class="fa fa-check"></i>Estonia of rogues and rascals</a></li>
<li class="chapter" data-level="" data-path="self-sufficient-estonia.html"><a href="self-sufficient-estonia.html"><i class="fa fa-check"></i>Self-sufficient Estonia</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contributors-and-editors.html"><a href="contributors-and-editors.html"><i class="fa fa-check"></i><b>6</b> Contributors and Editors</a><ul>
<li class="chapter" data-level="" data-path="contributors-and-editors.html"><a href="contributors-and-editors.html#editor-in-chief"><i class="fa fa-check"></i>Editor-in-chief</a></li>
<li class="chapter" data-level="" data-path="contributors-and-editors.html"><a href="contributors-and-editors.html#editors"><i class="fa fa-check"></i>Editors</a></li>
<li class="chapter" data-level="" data-path="contributors-and-editors.html"><a href="contributors-and-editors.html#contributors"><i class="fa fa-check"></i>Contributors</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="info.html"><a href="info.html"><i class="fa fa-check"></i><b>7</b> Info</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estonian Human Development Report 2019/2020</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction" class="section level2 unnumbered chapter_section chapter0_section intro_section">
<h2>Introduction</h2>
<h1>
Eesti ruumiline areng
</h1>
<div class="authors">
<div class="author-links">
<p><strong><a href="contributors-and-editors.html#helen-sooväli-sepping">Helen Sooväli-Sepping</a> ja <a href="contributors-and-editors.html#antti-roose">Antti Roose</a></strong></p>
</div>
<div>
<p><a class="print-btn" href="../print/EIA-2019-0-Sissejuhatus.pdf"><i class="fa fa-file" aria-hidden="true"></i>Trükiversioon</a></p>
</div>
</div>
<div id="põhisõnumid" class="section level3 unnumbered chapter0_section">
<h3>Põhisõnumid</h3>
<div class="points">
<ul>
<li>
Eesti on inimarengus edenenud maailma riikide hulgas 30. positsioonile, kuid jäänud sinna püsima.
</li>
</ul>
<p>
Eesti elanike heaolu kasv on olnud võrrelduna teiste maailma riikidega tähelepanuväärne. Riigisiseselt süveneb piirkondlik sotsiaalne kihistumine.
</p>
<ul>
<li>
Eesti suurlinnastumist väljendab Suur-Tallinna jätkuv kasv: inimesed, majandus ja teenused koonduvad Tallinna linnapiirkonda ning ülejäänud Eesti kahaneb ja taandareneb.
</li>
</ul>
<p>
Eestile kui tervikule tekitab suurlinnastumine tasakaalutust nii riikluses, halduses, majanduses, elu-, ruumi- ja keskkonnakvaliteedis. On aeg hakata tegema linnapoliitikat, luua riiklik raamistik ja sihtmeetmed, lähtudes linnapiirkondadest, mitte linnapiiridest.
</p>
<ul>
<li>
Eestlaste mitmepaiksus seob Tallinna maakondadega ning linnad küladega.
</li>
</ul>
<p>
Inimeste igapäevaste tegevusruumide laienemine ja haldusreform on toonud kaasa ruumilise identiteedi lahjenemise. Autokasutusel põhinev elulaad, elu- ja tegevuskorraldus võimaldab tegutseda samaaegselt nii linnas kui ka maal. Mitmes kohas elamine, mis on tingitud töörändest, maakodudest, perevõrgustikest, sõpruskondadest, õppimisest ja vaba aja veetmisest, eeldab senisest paindlikumat ruumiplaneerimist ja halduskorraldust.
</p>
<ul>
<li>
Avalik arutelu loob parema elukeskkonna ja püüdleb ühismeelele.
</li>
</ul>
<p>
Aruteluks vajalike oskuste arendamine on riiklik huvi. Osalusdemokraatia edendamiseks on vaja senisest enam toimivaid, läbipaistvaid ning tagasisidestamisel põhinevaid kodanikkonna kaasamisviise. Sellele aitavad kaasa nii digiplatvormid, analüütilisel argumentatsioonil põhinev meediaruum, asjatundlikud ametnikud kui ka usaldusväärsed eksperdid. See kõik tagab teadmiste vahetuse ning loob usaldust riigi ja tema kodanike vahel.
</p>
<ul>
<li>
Ehituspärand ja loodusalad kultuuri osana tugevdavad Eesti inimeste keskkonnasuhet ja kodutunnet.
</li>
</ul>
<p>
Mitmekesise elukeskkonna eeldus on säästva arengu põhimõtetest lähtuv ehituspärandi kaitse koos investeeringukavaga, mis tagab riigile oluliste hoonete säilitamise, kasutuselevõtu ja haldamise. Eesti inimeste keskkonnateadlikkus on kiiretes ja järskudes muutustes, mis selgitab viimaste aastate ühiskondlikke vastasseise loodusalade kasutamisel. Loodusalade teadlik planeerimine ja parem külastuskorraldus aitab parandada linlaste tervist ning hoida sidet loodusega.
</p>
</div>
<p>President Lennart Meri kuulutas Eesti Vabariigi 78. aastapäeva kõnes 24. veebruaril 1996:</p>
<p><em>„Milles peitub Eesti tugevus? [—] Et Eesti asub täpselt seal, kus ta asub. Et Eesti on täpselt nii suur, nagu ta on.“</em></p>
<p>Maismaad on Eestil katastris täpselt 43 465 km<sup>2</sup> (Maa-amet 2020). Eesti maa – nii maaressurss, geograafilised kohad, nende otstarve ja kasutus, linnad-külad kui ka loodus – on rahvuslik vara. Eesti on ja areneb siin sellel maal, võõrsõnaga „territooriumil“, teaduskeelselt „ruumis“. Eesti inimarengu aruande 2019/2020 põhiteema on Eesti ruumiline areng Eesti inimeste heaolu mõjutavates ja ühiskondlikes protsessides. Kuidas taasluua ja kasvatada Eesti ruumilist rikkust, kvaliteeti ja tasakaalu demokraatlikult ja kogu ühiskonna huvides, on selle aruande alusküsimus.</p>
<p>Läheneme ruumi mõistele (ingl <em>space</em>, <em>spatial</em>) viies peatükis võimalikult laialt, nii eri mõõtkavades kui ka eri tähendustes. Laiendame mõistet geograafiliselt kogu Eestile, võttes tähelepanu alla asustusstruktuuri, loodusalad, linnaruumi, sealhulgas linnadisaini ja meid ühendava aruteluruumi. Samuti kirjeldame Eesti demokraatia tervist ruumilises muutuses, säästva arengu ja ühiskonna sidususe vaatenurgast, rõhudes elukõlbliku, inimsõbraliku, inimmõõtmelise ruumi ühisloomele. Seega, ruum selle aruande katusterminina tähistab ühist ruumi, mis pälvib avalikku huvi ja pakub ühiskondlikku hüve.</p>
<p>Mitmes aruande artiklis kerkib üles küsimus demokraatlikest ruumisuhetest avalikus ruumis, kus avalik huvi vastandub isiklikule ja eraõiguslikule huvile. Kui avalik on avalik ruum (ingl <em>public space</em>), see küsimus on ühiskonnas viimastel aastatel teravalt kerkinud nii linnaruumi kui ka tootmisettevõtete, korterelamute, teede ja muude objektide planeerimisel, nii seoses looduses viibimisega kui ka metsade raadamisega. Tõepoolest, avalikku ruumi saab mõista avaliku ja era(statud) ruumi vastanduses. Ehkki 40% Eesti maaressursist on riigiomandis, 1% kuulub omavalitsustele, on ka selle ruumi n-ö avalikkus piiratud, näiteks riigikaitsemaa. Samuti võib avalik huvi puudutada ka seda 59% Eesti territooriumist, mis on eraomand.</p>
<div class="blockquote-right">
<p>
Ruum ise mõjutab inimeste olemist ja käitumist ning kujundab mõtteviisi nii kollektiivsel kui ka üksikisiku tasandil.
</p>
</div>
<p>Ruumil on ühtlasi oluline roll ühiskondlike protsesside kujundamisel. Avaliku ruumi, sealhulgas eraõigusliku ruumi kasutamine ja kujundamine peegeldab seda, kuidas ühiskond on organiseeritud. Mida avatum ja demokraatlikum on ühiskond, seda paremad on kaasarääkimise võimalused ruumi kujundamisel ja läbipaistvamad ruumiotsused. Ruum ise mõjutab inimeste olemist ja käitumist ning kujundab mõtteviisi nii kollektiivsel kui ka üksikisiku tasandil. Lisaks on avaliku ruumi olemus viimastel kümnenditel tugevasti muutunud. Suhtlemine digiplatvormidel pakub avaraid võimalusi kohtumisteks nii tuttavate kui ka võõrastega. Nii võib digitaalne aruteluruum olla täiendus linnaväljakule või külaplatsile. Avalik digitaalne ja füüsiline ruum on omavahel tihedalt läbi põimunud, tekitades aja ja ruumi tihenemise efekti – digitaalselt saame olla samal ajal mitmes ruumis korraga.</p>
</div>
<div id="eesti-on-inimarengus-edenenud-maailma-riikide-hulgas-30.-positsioonile-kuid-jäänud-sinna-püsima" class="section level3 unnumbered chapter0_section">
<h3>Eesti on inimarengus edenenud maailma riikide hulgas 30. positsioonile, kuid jäänud sinna püsima</h3>
<p>Aastast 1990 ÜRO Arenguprogrammi poolt kasutusele võetud inimarengu indeksi kohaselt kuulub Eesti väga kõrge inimarengu tasemega riikide hulka. Eesti on 30. kohal indeksiga 0,882 ning püsinud samal positsioonil viimased kuus aastat (<a href="introduction.html#table01">tabel 0.1</a>). Indeks võtab arvesse oodatavat eluiga, keskmiselt koolis käidud aastaid ning võrreldavates hindades SKPd ühe elaniku kohta. Euroopa Liidu keskmise oodatava elueaga võrreldes elavad Eesti elanikud (78,6 aastat) keskmiselt 3 aastat vähem. Oodatav eluiga sõltub mitmest mõjutajast: keskkonnast, tervishoiuteenuste kättesaadavusest, inimeste elatustasemest ja terviseteadlikkusest. Eestis on oodatav eluiga pikem linnalistes piirkondades, eesti rahvusest ja kõrgemalt haritud elanikkonna hulgas (<a href="introduction.html#Statistikaamet2018">Säästva arengu näitajad 2018</a>). Haridus on jätkuvalt au sees ja väga oluline. Eestist käivad õpilased maailmas kauem koolis vaid Šveitsis, Ameerika Ühendriikides ja Kanadas.</p>
<p>Heaolu kasv on märkimisväärne ning toonud käibele loosungi „Eestil pole kunagi nii hästi läinud kui täna“. Mõõtmisest ja indeksisüsteemist olulisem on andmete kvaliteet ja nende sisusse süvenemine. Kett on täpselt nii tugev, kui on tema nõrgim lüli, ehk teisisõnu, elanikkond on nii jõukas, kui tema materiaalselt kõige nõrgemalt kindlustatud ühiskonnagrupid. Statistikaameti andmetel elas 2019. aastal suhtelises vaesuses 284 300 (21,7%) ja absoluutses vaesuses 31 400 (2,4%) Eesti inimest. Ligikaudu pool eakatest kogevad suhtelist vaesust. Kui vaesusriskis elavate elanike osatähtsus on viimastel aastatel aeglaselt, aga siiski vähenenud, ei ole elanikkonna rikkama ja vaesema viiendiku erinevus võrreldes 2017. aastaga muutunud. Eesti heaolu suurenemisest ei ole osa saanud kõik elanikkonna grupid, saati kõik piirkonnad. Erinevused keskmises elueas, haridustasemes ja sissetulekutes avalduvad piirkondlikult ning on seotud ühtlasi keskkonnaseisundiga (<a href="introduction.html#RahvastikuterviseAK2030">Rahvastiku tervise arengukava 2020–2030</a>).</p>
<p>Selle sajandi esimestel kümnenditel on maailmas haigusi, nälga ja vaesust tõrjudes saavutatud elustandardi kiire kasv. Kuid tänapäeval on maailm uue ebavõrdsuslaine võimuses ning 2019. aasta lõpus ilmunud globaalse inimarengu aruande keskne teema on ebavõrdsus kui inimeste heaolu kõige suurem takistaja. Aruannet raamistab tulevikku suunatud sõnum, et viimasel aastakümnel on lisandunud kaks uut üleilmset suundumust, mis mõjutavad inimeste heaolu kõikjal maailmas: tehnoloogia kättesaadavus ja kliimamuutus. Tehnoloogilised edulood nagu tehisintellekt ja masinõpe süvendavad lõhet nende elanikerühmade ja riikide vahel, kel ei ole võimalusi tehnoloogilise arenguga kaasa minna. Kliimakriis tabab juba praegu valusamini vaesemaid maailma piirkondi ja vähekindlustatud elanikerühmi. Hinnanguliselt põhjustab kliimamuutus maailmas aastatel 2030–2050 alatoitumise, malaaria, kõhulahtisuse ja kuumarabanduse tõttu 250 000 lisasurma aastas (<a href="introduction.html#ÜRO2019">ÜRO 2019</a>).</p>
<p class="caption" id="table01">
<span class="figure-number">Tabel 0.1</span> Inimarengu indeks ja selle alusnäitajad valitud riikides (2018)
</p>
<div style="overflow-x:auto;">
<table class="table table-bordered table-hover table-condensed" id="table_01">
<thead>
<tr>
<th title="Field #1"" align="left !important">Järje- koht</th>
<th title="Field #2" class="table_01_country">
Riik
</th>
<th title="Field #3">
Inimarengu indeksi väärtus
</th>
<th title="Field #4">
Oodatav eluiga sünnihetkel (a)
</th>
<th title="Field #5">
Eeldatav kooli- aastate arv
</th>
<th title="Field #6">
Keskmine kooli- aastate arv
</th>
<th title="Field #7">
SKP inimese kohta (2011 ostujõu pariteedi alusel, USD)
</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left" class="table_01_nr">
1
</td>
<td class="table_01_country">
Norra
</td>
<td>
0,954
</td>
<td>
82,3
</td>
<td>
18,1
</td>
<td>
12,6
</td>
<td>
68 059
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
2
</td>
<td class="table_01_country">
Šveits
</td>
<td>
0,946
</td>
<td>
83,6
</td>
<td>
16,2
</td>
<td>
13,4
</td>
<td>
59 375
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
3
</td>
<td class="table_01_country">
Iirimaa
</td>
<td>
0,942
</td>
<td>
82,1
</td>
<td>
18,8
</td>
<td>
12,5
</td>
<td>
55 660
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
4
</td>
<td class="table_01_country">
Saksamaa
</td>
<td>
0,939
</td>
<td>
81,2
</td>
<td>
17,1
</td>
<td>
14,1
</td>
<td>
46 946
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
4
</td>
<td class="table_01_country">
Hongkong
</td>
<td>
0,939
</td>
<td>
84,7
</td>
<td>
16,5
</td>
<td>
12
</td>
<td>
60 221
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
6
</td>
<td class="table_01_country">
Austraalia
</td>
<td>
0,938
</td>
<td>
83,3
</td>
<td>
22,1
</td>
<td>
12,7
</td>
<td>
44 097
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
6
</td>
<td class="table_01_country">
Island
</td>
<td>
0,938
</td>
<td>
82,9
</td>
<td>
19,2
</td>
<td>
12,5
</td>
<td>
47 566
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
8
</td>
<td class="table_01_country">
Rootsi
</td>
<td>
0,937
</td>
<td>
82,7
</td>
<td>
18,8
</td>
<td>
12,4
</td>
<td>
47 955
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
9
</td>
<td class="table_01_country">
Singapur
</td>
<td>
0,935
</td>
<td>
83,5
</td>
<td>
16,3
</td>
<td>
11,5
</td>
<td>
83 793
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
10
</td>
<td class="table_01_country">
Holland
</td>
<td>
0,933
</td>
<td>
82,1
</td>
<td>
18
</td>
<td>
12,2
</td>
<td>
50 013
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
11
</td>
<td class="table_01_country">
Taani
</td>
<td>
0,93
</td>
<td>
80,8
</td>
<td>
19,1
</td>
<td>
12,6
</td>
<td>
48 836
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
12
</td>
<td class="table_01_country">
Soome
</td>
<td>
0,925
</td>
<td>
81,7
</td>
<td>
19,3
</td>
<td>
12,4
</td>
<td>
41 779
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
13
</td>
<td class="table_01_country">
Kanada
</td>
<td>
0,922
</td>
<td>
82,3
</td>
<td>
16,1
</td>
<td>
13,3
</td>
<td>
43 602
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
14
</td>
<td class="table_01_country">
Uus-Meremaa
</td>
<td>
0,921
</td>
<td>
82,1
</td>
<td>
18,8
</td>
<td>
12,7
</td>
<td>
35 108
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
15
</td>
<td class="table_01_country">
Suurbritannia
</td>
<td>
0,92
</td>
<td>
81,2
</td>
<td>
17,4
</td>
<td>
13
</td>
<td>
39 507
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
15
</td>
<td class="table_01_country">
USA
</td>
<td>
0,92
</td>
<td>
78,9
</td>
<td>
16,3
</td>
<td>
13,4
</td>
<td>
56 140
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
17
</td>
<td class="table_01_country">
Belgia
</td>
<td>
0,919
</td>
<td>
81,5
</td>
<td>
19,7
</td>
<td>
11,8
</td>
<td>
43 821
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
18
</td>
<td class="table_01_country">
Lichtenstein
</td>
<td>
0,917
</td>
<td>
80,5
</td>
<td>
14,7
</td>
<td>
12,5
</td>
<td>
99 732
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
19
</td>
<td class="table_01_country">
Jaapan
</td>
<td>
0,915
</td>
<td>
84,5
</td>
<td>
15,2
</td>
<td>
12,8
</td>
<td>
40 799
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
20
</td>
<td class="table_01_country">
Austria
</td>
<td>
0,914
</td>
<td>
81,4
</td>
<td>
16,3
</td>
<td>
12,6
</td>
<td>
46 231
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
21
</td>
<td class="table_01_country">
Luksemburg
</td>
<td>
0,909
</td>
<td>
82,1
</td>
<td>
14,2
</td>
<td>
12,2
</td>
<td>
65 543
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
22
</td>
<td class="table_01_country">
Iisreal
</td>
<td>
0,906
</td>
<td>
82,8
</td>
<td>
16
</td>
<td>
13
</td>
<td>
33 650
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
22
</td>
<td class="table_01_country">
Lõuna-Korea
</td>
<td>
0,906
</td>
<td>
82,8
</td>
<td>
16,4
</td>
<td>
12,2
</td>
<td>
36 757
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
24
</td>
<td class="table_01_country">
Sloveenia
</td>
<td>
0,902
</td>
<td>
81,2
</td>
<td>
17,4
</td>
<td>
12,3
</td>
<td>
32 143
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
25
</td>
<td class="table_01_country">
Hispaania
</td>
<td>
0,893
</td>
<td>
83,4
</td>
<td>
17,9
</td>
<td>
9,8
</td>
<td>
35 041
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
26
</td>
<td class="table_01_country">
Tšehhi
</td>
<td>
0,891
</td>
<td>
79,2
</td>
<td>
16,8
</td>
<td>
12,7
</td>
<td>
31 597
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
26
</td>
<td class="table_01_country">
Prantsusmaa
</td>
<td>
0,891
</td>
<td>
82,5
</td>
<td>
15,5
</td>
<td>
11,4
</td>
<td>
40 511
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
28
</td>
<td class="table_01_country">
Malta
</td>
<td>
0,885
</td>
<td>
82,4
</td>
<td>
15,9
</td>
<td>
11,3
</td>
<td>
34 795
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
29
</td>
<td class="table_01_country">
Itaalia
</td>
<td>
0,883
</td>
<td>
83,4
</td>
<td>
16,2
</td>
<td>
10,2
</td>
<td>
36 141
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
30
</td>
<td class="table_01_est table_01_country">
Eesti
</td>
<td class="table_01_est">
0,882
</td>
<td class="table_01_est">
78,6
</td>
<td class="table_01_est">
16,1
</td>
<td class="table_01_est">
13
</td>
<td class="table_01_est">
30 379
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
34
</td>
<td class="table_01_country">
Leedu
</td>
<td>
0,869
</td>
<td>
75,7
</td>
<td>
16,5
</td>
<td>
13
</td>
<td>
29 775
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
39
</td>
<td class="table_01_country">
Läti
</td>
<td>
0,854
</td>
<td>
75,2
</td>
<td>
16
</td>
<td>
12,8
</td>
<td>
26 301
</td>
</tr>
<tr>
<td align="left" class="table_01_nr">
49
</td>
<td class="table_01_country">
Venemaa
</td>
<td>
0,824
</td>
<td>
72,4
</td>
<td>
15,5
</td>
<td>
12
</td>
<td>
25 036
</td>
</tr>
</tbody>
</table>
</div>
<div class="imgsource">
<p>
<span class="imgsource-source">Allikas:</span> ÜRO 2019.
</p>
</div>
</div>
<div id="eesti-suurlinnastumist-väljendab-suur-tallinna-jätkuv-kasv-inimesed-majandus-ja-teenused-koonduvad-tallinna-linnapiirkonda-ning-ülejäänud-eesti-kahaneb-ja-taandareneb" class="section level3 unnumbered chapter0_section">
<h3>Eesti suurlinnastumist väljendab Suur-Tallinna jätkuv kasv: inimesed, majandus ja teenused koonduvad Tallinna linnapiirkonda ning ülejäänud Eesti kahaneb ja taandareneb</h3>
<p>Eesti kaart on lihtne. On suurlinn Tallinn, on ülikoolilinn Tartu, on suvituslinn Pärnu, on hilistööstuslik Kirde-Eesti, järjest enam puhke-, põllu- ja metsamajanduslik Lõuna-Eesti ja meretagused saared. Lihtsamalt saab Eesti jagada kaheks – on Tallinn ja (muu) Eesti: kaheksast viieni töiselt tegusad maakonnalinnad ning rahvuspargistuv ääremaa. Need ei ole sildid, vaid Eesti tegelik ruumistruktuur ja haldusjaotus (<a href="introduction.html#figure01">joonis 0.1</a>). Ruumilise arengu mõttes on sotsiaalteadlaste 2000. aastal osutatud „Kaks Eestit“ saanud nüüd reaalsuseks (vt <a href="introduction.html#Lauristin2001">Lauristin 2001</a>; <a href="introduction.html#Vetik2002">Vetik 2002</a>).</p>
<p>Järjest enam arutleb teadlaskond planetaarse linnastumise teemadel, selgitades ja täpsustades linnastumisprotsesside üha tugevamat mõju üleilmastumisele, keskuskohtade ja linnaalade hägustumist ning hävitavat survet loodusele (<a href="introduction.html#Schmidt2018">Schmidt 2018</a>). Linnastumisprotsess põimib kokku turumajanduslikud globaalvõrgustikku ühendatud tegevused ning intensiivistab maakasutust. Maapiirkonnad muudetakse agrotööstuskompleksideks, loodust kaubastatakse näiteks turismi eesmärgil, rajatakse tööstusparke, samuti kaupade transportimiseks mõeldud logistika- ja transporditaristud.</p>
<p class="caption" id="figure01">
<span class="figure-number">Joonis 0.1</span> Eesti linnasüsteem (alates 2000 elanikust, 2019. aasta rahvaarvu alusel)
</p>
<pre><code>## Reading layer `maakond_20200101&#39; from data source `/Users/taavetkutsar/Documents/GitHub.nosync/EIA_2019/data/0_fig1_data/maakond_20200101.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 15 features and 2 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 369032.1 ymin: 6377141 xmax: 739152.8 ymax: 6634019
## epsg (SRID):    3301
## proj4string:    +proj=lcc +lat_1=58 +lat_2=59.33333333333334 +lat_0=57.51755393055556 +lon_0=24 +x_0=500000 +y_0=6375000 +ellps=GRS80 +units=m +no_defs</code></pre>
<pre><code>##                MNIMI MKOOD                       geometry
## 1   Viljandi maakond  0084 MULTIPOLYGON (((621049.2 64...
## 2       Hiiu maakond  0039 MULTIPOLYGON (((418045.8 65...
## 3      Harju maakond  0037 MULTIPOLYGON (((505059.9 65...
## 4      Lääne maakond  0056 MULTIPOLYGON (((460628.3 65...
## 5      Rapla maakond  0071 MULTIPOLYGON (((504136.5 65...
## 6 Lääne-Viru maakond  0060 MULTIPOLYGON (((657694.1 65...</code></pre>
<pre><code>## Reading layer `asustusyksus_20200301&#39; from data source `/Users/taavetkutsar/Documents/GitHub.nosync/EIA_2019/data/0_fig1_data/asustusyksus_20200301.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 4713 features and 7 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 369032.1 ymin: 6377141 xmax: 739152.8 ymax: 6634019
## epsg (SRID):    3301
## proj4string:    +proj=lcc +lat_1=58 +lat_2=59.33333333333334 +lat_0=57.51755393055556 +lon_0=24 +x_0=500000 +y_0=6375000 +ellps=GRS80 +units=m +no_defs</code></pre>
<pre><code>##                            ANIMI AKOOD TYYP          ONIMI OKOOD
## 1 Väikeheinamaa küla / Lillängin  9619    8    Viimsi vald  0890
## 2                 Saviranna küla  7498    8 Jõelähtme vald  0245
## 3             Kristiine linnaosa  0339    6        Tallinn  0784
## 4              Mustamäe linnaosa  0482    6        Tallinn  0784
## 5                      Salu küla  7392    8       Rae vald  0653
## 6                    Patika küla  6036    8       Rae vald  0653
##           MNIMI MKOOD                       geometry
## 1 Harju maakond  0037 MULTIPOLYGON (((527958.2 66...
## 2 Harju maakond  0037 MULTIPOLYGON (((558032.7 65...
## 3 Harju maakond  0037 MULTIPOLYGON (((538249.5 65...
## 4 Harju maakond  0037 MULTIPOLYGON (((536316.3 65...
## 5 Harju maakond  0037 MULTIPOLYGON (((559679.9 65...
## 6 Harju maakond  0037 MULTIPOLYGON (((552250.8 65...</code></pre>
<pre><code>## Reading layer `omavalitsus_20200301&#39; from data source `/Users/taavetkutsar/Documents/GitHub.nosync/EIA_2019/data/0_fig1_data/omavalitsus_20200301.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 79 features and 5 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 369032.1 ymin: 6377141 xmax: 739152.8 ymax: 6634019
## epsg (SRID):    3301
## proj4string:    +proj=lcc +lat_1=58 +lat_2=59.33333333333334 +lat_0=57.51755393055556 +lon_0=24 +x_0=500000 +y_0=6375000 +ellps=GRS80 +units=m +no_defs</code></pre>
<pre><code>##           ONIMI OKOOD         MNIMI MKOOD TYYP
## 1    Ruhnu vald  0689 Saare maakond  0074    1
## 2     Muhu vald  0478 Saare maakond  0074    1
## 3   Viimsi vald  0890 Harju maakond  0037    1
## 4 Saaremaa vald  0714 Saare maakond  0074    1
## 5  Hiiumaa vald  0205  Hiiu maakond  0039    1
## 6    Kihnu vald  0303 Pärnu maakond  0068    1
##                         geometry
## 1 MULTIPOLYGON (((456706.5 64...
## 2 MULTIPOLYGON (((463418.4 64...
## 3 MULTIPOLYGON (((545381.9 65...
## 4 MULTIPOLYGON (((383834.7 64...
## 5 MULTIPOLYGON (((418045.8 65...
## 6 MULTIPOLYGON (((499610.8 64...</code></pre>
<pre><code>## $tm_layout
## $tm_layout$frame
## [1] FALSE
## 
## $tm_layout$asp
## [1] 1.777778
## 
## $tm_layout$outer.margins
## [1] 0
## 
## $tm_layout$inner.margins
## [1] 0.02 0.10 0.02 0.02
## 
## $tm_layout$legend.outside
## [1] FALSE
## 
## $tm_layout$legend.width
## [1] 0.25
## 
## $tm_layout$legend.height
## [1] 0.7
## 
## $tm_layout$legend.title.size
## [1] 1
## 
## $tm_layout$legend.text.size
## [1] 1
## 
## $tm_layout$legend.format
## $tm_layout$legend.format$text.separator
## [1] &quot;kuni&quot;
## 
## 
## $tm_layout$style
## [1] NA
## 
## 
## attr(,&quot;class&quot;)
## [1] &quot;tm&quot;</code></pre>
<p><img src="../figures/0-intro/fig01.png" width="100%" style="display: block; margin: auto;" /></p>
<div class="imgsource">
<div>
<p><span class="imgsource-source">Allikas:</span> Statistikaamet.</p>
</div>
<div>
<p><a class="data-btn" href="data/0_fig1_data.zip"><i class="fa fa-download" aria-hidden="true"></i>Laadi andmed</a></p>
</div>
</div>
<div class="blockquote-right">
<p>
Linnastumisprotsess põimib kokku turumajanduslikud globaalvõrgustikku ühendatud tegevused ning intensiivistab maakasutust.
</p>
</div>
<p>Linna tähendust ja mõju ei saa mõõta üksnes linnavormi, tiheduse ja teiste ruumitunnustega. Tänapäeva linn määratleb end halduspiire ületava sotsiaalruumilise jõuna (<a href="introduction.html#Brenner2019">Brenner 2019</a>). Nii ei ole ka Eesti linn praegu enam traditsioonilise arusaama kohaselt ühe selgelt eristuva linnakeskusega tööstuslik tiheasula. Praegused 47 halduspiiridega linna moodustavad Eestis linnasüsteemi tinglikult, sest enam kui poolel neist napib 21. sajandi mõistes suurust ja linnalisi omadusi. Eestis väljendub linnastumine linnaalade laienemise ja linnarahvastiku kasvuna Tallinnas. Linnapiirkondlikud majandusteooriad seletavad praegust suurlinnastumist süveneva tasakaalutuse ja kasvu koondumisena (<a href="introduction.html#Nijkamp2013">Nijkamp ja Kourtit 2013</a>). Nende majandusmudelite õpikunäide on Eesti. Linnastumisel, iseäranis suurlinnastumisel on arvestatavad negatiivsed välismõjud eeskätt linnaruumi- ja keskkonnakasutuses, aga ka sotsiaalses plaanis, nagu näiteks ühiskonna kihistumises. Eesti linnastumist 2000. aastatel iseloomustasid kiired euroopalikud õigus-, haldus- ja sotsiaal-majanduslikud muutused (<a href="introduction.html#Raagmaa2014">Raagmaa jt 2014</a>) (<a href="introduction.html#table02">tabel 0.2</a>). 2010. aastatel toimus Euroopas majandustõusu uuel lainel suurlinnade kokkusulamine hiigelregioonideks (London-Manchester, Pariis-Brüssel-Amsterdam-Saksa linnastud; Rooma-Milano-Torino). Nõnda ei ole Tallinn teiste suurlinnade seas sugugi suur, Euroopa Liidus elanike arvu poolest alles 59. kohal.</p>
<p class="caption" id="table02">
<span class="figure-number">Tabel 0.2</span> Euroopa ja Eesti linnapoliitika võtmearengud
</p>
<div style="overflow-x:auto;">
<table class="table table-bordered table-hover table-condensed" id="table_02">
<thead>
<tr>
<th title="Field #1">
Aastakümnend
</th>
<th title="Field #2">
Euroopa areng
</th>
<th title="Field #3">
Euroopa võtmeprotsessid
</th>
<th title="Field #4">
Linnapoliitika võtmeteemad „vanas” Euroopas
</th>
<th title="Field #5">
Linnapoliitika võtmeteemad Eestis
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="table_02_red">
1990
</td>
<td>
Ühisturu integratsioon ja üleeuroopalised taristud, sh transpordivõrk.
</td>
<td>
Demokratiseerimine ja riigireformid Kesk- ja Ida-Euroopas.
</td>
<td>
Kultuur ja turism. Konkurentsipoliitika.
</td>
<td>
Üleminekureformid, sh maa- ja omandireform ning linnahaldus. Erastamine ja kinnisvaraturu teke.
</td>
</tr>
<tr>
<td class="table_02_red">
2000
</td>
<td>
Euroopa Liidu itta laienemine. Terrorism.
</td>
<td>
Majandusbuum ja finantskriis.
</td>
<td>
Suurlinnastud. Elukvaliteet.
</td>
<td>
Linnaplaneerimine. Kinnisvarabuum, sh eeslinnastumislaine, uued keskused ja linnataristud ning ärilinnak.
</td>
</tr>
<tr>
<td class="table_02_red">
2010
</td>
<td>
Hiigelregioonid suurlinnastute võrgustikuna.
</td>
<td>
Majanduse taastumine. Kokkuhoiupoliitika.
</td>
<td>
Nutikas spetsialiseerumine. Tehnoloogiline areng ja innovatsioon.
</td>
<td>
Suurarendused ja suurtaristud. Keskklassistumine. Avaliku ruumi teema esilekerkimine. Kaasav linn ja kodanikuaktivismi teke.
</td>
</tr>
<td class="table_02_red">
2020 ja tulevik
</td>
<td>
Deglobaliseerumine. Euroopa geopoliitilise positsiooni hoidmine maailmas. Kliimaneutraalsus.
</td>
<td>
Majanduskriis. Brexit. Roheline lepe. Digitaalsus. Populism. Euroopa kultuuri kaitse.
</td>
<td>
Säästlik, tark hooliv linn. „Uus” demokraatia.
</td>
<td>
Rail Baltica. Talsinki. Kestlik kahanemine. Sotsiaalsüsteemid.
</td>
</tr>
</tbody>
</table>
</div>
<div class="imgsource">
<p>
<span class="imgsource-source">Allikas:</span> Clark jt 2018; Mäntysalo jt 2019; Raagmaa jt 2014.
</p>
</div>
<p>Linnaareng tervikuna põhineb Eestis linnamaa laienemisel, maavõtul. Aastatel 2000–2017 on asustusalade pindala Eestis suurenenud 138 km<sup>2</sup> võrra (<a href="#maakasutuse-muutused-linna-ja-maa-tähenduse-moondumine">Oja, ptk 1</a>). Maakasutuse muutusena on Eestis neil aastatel tinglikult rajatud juurde üheksa Viljandi linna, aga tegelikkuses ega kaardil ühtegi uut linna pole. Samal ajal iseloomustab linnade kasvu killustatus ja hajumine. Akadeemik Mart Kalm on pannud diagnoosi Eesti ehitatud ruumile (<a href="introduction.html#Kalm2018">Kalm 2018</a>):</p>
<p><em>„Võrreldes ülejäänud Euroopaga on piinlik tunnistada, kui vähe tähelepanu pöörame tänapäeval jätkusuutlikkusele. [—] Vaesus ja muutuvad olud on harva lasknud terviklikel keskkondadel tekkida, mistõttu modernset Eestit iseloomustab rohkem keskkonna katkendlikkus.“</em></p>
<div class="blockquote-left">
<p>
21⁣. sajandi kahe esimese aastakümne suurlinnastumine on juba kujundanud Eesti arengulugu.
</p>
</div>
<p>Praeguse seisuga elab linnakeskkonnas 920 000 inimest ehk 69% Eesti elanikest, kellest omakorda Suur-Tallinnas umbes 550 000 ehk 40% Eesti elanikest (<a href="#planeerimisvabaduse-võidukäik-eeslinna-eestis">Roose, ptk 1</a>). 21. sajandi kahe esimese aastakümne suurlinnastumine on juba kujundanud Eesti arengulugu, kuid ei ole veel võrreldav massilise elamuehituse ja sisserändeajastuga 1970.–1980. aastatel. Suur-Tallinna kasv 2010. aastatel on tähendanud laialdasi ja veel suuremaid kinnisvaraarendusi ning liiklustaristut, linnaasumite segregatsiooni (<a href="introduction.html#Tammaru2020">Tammaru jt 2020</a>), uusasumite killustatud laienemist (<a href="#planeerimisvabaduse-võidukäik-eeslinna-eestis">Roose, ptk 1</a>) ning vähenevat avalikku linnaruumi (<a href="#avalik-ruum-kui-elukeskkonda-siduv-võrgustik">Paaver ja Kiivet, ptk 2</a>). Kiire autostumise kasvuga võtavad üha suurema osa linnade territooriumist enda alla sõiduteed ja parkimiskohad (<a href="#eesti-elukeskkond-aastal-2050">Grišakov, ptk 5</a>). Ka taristuinvesteeringud on suunatud eelkõige sõiduteedesse, vähem kõnni- ja jalgrattateedesse, linnaväljakutesse ja parkidesse. Autostumisega kaasnev inimeste vähene füüsiline liikuvus (<a href="#ligipääsetavuse-muutused-autostunud-eestis">Tuvikene jt, ptk 1</a>) võib omakorda mõjutada füüsilist ja vaimset tervist, mille näitajad tingituna ülekaalulisusest ja vaimsetest häiretest on terves Eestis viimastel kümnenditel languses (<a href="introduction.html#Statistikaamet2018">Säästva arengu näitajad 2018</a>). Sillutatud ja ehitatud linnamaaks ohverdatakse linnarohelus, mis on teravnevas kliimakriisis omandanud järjest olulisema tähenduse nii elurikkuse ja süsinikusalvena kui ka linna tehiskeskkonna ja inimeste tekitatud keskkonnamõjude puhastamisel ja puhverdamisel (<a href="#loodusalade-kujundamine-avalikuks-kasutuseks">Poom ja Sepp, ptk 3</a>; <a href="introduction.html#Hansis2015">Hansis jt 2015</a>; <a href="introduction.html#EEA2019">EEA 2019a</a>). Tormakas linnakasvus põrkuvad sageli avalikud ja erahuvid (nt Viimsi valla arendustegevus, Tallinnas Kalamaja tihendamine jne; vt <a href="#avalik-ruum-kui-elukeskkonda-siduv-võrgustik">Paaver ja Kiivet, ptk 2</a>; <a href="#aktivism-avaliku-ruumi-koosloomes">Kljavin jt, ptk 2</a>; <a href="#ühiskondlik-poliitiline-diskussioon-digitaalses-avalikus-ruumis">Ventsel ja Madisson, ptk 4</a>).</p>
<p>Tallinnale pakub arengupotentsiaali kaksiklinnastumine Helsingiga. Teadmusmajandust ja innovatsiooni arendav tulevikulinn Talsinki võiks liita Helsingi üleilmselt tunnustatud teadmus- ja elukvaliteedi Tallinna uuenduslikkuse ja kasvuhooga. Kui nii läheb, siis sünnib miljonilinn, maailmalinn (<a href="#eesti-elukeskkond-aastal-2050">Grišakov, ptk 5</a>).</p>
</div>
<div id="eesti-inimeste-mitmepaiksus-seob-tallinna-maakondadega-ja-linnad-küladega" class="section level3 unnumbered chapter0_section">
<h3>Eesti inimeste mitmepaiksus seob Tallinna maakondadega ja linnad küladega</h3>
<p>Kõik maakonnad peale Harjumaa on kahanemas. Aastatel 2000–2018 lisandus Harjumaale 10% rahvastikku, samal ajal kui Tartumaa rahvastik vähenes 4%, teistes maakondades jäi elanikke vähemaks kümnendiku kuni veerandi võrra. Kahanemine on suurlinnastumise pöördprotsess. Selle näiteks on ühe Tallinna uue eeslinnaasumi ja ühe maa-aleviku rahvastikupüramiid (<a href="introduction.html#figure02">joonis 0.2</a>). Tallinna eeslinnaasumis elavad noored lastega pered, maa-alevikus üle viiekümnesed. Kahanev on piirkond, mille elanikkond väheneb olulisel määral ühe põlvkonna jooksul. Maakonnad kaugenevad Tallinnast nii ruumiliselt, majanduslikult, sotsiaalselt, elutingimuste poolest kui ka kultuuriliselt (<a href="#nüüdisaegsed-elamistingimused-kelle-privileeg">Kährik ja Väiko, ptk 1</a>; <a href="#keskuse-ja-ääremaa-lõhe-eestis">Plüschke-Altof jt, ptk 1</a>). Selle arengu keskmes on viimasel kümnendil vastuseid ootav küsimuste kimp: kas kahanevatel maakonnalinnadel on jõudu, et maakondi käima tõmmata; kas ettevõtluskeskkond on piisavalt elav ja mitmekesine ning kas tööjõubaas ja -areaal on küllaldane majanduse arenguks?</p>
<p class="caption" id="figure02">
<span class="figure-number">Joonis 0.2.</span> Tallinna eeslinna asumi vs maa-aleviku rahvastikupüramiid
</p>
<div class="desktop-plot">
<pre><code>## Warning: package &#39;plotly&#39; was built under R version 3.6.2</code></pre>
<div id="htmlwidget-185c01600c529dbccdd0" style="width:100%;height:504px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-185c01600c529dbccdd0">{"x":{"data":[{"orientation":"h","width":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],"base":[-9,-10,-7,-6,-5,-6,-9,-12,-10,-5,-5,-4,-4,-4,-4,-4,-1,-1,-1],"x":[9,10,7,6,5,6,9,12,10,5,5,4,4,4,4,4,1,1,1],"y":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],"text":["Vanus: 0-4<br />Sugu: Mehed","Vanus: 5-9<br />Sugu: Mehed","Vanus: 10-14<br />Sugu: Mehed","Vanus: 15-19<br />Sugu: Mehed","Vanus: 20-24<br />Sugu: Mehed","Vanus: 25-29<br />Sugu: Mehed","Vanus: 30-34<br />Sugu: Mehed","Vanus: 35-39<br />Sugu: Mehed","Vanus: 40-44<br />Sugu: Mehed","Vanus: 45-49<br />Sugu: Mehed","Vanus: 50-54<br />Sugu: Mehed","Vanus: 55-59<br />Sugu: Mehed","Vanus: 60-64<br />Sugu: Mehed","Vanus: 65-69<br />Sugu: Mehed","Vanus: 70-74<br />Sugu: Mehed","Vanus: 75-79<br />Sugu: Mehed","Vanus: 80-84<br />Sugu: Mehed","Vanus: 85-89<br />Sugu: Mehed","Vanus: 90+<br />Sugu: Mehed"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(54,155,158,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Mehed","legendgroup":"Mehed","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"h","width":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],"base":[-5,-4,-4,-4,-5,-8,-11,-8,-4,-5,-8,-11,-10,-5,-2,-1,-2,-4,-2],"x":[5,4,4,4,5,8,11,8,4,5,8,11,10,5,2,1,2,4,2],"y":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],"text":["Vanus: 0-4<br />Sugu: Mehed","Vanus: 5-9<br />Sugu: Mehed","Vanus: 10-14<br />Sugu: Mehed","Vanus: 15-19<br />Sugu: Mehed","Vanus: 20-24<br />Sugu: Mehed","Vanus: 25-29<br />Sugu: Mehed","Vanus: 30-34<br />Sugu: Mehed","Vanus: 35-39<br />Sugu: Mehed","Vanus: 40-44<br />Sugu: Mehed","Vanus: 45-49<br />Sugu: Mehed","Vanus: 50-54<br />Sugu: Mehed","Vanus: 55-59<br />Sugu: Mehed","Vanus: 60-64<br />Sugu: Mehed","Vanus: 65-69<br />Sugu: Mehed","Vanus: 70-74<br />Sugu: Mehed","Vanus: 75-79<br />Sugu: Mehed","Vanus: 80-84<br />Sugu: Mehed","Vanus: 85-89<br />Sugu: Mehed","Vanus: 90+<br />Sugu: Mehed"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(54,155,158,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Mehed","legendgroup":"Mehed","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"h","width":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[9,10,6,5,3,7,10,12,9,5,5,5,5,5,4,4,3,2,1],"y":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],"text":["Vanus: 0-4<br />Sugu: Naised","Vanus: 5-9<br />Sugu: Naised","Vanus: 10-14<br />Sugu: Naised","Vanus: 15-19<br />Sugu: Naised","Vanus: 20-24<br />Sugu: Naised","Vanus: 25-29<br />Sugu: Naised","Vanus: 30-34<br />Sugu: Naised","Vanus: 35-39<br />Sugu: Naised","Vanus: 40-44<br />Sugu: Naised","Vanus: 45-49<br />Sugu: Naised","Vanus: 50-54<br />Sugu: Naised","Vanus: 55-59<br />Sugu: Naised","Vanus: 60-64<br />Sugu: Naised","Vanus: 65-69<br />Sugu: Naised","Vanus: 70-74<br />Sugu: Naised","Vanus: 75-79<br />Sugu: Naised","Vanus: 80-84<br />Sugu: Naised","Vanus: 85-89<br />Sugu: Naised","Vanus: 90+<br />Sugu: Naised"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(197,68,9,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Naised","legendgroup":"Naised","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"h","width":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[4,5,1,5,6,8,5,4,3,3,11,7,7,6,5,3,6,5,6],"y":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],"text":["Vanus: 0-4<br />Sugu: Naised","Vanus: 5-9<br />Sugu: Naised","Vanus: 10-14<br />Sugu: Naised","Vanus: 15-19<br />Sugu: Naised","Vanus: 20-24<br />Sugu: Naised","Vanus: 25-29<br />Sugu: Naised","Vanus: 30-34<br />Sugu: Naised","Vanus: 35-39<br />Sugu: Naised","Vanus: 40-44<br />Sugu: Naised","Vanus: 45-49<br />Sugu: Naised","Vanus: 50-54<br />Sugu: Naised","Vanus: 55-59<br />Sugu: Naised","Vanus: 60-64<br />Sugu: Naised","Vanus: 65-69<br />Sugu: Naised","Vanus: 70-74<br />Sugu: Naised","Vanus: 75-79<br />Sugu: Naised","Vanus: 80-84<br />Sugu: Naised","Vanus: 85-89<br />Sugu: Naised","Vanus: 90+<br />Sugu: Naised"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(197,68,9,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Naised","legendgroup":"Naised","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":48.1811579281108,"r":0,"b":27.563304275633,"l":43.5035284350353},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(41,43,44,1)","family":"Montserrat","size":13.2835201328352},"xaxis":{"domain":[0,0.489128071319852],"automargin":true,"type":"linear","autorange":false,"range":[-15.84,15.84],"tickmode":"array","ticktext":[15,10,5,0,5,10,15],"tickvals":[-15,-10,-5,0,5,10,15],"categoryorder":"array","categoryarray":[15,10,5,0,5,10,15],"nticks":null,"ticks":"outside","tickcolor":"rgba(234,234,234,1)","ticklen":3.65296803652968,"tickwidth":0.265670402656704,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"Montserrat","size":10.6268161062682},"tickangle":-0,"showline":true,"linecolor":"rgba(234,234,234,1)","linewidth":0.265670402656704,"showgrid":true,"gridcolor":"rgba(234,234,234,1)","gridwidth":0.265670402656704,"zeroline":false,"anchor":"y","title":"","hoverformat":".2f"},"annotations":[{"text":"%","x":0.5,"y":-0.04151100041511,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(41,43,44,1)","family":"Montserrat","size":13.2835201328352},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"top","annotationType":"axis"},{"text":"Vanus","x":-0.0548538219771097,"y":0.5,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(41,43,44,1)","family":"Montserrat","size":13.2835201328352},"xref":"paper","yref":"paper","textangle":-90,"xanchor":"right","yanchor":"center","annotationType":"axis"},{"text":"Tallinna eeslinn","x":0.244564035659926,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(41,43,44,1)","family":"Montserrat","size":13.2835201328352},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Maa-alevik","x":0.755435964340074,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(41,43,44,1)","family":"Montserrat","size":13.2835201328352},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"}],"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.4,19.6],"tickmode":"array","ticktext":["0-4","5-9","10-14","15-19","20-24","25-29","30-34","35-39","40-44","45-49","50-54","55-59","60-64","65-69","70-74","75-79","80-84","85-89","90+"],"tickvals":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],"categoryorder":"array","categoryarray":["0-4","5-9","10-14","15-19","20-24","25-29","30-34","35-39","40-44","45-49","50-54","55-59","60-64","65-69","70-74","75-79","80-84","85-89","90+"],"nticks":null,"ticks":"outside","tickcolor":"rgba(234,234,234,1)","ticklen":3.65296803652968,"tickwidth":0.265670402656704,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"Montserrat","size":10.6268161062682},"tickangle":-0,"showline":true,"linecolor":"rgba(234,234,234,1)","linewidth":0.265670402656704,"showgrid":true,"gridcolor":"rgba(234,234,234,1)","gridwidth":0.265670402656704,"zeroline":false,"anchor":"x","title":"","hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":0.489128071319852,"y0":0,"y1":1},{"type":"rect","fillcolor":"rgba(255,255,255,1)","line":{"color":"rgba(255,255,255,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":0.489128071319852,"y0":0,"y1":24.9730178497302,"yanchor":1,"ysizemode":"pixel"},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.510871928680148,"x1":1,"y0":0,"y1":1},{"type":"rect","fillcolor":"rgba(255,255,255,1)","line":{"color":"rgba(255,255,255,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0.510871928680148,"x1":1,"y0":0,"y1":24.9730178497302,"yanchor":1,"ysizemode":"pixel"}],"xaxis2":{"type":"linear","autorange":false,"range":[-15.84,15.84],"tickmode":"array","ticktext":[15,10,5,0,5,10,15],"tickvals":[-15,-10,-5,0,5,10,15],"categoryorder":"array","categoryarray":[15,10,5,0,5,10,15],"nticks":null,"ticks":"outside","tickcolor":"rgba(234,234,234,1)","ticklen":3.65296803652968,"tickwidth":0.265670402656704,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"Montserrat","size":10.6268161062682},"tickangle":-0,"showline":true,"linecolor":"rgba(234,234,234,1)","linewidth":0.265670402656704,"showgrid":true,"domain":[0.510871928680148,1],"gridcolor":"rgba(234,234,234,1)","gridwidth":0.265670402656704,"zeroline":false,"anchor":"y","title":"","hoverformat":".2f"},"showlegend":true,"legend":{"bgcolor":"transparent","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(41,43,44,1)","family":"Montserrat","size":10.6268161062682},"y":1.15,"orientation":"h","x":0},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","showSendToCloud":false,"displayModeBar":false},"source":"A","attrs":{"bafe3409043b":{"x":{},"y":{},"fill":{},"type":"bar"}},"cur_data":"bafe3409043b","visdat":{"bafe3409043b":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
<div class="mobile-plot">
<p><img src="EIA_2019_digi_eng_files/figure-html/unnamed-chunk-13-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div class="imgsource">
<div>
<p><span class="imgsource-source">Allikas:</span> Rahvastikuregister.</p>
</div>
<div>
<p><a class="data-btn" href="data/0_fig2_data.csv"><i class="fa fa-download" aria-hidden="true"></i></i>Laadi andmed</a></p>
</div>
</div>
<p>Kahanemisküsimus ei taandu pelgalt töörändele ja suurema sissetuleku otsingutele. Elamufondi ülejääk ja vananemine nii elutingimuste poolest kui ka ehitustehniliselt on muutnud paljud Eesti pered kinnismaisteks, kuivõrd nende kodu turuhind on madal. Samal ajal puudub maakondades noortel peredel võimalus alustada elu uuselamus, uues kodus. Ebavõrdsus elamistingimustes ja kinnisvarahindades, alaealist ja pensioniealist elanikkonda liikuvusvaesusesse lükkav harv ühistransport süvendab üldist regionaalset ebavõrdsust Eestis (<a href="#nüüdisaegsed-elamistingimused-kelle-privileeg">Kährik ja Väiko, ptk 1</a>; <a href="#ligipääsetavuse-muutused-autostunud-eestis">Tuvikene jt, ptk 1</a>).</p>
<div class="blockquote-right">
<p>
Eestis ootab lahendamist kohapõhine targa kahanemise plaan kolmes valdkonnas: töökohad, elukohad, põhiteenused.
</p>
</div>
<p>Maakonnatasandi ja maakonnalinnade nõrgenemine on kiirendanud suundumust kahe-keskuse-Eestiks, mis koosneb Tallinnast ja Tartust, kattes nende tagamaad tunniajase autosõidu raadiuses (<a href="introduction.html#figure03">joonis 0.3</a>). Töökoht liigub Tallinna ja Tartusse ees, elukoht ja teenused tulevad järele. Ülikooliõpingute järel ei naase paljud noored kodukohta, vaid jäävad elama Tallinna või Tartusse. Seda laadi protsessi leevendab eestlaste mitmepaiksus (ingl multilocality). Arvukalt elanikke omab kahte kodu, ühte linnas ja teist maapiirkonnas, kuhu sõidetakse nädalavahetuseti ja suvepuhkuseks. Nendele lisanduvad hargmaised pered, kes elavad piiri taga ja käivad Eestis puhkamas. Hargmaisus on toonud Tallinnale Helsingi ja Stockholmi lähemale näiteks Rakverest või Paidest, seda nii ajageograafiliselt elu- ja töökohtadena kui ka eluoluliselt. Sestap jäävad maakonnad, aga ka ülikoolilinn Tartu üleilmastumisprotsessides siseisolatsiooni (<a href="#sissejuhatus-1">Leetmaa, ptk 1</a>). Ka koduläheduse mõiste on aja ja ruumi tihenemise ja kiirenemise (<a href="introduction.html#Lauristin2017">Lauristin jt 2017</a>) ja linliku elumudeli tõttu muutunud, laienenud ülelinnaliseks või isegi piirkondlikuks. See omakorda on lahjendanud ruumilist identiteeti, hägustanud kodulinna ja koduküla tähendust.</p>
<p class="caption" id="figure03">
<span class="figure-number">Joonis 0.3.</span> Geograaf Edgar Kandi ajalooline Eesti linnasüsteem kehtib põhimõtteliselt ka tänapäeval, sh kahekeskuseline Tallinna- ja Tartu-tõmbeline Eesti ning nende linnade tagamaad autosõiduraadiuses, nn ühe-tunni-Eesti
</p>
<p><img src="../figures/0-intro/fig03.png" width="100%" style="display: block; margin: auto;" /></p>
<div class="imgsource">
<p>
<span class="imgsource-source">Allikas:</span> Kant (1935).
</p>
</div>
<p>Kestliku kahanemise võtit ei ole seni pakkunud ruumilised ümberkorraldused riigihalduses ega ka haldusreform. Üha hõredam asustus ühelt poolt sundis keskvalitsuse nõudmisel maavaldu liituma ja ühiselt maaelu korraldama, kuid teiselt poolt liiguvad teenused ja muud sotsiaalsed võrgustikud linna (ostu- ja vabaajakeskused, haridus- ja raviteenused jm). Ettevõtlust edendavad ja maapiirkondi elavdavad Euroopa Liidu programmid ja projektid on mõjunud tagasihoidlikult, sest on jõudnud suurel määral linnapiirkondadesse (<a href="introduction.html#Regionaalarengustrateegia2019">Eesti regionaalarengu strateegia 2014–2020 seireraport 2019</a>; <a href="introduction.html#Raagmaa2014">Raagmaa jt 2014</a>). Konkurentsivõimele keskenduv regionaalpoliitika on toetanud turumajanduslikke arengusuundumusi ega ole ääremaastumisprotsessi vähendanud (<a href="#keskuse-ja-ääremaa-lõhe-eestis">Plüschke-Altof jt, ptk 1</a>).</p>
<p>Eestis ootab lahendamist kohapõhine targa kahanemise plaan kolmes valdkonnas: töökohad, elukohad, põhiteenused. See eeldab Eesti piirkondade arengu kavandamist ja lahendamist kahes põhimõtteliselt erinevas võtmes: turumajanduslikel printsiipidel kasvu ja konkurentsi ning solidaarsuspõhimõttel kestliku kahanemise võtmes. Eesti vajab kaht haldusmudelit – üht suurlinnastumise, teist kahanemise puhuks.</p>
</div>
<div id="avalik-arutelu-loob-parema-elukeskkonna-ja-püüdleb-ühismeelele" class="section level3 unnumbered chapter0_section">
<h3>Avalik arutelu loob parema elukeskkonna ja püüdleb ühismeelele</h3>
<p>Samavõrd kui avaliku füüsilise ruumi olemus on viimastel kümnenditel olulisel määral muutunud, on muutunud meie suhtluskeskkonnad. Suhtlemine ja sotsialiseerumine digiplatvormidel pakub avaraid võimalusi aruteludeks ja kohtumisteks tuttavate, aga ka täiesti võõraste inimestega. Virtuaalne ruum võtab üle füüsilise ruumi funktsioone (<a href="#sissejuhatus-4">Ibrus, ptk 4</a>). Nii nagu elukeskkond ja füüsiline ruum, peab arutelukeskkond olema mitmekesine ja tasakaalustatud (<a href="#ajakirjanduse-kujundatav-arvamusruum">Kõuts-Klemm, ptk 4</a>). Praegu on traditsiooniline paberväljaannetega ajakirjandus taandumas uute meediavormide ees ning seeläbi võimendamas digilõhet. Ühtlasi on see tähendanud mitmel pool Eestis kohaliku inforuumi ahenemist (<a href="#eesti-noored-virtuaalses-arvamusruumis">Kalmus ja Siibak, ptk 4</a>). See viitab probleemile, et vanemaealised ei saa osa meediaruumist, sest nende digipädevus on ebapiisav (<a href="introduction.html#Tambaum2019">Tambaum 2019</a>).</p>
<p>Avalike teemade arutamisel võrgumeedias on toimunud liikumine argumentatsiooni ülelihtsustumise suunas. Suhtluses valdavad kiiresti mõistetavad ja tugeva emotsionaalse laenguga sõnumid (<a href="#ühiskondlik-poliitiline-diskussioon-digitaalses-avalikus-ruumis">Ventsel ja Madisson, ptk 4</a>). Samal ajal on nii uue meedia kui ka sellest tulenevat kajakambrite mõju aruteluruumile üle hinnatud. Sotsiaalmeediast pärit emotsionaalne suhtlusviis on üle kandunud kogu meediaruumi, kus eksperdi ja tõenduspõhist argumentatsiooni võidakse ära kasutada eri positsioonide vastandamiseks ning argumentide tühistamiseks selle asemel, et leida väitluses ühisosa (<a href="#ekspertide-roll-ja-staatus-ühiskondlikes-meediaaruteludes">Olesk, ptk 4</a>). Samal põhjusel ei soovi Eesti noored osaleda avalikus debatis (<a href="eesti-noored-virtuaalses-arvamusruumis">Kalmus ja Siibak, ptk 4</a>). Suhtluskultuuri kuulub oskus järgida avaliku suhtlemise head tava.</p>
<div class="blockquote-left">
<p>
Suhtluskultuuri kuulub oskus järgida avaliku suhtlemise head tava.
</p>
</div>
<p>Eesti kodanikuühiskonna eestkõnelejad on seisnud hea selle eest, et edendada nii arutelu- kui ka kaasamiskultuuri. Sellegipoolest on kodanikuaktiivsus Eestis vähene, olles näiteks Soomest ja Rootsist enam kui mitukümmend aastat maas (<a href="introduction.html#Ainsaar2019">Ainsaar ja Strenze 2019</a>). Iseseisvunud Eestis on ruumi planeerimise praktikad ja tavad muutunud avatumaks, demokraatlikumaks. See on kinnistamas inimestes arusaama, et kaasamine on osa kvaliteetse elukeskkonna loomisest ja kujundamisest. Ometi iseloomustavad valdava osa Eesti elanike suhtumist kaasamisse pigem passiivsus ja pessimism (<a href="#kaasarääkimise-võimalused-loodusalade-kasutamisel">Vahtrus jt, ptk 3</a>). Põhjusena saab välja tuua vähese tagasisidestamise ja formaalse suhtumise, mis kahandab kaasamise tähendust ja usaldusväärsust ning tekitab kaasamisväsimust. Avaliku ruumi eest seisvad huvirühmad otsivad aktiivselt dialoogipartnereid avaliku sektori või erasektori hulgast ning tõukavad tagant kodanikuühiskonna ja demokraatlikuma kaasamiskultuuri arengut (<a href="#aktivism-avaliku-ruumi-koosloomes">Kljavin jt, ptk 2</a>). Vaatamata sellele on avalik haldus muutunud kohmakalt bürokraatlikuks ja ühtlasi spetsiifiliselt tehnokraatlikuks. Konsensuse – eesti keeli ühismeele – leidmist raskendab erialakeele barjäär planeerijate, projekteerijate ja kodanike vahel. Avalikuks aruteluks interneti sügavustes esitatud tehniliselt detailirohked joonised ja kirjeldused ei jäta tavainimesele võimalust kaasa rääkida oma piirkonna arengus. See omakorda on toonud kaasa arendamise ja ruumilise muutuse eituse, mitte-minu-tagahoovis-suhtumise (ingl NIMBY).</p>
<p>Viimaste aastate konfliktid ruumi planeerimisel ning arutelud loodusalade kasutamisest annavad tunnistust keskkonna väärtuste mitmetimõistmisest.</p>
<div class="blockquote-right">
<p>
Viimaste aastate konfliktid ruumi planeerimisel ning arutelud loodusalade kasutamisest annavad tunnistust keskkonna väärtuste mitmetimõistmisest.
</p>
</div>
<p>Arutelu kehv kvaliteet on infoajastu suurimaid probleeme. Parema ruumi loomiseks ja osapoolte arusaamade selgitamiseks on mitmesuguseid lahendusi. Tasakaalustatud, ühismeelele püüdlev aruteluruum on ühiskonna eri gruppide koostöö ja sidustamise eeldus. Aruteluks vajalike oskuste arendamine on riiklik huvi. Kodanikupädevust ja aruteluoskusi on tarvis parandada, et võimestada kodanikke ja edendada laiapõhjalist demokraatiat. Võimalusi selleks pakuvad arendamisel digiplatvormid, asjatundlikud ametnikud ja usaldusväärsed eksperdid.</p>
</div>
<div id="ehituspärand-ja-loodusalad-kultuuri-osana-tugevdavad-eesti-inimeste-keskkonnasuhet-ja-kodutunnet" class="section level3 unnumbered chapter0_section">
<h3>Ehituspärand ja loodusalad kultuuri osana tugevdavad Eesti inimeste keskkonnasuhet ja kodutunnet</h3>
<p>Kultuuriruumi lahutamatu osa on materiaalne ja füüsiline ruum kui rahvuse enesekirjelduse viis, nii nagu on seda ajaloo- ja tekstinarratiivid. Elukeskkond oma tänaste ja ajalooliste hoonete, linna- ja külastruktuuri, asustusstruktuuri ning maakasutusega kannab endas eri ajalooetappide kihistusi. Seeläbi on maastik koos kujundamise ja kujutamisega üks olulisemaid kollektiivse mälu ja identiteedi loomise vahendeid samamoodi, nagu on seda eestikeelsed tüvitekstid, filmid, teatrietendused või laulu- ja tantsupeod. 2018. aasta kogumik „Eesti säästva arengu näitajad“ sedastab säästva arengu 11. eesmärgis, et kultuuripärandi olukord osutab eesti kultuuri kestlikkusele ja ühiskonna teadlikkusele kultuuripärandi väärtustest.</p>
<p>Riigi esmatähtsad kultuuri- ja mäluasutused Kumu ja ERM on valmis ehitatud. Käes on aeg senisest enam pühenduda olemasoleva arhitektuuri- ja maastikupärandi väärtustamisele. Uusehitiste rajamise kõrval võiks hoonestuses kavakindlamalt eelistada ehituspärandi uuskasutust. Sellest saab sotsiaal-majanduslikku kasu terve piirkond, mitte üksnes konkreetne eluala (<a href="introduction.html#HistoricEngland2019">Historic England 2019</a>). Kultuuripärandi kasutuselevõtt muudab väikelinnad ja maa-alevikud tervikuna atraktiivsemaks nii elanikkonnale kui ka piirkonna külastajatele (<a href="#ehituspärand-ja-ruumikvaliteet">Talk ja Raie, ptk 2</a>). Seda laadi mõtteviisi juurutamise eeldus on põhjalikud sotsiaal-majanduslikud mõjuanalüüsid ja terviklik vaade nii ehituspärandile kui ka tervele piirkonnale, samuti võimalikult paljude osapoolte huvide ja võimalustega arvestamine (<a href="#sissejuhatus-2">Lankots, ptk 2</a>). Samuti on kohane iga objekti puhul küsida, mis on ehituspärandi säilitamise eesmärk või milline on riigi või siis eraomaniku suutlikkus kaitsealustesse objektidesse investeerida. Mitmekesisema elukeskkonna seisukohast vajab Eesti ehituspärand kaitset koos sotsiaal-kultuurilise ning majandusliku mõjuhindamise, riikliku investeeringukava ja meetmetega, mis tagavad riigile prioriteetsete ajalooliste hoonete säilitamise, kasutuselevõtu ja haldamise.</p>
<p>Viimaste kümnendite linnastumisprotsess on avaldanud mõju kultuuriloomele. Eestis on rohkelt säilinud põlvest põlve suulise pärimuse teel edasi kantavaid kultuuripraktikaid, nagu näiteks seenel- ja marjulkäik ning aiasaaduste kasvatamine ja konserveerimine. Loodust kaitstakse ja keskkonnast hoolitakse. Selle tõestuseks on iga-aastane tuhandeid Eesti inimesi koondav „Teeme ära“ talgupäev. RMK puhkealad on linlaste seas ülipopulaarsed ning mitmel pool külastuskoormuse piiril. Sellegipoolest on Eesti elanikkonna kontakt loodusega vähenemas ja nii on paar viimast põlvkonda Eestis kaotamas looduse tundmist laiemalt, samuti esineb põhjendamatut looduskartust (<a href="#kuidas-inimesed-eesti-looduskeskkonda-kasutavad">Sepp ja Lõhmus, ptk 3</a>). Üleeuroopaline ja Eesti elurikkuse ja looduspaikade kadu (<a href="introduction.html#EEA2019b">EEA 2019b</a>; <a href="#sissejuhatus-3">Lõhmus, ptk 3</a>) ning tehiskeskkonna laienemine annavad märku Eesti ühiskonna väärtussüsteemi katkestustest, mis selgitab viimaste aastate konflikte ruumi planeerimisel ja looduskasutuses (<a href="#ekspertide-roll-ja-staatus-ühiskondlikes-meediaaruteludes">Olesk, ptk 4</a>; <a href="#kaasarääkimise-võimalused-loodusalade-kasutamisel">Vahtrus jt, ptk 3</a>). Selline kultuurikatkestus on otseses seoses keskkonnateadlikkuse ja -käitumisega. Meil ei ole võimalik suurendada inimeste ökoloogilist teadlikkust, kui loodusega kokkupuude piirdub telesaadete, ajakirjas avaldatud fotode või loodusmuuseumi külastusega (<a href="introduction.html#Gandy2018">Gandy 2018</a>). Kliimamuutuse ja bioloogilise mitmekesisuse küsimustesse hakatakse ühiskonnas tõsisemalt suhtuma siis, kui inimene kogeb, tajub ja tunnetab loodust vahetult. Terviklik, eesmärgipärane planeerimine Eesti linnapiirkondades peatab inimeste tervisele ja heaolule ülioluliste linnalähedaste ja linnasiseste rohealade täisehitamise.</p>
</div>
<div id="tulevikuvaade" class="section level3 unnumbered chapter0_section">
<h3>Tulevikuvaade</h3>
<p>Linnad on võimsa sotsiaal-majandusliku mõjujõuga, kuid samal ajal haavatavad süsteemid. Inimarengu aruande autorid juhivad järjekindlalt tähelepanu, et Eesti suuremate linnade, kuid eriti Tallinna linnapiirkonna kasv tehiskeskkonna hoonestuse ja taristuna on rajatud tihtipeale inimeste vaimsele ja füüsilisele heaolule tähtsa avaliku ruumi ja roheluse arvelt. Samuti tuuakse välja kliimamuutuse ning kiire autostumise omavahelist seost. Süsinikuheite vähendamine sõltub kliimasõbralikumate liikuvusviiside eelistamisest (<a href="#ligipääsetavuse-muutused-autostunud-eestis">Tuvikene jt, ptk 1</a>).</p>
<p>Näited arvukatest linnadest nii Läänemere piirkonnas kui ka Euroopas laiemalt rõhutavad linnade kasvavat rolli säästva arengu ning innovatsiooni veduritena. Linnade arengut suunab lähitulevikus ja pikemas vaates Euroopa Liidu kliimapoliitika. Mida kliimapoliitikast lähtuv valitsemine kaasa toob? Planeerimisotsuse peamiseks mõõdupuuks saab maakasutuse efektiivsus kliimamuutuse seisukohast. Euroopa kliimapoliitika fookus laieneb lähikümnendil energiakasutuselt maakasutusele, mida praeguses süsinikuheite arvestuses tähistab lühend LULUCF, tähtsustamaks maakasutuse muutuse ja metsanduse rolli süsinikuringes. Üha tähtsamaks saab ringmajandus. Linnakeskkonnas avaldub see linnapiirkondade uuendamises, mahajäetud maa-alade kasutuselevõtus ja vanade hoonete kasutuselevõtus uute hoonete ehitamise asemel.</p>
<p>Säästva arengu põhimõtteid järgivale ja head elukvaliteeti pakkuvale linnakeskkonnale on iseloomulik, et selles on hea olla nii 8- kui ka 80-aastasel inimesel. Uut linnaajastut Eestis edendab Tartu linn teel Euroopa kultuuripealinnaks, määratledes linnakultuuri linnaruumi ja elukeskkonnana. Lähiaastatel eelistab Tartu taristuinvesteeringutes jalakäijaid ja rattureid, vääristab südalinna, rajades lastele ja eakatele sobivaid linnaparke ning luues uut otstarbekohast arhitektuuri ja tänavakultuuri. Ka Pärnu on seadnud eesmärgiks parandada elanikkonna terviseseisundit linnakeskkonna kvaliteeti tõstes. Linnade koostöö ülikoolide ja terviseasutustega tervist toetava keskkonna loomisel võimaldab luua vundamendi rahvatervise parandamiseks ning seeläbi otseste tervisekulude vähendamiseks (<a href="#eesti-elukeskkond-aastal-2050">Grišakov, ptk 5</a>).</p>
<div class="blockquote-right">
<p>
Eesti ei ole oma ääremaastumisega erand, kuid tulenevalt Eesti geopoliitilisest asendist võib see osutuda riikluse probleemiks.
</p>
</div>
<p>Ei Põhjala ega ülejäänud Euroopa pole suutnud seni maapiirkondadele kahanemist pidurdavat poliitikat välja pakkuda. Mõningaid Eestile sobivaid häid näiteid pakuvad eeskujuks Põhjamaad (<a href="introduction.html#Nordregio2017">Nordregio 2017</a>). Eesti ei ole oma ääremaastumisega erand, kuid tulenevalt Eesti geopoliitilisest asendist võib see osutuda riikluse probleemiks. Järjest hõredam püsiasustus piirialadel loob ruumilise vaakumi, kus tegutsevad Eesti sõjaväelised ja jõustruktuurid. See on tihti ainus võimalus tagada riigi kohalolek. Piiriäärsete piirkondade teema eeldab tihedamat koostöös teiste Balti riikidega. Haldusreformi järel vajavad maapiirkondade inimesed kindlustunnet, et kvaliteetsed teenused on kättesaadavad kõigile elanikkonna eagruppidele. Teiste riikide kogemusele tuginedes (samas) võib elanikkonna piirkonda püsimajäämise ja noorte piirkonda meelitamise võti peituda kodanike aktiivses osalemises piirkonna arenguprotsessides ja nende suunamisel. Kohaliku omavalitsuse jõustav, koostööle kutsuv avatud valitsemine tagab usaldusväärse õhkkonna, et koha arengu kavandamine ja elluviimine muutub inimestele oluliseks ning kohalikel elanikel on võimalus ise piirkonna arengut suunata. Need on strateegilised pikaajalised kokkulepped, mis rajanevad usaldusel ja kestavad poliitikaüleselt.</p>
<p>Eesti kodanikuühiskonna lõimimisel valitsuse, ametiasutuste ja kohaliku tasandi otsustusprotsessidesse on kasutamata potentsiaal. Osalusdemokraatia edendamiseks vajame esiteks senisest enam toimivaid, läbipaistvaid ning tagasisidestamisel põhinevaid kodanikkonna kaasamisviise. Need tagavad teadmiste vahetuse ning loovad laiemat usaldust riigi ja tema kodanike vahel. Teine usalduse loomise mehhanism ühiskonnas on andmete kättesaadavus ja nende täpsus. Ühiskonna innovatsiooni veab tark linn, mis põhineb reaalajas jälgitavate avaandmete tõlgendamisel ning eraettevõtete, ülikoolide ja kodanikualgatuste lõimitud teadmussiirdel. Avaandmetel põhinev kodanikuteadus saab täiendavalt pakkuda sotsiaalse innovatsiooni lahendusi linna- ja maakogukondadele ning ühtlasi olla partner riigile ja kohalikele omavalitsustele spetsiifiliste probleemide lahendamisel. Seeläbi on kodanikuühiskond ühiskonna sidusust loov partner, kes kaasamise kaudu mõjutab valitsemise protsesse.</p>
<p>Seda aruannet lõpetades on tervet maailma haaranud tervishoiukriis. Eriti haavatavad on sellises olukorras suurlinnad, kus haigust ohjata on keeruline. Ajaloost tuntud suuremad haiguspuhangud on olulisel määral muutnud linnade ja ühiskondade olemust ja tegevusmustreid. Jääb vaid loota, et kahte praegust üleilmset suurprobleemi – tervise- ja kliimakriisi – lahendatakse korraga ja üheskoos.</p>
</div>
<div id="viidatud-allikad" class="section level3 unnumbered subreferences">
<h3>Viidatud allikad</h3>
<p id="Ainsaar2019">
Ainsaar, M., Strenze, T. (toim.) 2019. Väärtused kui inimvara ja nende seos ühiskonna arenguga. Tallinn, Tartu: Arenguseire Keskus, Tartu Ülikool.
</p>
<p id="Brenner2019">
Brenner, N. 2019. New Urban Spaces: Urban Theory and the Scale Question. Oxford: Oxford University Press.
</p>
<p id="Clark2019">
Clark, G., Moonen, T., Nunley, J. 2019. The Story of Your City: Europe and its Urban Development 1970 to 2020. European Investment Bank.
</p>
<p id="EEA2019">
EEA – European Environmental Agency 2019a. Land and soil in Europe. EEA Signals 2019. Luxembourg: Publications Office of the European Union.
</p>
<p id="EEA2019b">
EEA – European Environmental Agency 2019b. The European environment – state and outlook 2020. Luxembourg: Publications Office of the European Union.
</p>
<p id="Eestiinimvararaport2019">
Eesti inimvara raport 2019. Tallinn: Arenguseire Keskus.
</p>
<p id="Regionaalarengustrateegia2019">
Eesti regionaalarengu strateegia 2014–2020 seireraport 2019. Tallinn: Rahandusministeerium.
</p>
<p id="Gandy2018">
Gandy, M. 2018. Cities in deep time. – Cities, 22 (1), 96–195.
</p>
<p id="Hansis2015">
Hansis, E., Davis, S. J., Pongratz, J. 2015. Relevance of methodological choices for accounting of land use change carbon fluxes. – Global Biogeochemical Cycles, 29 (8), 1230–1246.
</p>
<p id="HistoricEngland2019">
Historic England 2019. – Annual Report &amp; Accounts 2018/2019.
</p>
<p id="Kalm2018">
Kalm, M. 2018. Eesti arhitektuuri 100 aastat. Talust tarbimismaastikuni. Tallinn: Postimehe Kirjastus.
</p>
<p id="Kant1935">
Kant, E. 1935. Bevölkerung und Lebensraum Estlands: ein anthropoökologischer Beitrag zur Kunde Baltoskandias. Tartu: Akadeemiline Kooperatiiv.
</p>
<p id="Lauristin2001">
Lauristin, M. 2001. Kas siirdeaeg on Eestis lõppenud? – Eesti Päevaleht, 25.04.2001.
</p>
<p id="Lauristin2017">
Lauristin, M., Kalmus, V., Keller, M., Kiisel, M., Massu, A., Opermann, S., Vihalemm, P., Vihalemm, T. 2017. Kokkuvõte. Eesti ühiskonda kujundavad protsessid ja tulevikuarengud. – Vihalemm, P., Lauristin, M., Kalmus, V., Vihalemm, T. (toim.) Eesti ühiskond kiirenevas ajas. Uuringu „Mina. Maailm. Meedia“ 2002–2014 tulemused. Tartu: Tartu Ülikooli Kirjastus, 669–723.
</p>
<p id="Mäntysalo2019">
Mäntysalo, R., Kanninen, V., Purkarthofer, E., Koste, O.-W. (toim.) 2019. Kaupunkiseudut: Ristiinvalotuksia ja rajanylityksiä. BEMINE-hankkeen loppuraportti. Aalto-yliopiston julkaisusarja CROSSOVER 3/2019.
</p>
<p id="Nijkamp2013">
Nijkamp, P., Kourtit, K. 2013. The “New Urban Europe”: Global Challenges and Local Responses in the Urban Century. – European Planning Studies, 21 (3), 291–315.
</p>
<p id="Nordregio2017">
Nordregio 2017. White paper on Nordic sustainable cities. Stockholm: Nordregio.
</p>
<p id="Raagmaa2014">
Raagmaa, G., Kalvet, T., Kasesalu, R. 2014. Europeanization and De-Europeanization of Estonian Regional Policy. – European Planning Studies, 22 (4), 775–795.
</p>
<p id="RahvastikuterviseAK2030">
Rahvastiku tervise arengukava 2020–2030. Tööversioon. Tallinn: Sotsiaalministeerium, 2020.
</p>
<p id="Schmidt2018">
Schmidt, C. 2018. Journeys through planetary urbanization: Decentering perspectives on the urban. – Environment and Planning D: Society and Space, 36 (3), 591–610.
</p>
<p id="Statistikaamet2018">
Säästva arengu näitajad 2018. Tallinn: Statistikaamet.
Tambaum, T. 2016. 55+ rahvastiku internetikasutus ja sotsiaalne aktiivsus. – Sakkeus, L., Leppik, L. (toim.). Pilk hallile alale. SHARE Eesti uuringu esimene ülevaade ja soovitused eakate poliitika kujundamiseks. Tallinn: Tallinna Ülikool, 182−205.
</p>
<p id="Tambaum2019">
Tambaum, T. 2019. Vanemas tööeas inimeste interneti kasutus ja sotsiaalne aktiivsus SHARE nelja laine andmetes. – Sakkeus, L., Tambaum, T. (toim.). Vananemine elukaare vaates. SHARE Eesti Uuringu teine ülevaade. Tallinn: Tallinna Ülikool, 71–84.
</p>
<p id="Tammaru2020">
Tammaru, T., Marcinczak, S., Aunap, R., van Ham, M., Janssen, H. 2020. Relationship between income inequality and residential segregation of socioeconomic groups. – Regional Studies, 54 (4), 450–461.
</p>
<p id="Vetik2002">
Vetik, R. (toim.) 2002. Kaks Eestit. Artiklite, ettekannete ja analüüside kogumik. Tallinn: Tallinna Pedagoogikaülikool.
</p>
<p id="ÜRO2019">
ÜRO – UNDP 2019. Human Development Report 2019. Beyond income, beyond averages, beyond today: Inequalities in human development in the 21st century. New York. <a href="http://hdr.undp.org/en/content/human-development-report-2019" class="uri">http://hdr.undp.org/en/content/human-development-report-2019</a>.
</p>

</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="foreword.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="diversity-in-the-estonian-living-environment.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": true,
"weibo": false,
"instapaper": false,
"vk": false,
"all": false,
"google": false
},
"fontsettings": false,
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"scroll_highlight": true,
"toolbar": null,
"position": "fixed",
"edit": null,
"download": null,
"search": true
}
});
});
</script>

</body>

</html>
